# Conditions
#############
# Global Conditions
.if-default-branch-refs: &if-default-branch-refs
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-tag-semver: &if-tag-semver
  if: '$CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/'

.if-merge-request: &if-merge-request
  if: '$CI_MERGE_REQUEST_IID'


# Reusables
################################################################################
variables:
  POETRY_VERSION: "1.1.11"
  POETRY_VIRTUALENVS_CREATE: "true"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"

.install-deps: &install-deps
  needs: []
  before_script:
    - cd ra-data-models
    - cp -r ../backend/ramodels ramodels
    - pip install --no-cache-dir poetry==${POETRY_VERSION}
    - poetry install
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ra-data-models/.venv/

.source-venv: &source-venv
  image: python:3
  needs: [Install ramodels]
  before_script:
    - cd ra-data-models
    - cp -r ../backend/ramodels ramodels
    - source .venv/bin/activate

# Jobs
################################################################################


Install ramodels:
  <<: *install-deps
  image: python:3
  stage: build
  script:
    - poetry --version
  rules:
    - <<: *if-default-branch-refs
    - <<: *if-merge-request

Test ramodels:
  <<: *source-venv
  stage: test
  variables:
    HYPOTHESIS_PROFILE: ci
  parallel: 8
  script:
    - pytest
      --cov=ramodels
      --cov-report=html
      --shard-id=$(($CI_NODE_INDEX - 1))
      --num-shards=$CI_NODE_TOTAL
    - mv .coverage ".coverage.$(($CI_NODE_INDEX - 1))"
  artifacts:
    when: always
    paths:
      - "ra-data-models/.coverage.$(($CI_NODE_INDEX - 1))"
  rules:
    - <<: *if-merge-request

Check coverage ramodels:
  stage: coverage
  image: python:3
  needs: [Test ramodels]
  before_script:
    - cd ra-data-models
    - cp -r ../backend/ramodels ramodels
    - pip install coverage
    - coverage combine
  script:
    - coverage report -m --fail-under=100
  rules:
    - <<: *if-merge-request

Release to PyPI:
  <<: *install-deps
  stage: release
  image: python:3
  script:
    - sed -i "s/^version = .*$/version = \"${CI_COMMIT_TAG}\"/g" pyproject.toml
    - poetry publish --build -u __token__ -p $PYPI_TOKEN
  rules:
    - <<: *if-tag-semver

ramodel pages:
  <<: *source-venv
  stage: release
  script:
    - python docs/generate_schemas.py
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - <<: *if-default-branch-refs
