# Global
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .venv
    - .cache/pip
    - .cache/pre-commit

stages:
  - lint

# Job templates
.install-deps-template: &install-deps
  before_script:
    - pip install poetry pre-commit
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv

.lint-template: &lint
  <<: *install-deps
  image: python:3.8
  stage: lint

# Lint jobs
Lint Project:
  <<: *lint
  script: 
      - pre-commit install
      - pre-commit run --all-files
