# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

stages:
  - sync
  - lint
  - build
  - test
  - coverage
  - review
  - qa
  - post-qa
  - prepare-release
  - release
  - deploy
  - docs

default:
  # All jobs are interruptible by default
  interruptible: true

workflow:
  rules: !reference [".workflow:rules", rules]

variables:
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  FRONTEND_IMAGE_SHA: ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_SHA}
  FRONTEND_TEST_IMAGE_SHA: ${CI_REGISTRY_IMAGE}/frontend-test:${CI_COMMIT_SHA}
  TEMPOTEST_IMAGE_SHA: ${CI_REGISTRY_IMAGE}/tempotest:${CI_COMMIT_SHA}
  KEYCLOAK_IMAGE_SHA: ${CI_REGISTRY_IMAGE}/keycloak:${CI_COMMIT_SHA}
  KEYCLOAK_DB_IMAGE_SHA: ${CI_REGISTRY_IMAGE}/keycloak-db:${CI_COMMIT_SHA}
  PYPROJECT_ROOT: "./backend"

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
