# Global
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .venv/
    - .cache/pip
    - .cache/pre-commit

stages:
  - lint
  - test

# Job templates
.install-deps-template: &install-deps
  before_script:
    - pip install poetry pre-commit
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv
    - pre-commit install

.lint-template: &lint
  <<: *install-deps
  image: python:3.8
  stage: lint

.test-template: &test
  # Coverage needed too
  <<: *install-deps
  stage: test
  script: poetry run pytest

# Lint jobs
Lint Project:
  <<: *lint
  script: 
      - pre-commit run --all-files

# Test jobs
Python 3.8:
  <<: *test
  image: python:3.8

Python 3.9:
  <<: *test
  image: python:3.9

