repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0
    hooks:
      - id: pyupgrade
        args: [ "--py310-plus" ]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports
        args: [ "--application-directories=.:backend:tests" ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ "--extend-ignore=B008,W503,E203", "--max-line-length=10001" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [ --config-file=pyproject.toml ]
        additional_dependencies:
          - aiohttp
          - fastapi
          - httpx
          - os2mo-dar-client==1.0.3
          - prometheus_client
          - pydantic
          - fastramqpi==8.3.0
          - sqlalchemy
          - starlette_context
          - strawberry-graphql==0.237.1
          - structlog
          - types-python-dateutil

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        files: backend/mora/graphapi/
        exclude: (backend/mora/graphapi/gmodels/|backend/mora/graphapi/versions/v5/facet.py|backend/mora/graphapi/versions/latest/orgmodel.py)
        args: [ "--convention=google", "--add-ignore=D1" ]
        additional_dependencies:
          - toml

  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.1.2
    hooks:
      - id: reuse

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: "docs/src/graphics/.*"
      - id: trailing-whitespace

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [ push ]
