repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--extend-ignore=B008,W503,E203", "--max-line-length=88"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args: [--config-file=backend/pyproject.toml]
        additional_dependencies:
          - aiohttp
          - fastapi
          - httpx
          - os2mo_dar_client==1.0.1
          - pydantic
          - ramodels==7.0.1
          - starlette_context
          - strawberry-graphql
          - structlog
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
      - id: reorder-python-imports
        args: ["--application-directories=.:backend:tests"]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.17.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - eslint-config-airbnb-base
          - eslint-plugin-import
