repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--extend-ignore=B008,W503,E203", "--max-line-length=101"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args: [--config-file=backend/pyproject.toml]
        exclude: ra-data-models
        additional_dependencies:
          - aiohttp
          - fastapi
          - httpx
          - os2mo_dar_client==1.0.1
          - pydantic
          - ramodels==7.0.1
          - starlette_context
          - strawberry-graphql
          - structlog
          - prometheus_client
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args: [--config-file=ra-data-models/mypy.ini]
        files: ra-data-models
        types: [file, python]
        additional_dependencies:
          - pydantic
          - types-python-dateutil
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
      - id: reorder-python-imports
        args: ["--application-directories=.:backend:tests"]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: tempotest
        files: \.(js|vue|css|html)$
