# SPDX-FileCopyrightText: 2018-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

build:
  image: latest

formats: []

requirements_file: docs/requirements-docs.txt

python:
  version: 3.7
  setup_py_install: false
  python.use_system_site_packages: true
