# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: OS2mo-repository
  annotations:
    github.com/project-slug: OS2mo/os2mo
    github.com/team-slug: OS2mo/developers
    sentry.io/project-slug: magenta/rammearkitektur
    backstage.io/source-location: url:https://git.magenta.dk/rammearkitektur/os2mo
    backstage.io/view-url: https://git.magenta.dk/rammearkitektur/os2mo/-/blob/master/catalog-info.yaml
    backstage.io/edit-url: https://git.magenta.dk/rammearkitektur/os2mo/-/edit/master/catalog-info.yaml
spec:
  type: url
  targets:
    - ./.backstage/os2mo.yaml
    # AMQP Systems
    - ./.backstage/amqp.yaml
    - ./.backstage/old_amqp.yaml
    # WebAPIs
    - ./.backstage/graphql_api.yaml
    - ./.backstage/service_api.yaml
  owner: user:default/emil
