# SPDX-FileCopyrightText: 2022 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

# Usage:
#
#   FIXTURE=aalborg docker-compose -f docker-compose.yml -f docker-compose.fixture.yml [-f docker-compose.override.yml] up -d --build
#
# If FIXTURE is unset, the default, "kolding", will be used. For a list of supported fixtures see:
# https://git.magenta.dk/rammearkitektur/os2mo-fixture-loader.
services:
  mox:
    depends_on:
      fixture-loader:
        condition: service_completed_successfully

  fixture-loader:
    image: magentaaps/os2mo-fixture-loader:0.1.0
    command: ["${FIXTURE:-kolding}"]
    environment:
      PGHOST: mox-db
      PGDATABASE: mox
      PGUSER: postgres
      PGPASSWORD: mysecretpassword
    depends_on:
      mox-db-init:
        condition: service_completed_successfully
