# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
[tool.poetry]
name = "OS2mo"
version = "2.4.0"
authors = ["Magenta ApS <info@magenta.dk>"]
description = "OS2mo - Medarbejder og Organisation"
license = "MPL-2.0"
documentation = "https://os2mo.readthedocs.io"
readme = "README.rst"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/os2mo"
keywords = ["os2mo"]

[tool.poetry.dependencies]
aiofiles = "^0.7.0"
aiohttp = "^3.7.4"
alembic = "^1.6.5"
anytree = "^2.8.0"
authlib = "^0.15.4"
click = "^8.0.1"
fastapi = "^0.65.2"
gunicorn = "^20.1.0"
httpx = "^0.19.0"
Jinja2 = "^3.0.1"
lora-utils = {git = "https://github.com/magenta-aps/lora-utils"}
lxml = "^4.6.3"
more-itertools = "^8.8.0"
os2mo-fastapi-utils = "1.0.0"
os2mo-http-trigger-protocol = "^0.0.4"
pika = "^1.2.0"
prometheus-fastapi-instrumentator = {git = "https://github.com/AndreasPB/prometheus-fastapi-instrumentator"}
psycopg2-binary = "^2.8.6"
pydantic = {extras = ["email"], version = "^1.7.3"}
PyJWT = {extras = ["crypto"], version = "^2.1.0"}
python = "^3.8"
python-dateutil = "^2.8.1"
python-multipart = "^0.0.5"
ra-utils = "0.4.0"
ramodels = "^2.1.1"
requests = "^2.25.1"
service-person-stamdata-udvidet = {git = "https://github.com/magenta-aps/service_person_stamdata_udvidet", rev = "0.2.0"}
SQLAlchemy = "^1.4.17"
SQLAlchemy-Utils = "^0.37.6"
starlette-context = "^0.3.2"
strawberry-graphql = {extras = ["asgi"], version = "^0.77.10"}
structlog = "^21.1.0"
toml = "^0.10.2"
validators = "^0.18.2"
Werkzeug = "^2.0.1"

[tool.poetry.dev-dependencies]
aioresponses = "^0.7.2"
coverage = "^5.5"
flake8 = "^3.9.2"
flake8-bugbear = "^21.4.3"
flake8-module-name = "^0.2.0"
freezegun = "^1.1.0"
hypothesis = "^6.17.4"
notsouid = "^0.0.3"
parameterized = "^0.8.1"
pip-tools = "^6.2.0"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
pytest-cov = "^2.12.1"
pytest-parallel = "^0.1.0"
python-dotenv = "^0.19.0"
requests-mock = "^1.9.3"
termcolor = "^1.1.0"
unittest-xml-reporting = "^3.0.4"
watchdog = "^2.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.autopub]
git-username = "MagentaBot"
git-email = "info@magenta.dk"
