env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/no-unresolved: off  # k6 is actually golang, can't really import it
  import/extensions: off  # .js ending is ok
  no-restricted-globals: off  # required by k6, e.g. "init" context
  no-console: off  # console.log() is preferred in k6
globals:
  __ENV: readonly  # allow using the k6 '__ENV' global variable
