export const MOVE_EMPLOYEE = 'MOVE_EMPLOYEE'
export const SET_EMPLOYEE = 'SET_EMPLOYEE'
export const GET_EMPLOYEE = 'GET_EMPLOYEE'
export const SET_ORG = 'SET_ORG'
export const GET_ORG = 'GET_ORG'
export const SET_VALIDITY = 'SET_VALIDITY'
export const GET_VALIDITY = 'GET_VALIDITY'
