# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Bootstrap the built-in policies

Seed the built-in policies on top of the policy-engine schema: the "Public"
policy grants every actor access to the fields that require no role under the
legacy RBAC map, and the "Introspection" policy grants every actor GraphQL
introspection. The remaining legacy policies are migrated into the database by
later commits, each extending this migration.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a4b5c6d7e8f9"
down_revision: str | Sequence[str] | None = "9f8e7d6c5b4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Well-known UUIDs (the policy name encoded in the tail).
PUBLIC_UUID = "7075626c-9bac-5eed-0000-7075626c6963"
INTROSPECTION_UUID = "696e7472-9bac-5eed-0000-696e74726f73"

policy = sa.table(
    "policy",
    sa.column("id", sa.Uuid),
    sa.column("name", sa.String),
    sa.column("description", sa.String),
    sa.column("activated", sa.Boolean),
)
policy_actor = sa.table(
    "policy_actor",
    sa.column("kind", sa.String),
    sa.column("value", sa.String),
    sa.column("policy_fk", sa.Uuid),
)
policy_rule = sa.table(
    "policy_rule",
    sa.column("type", sa.String),
    sa.column("field", sa.String),
    sa.column("policy_fk", sa.Uuid),
)

# Introspection: allow GraphQL introspection for every actor. `__typename` is a
# meta-field that can appear under any type; the __-prefixed introspection types
# carry the remaining introspection fields.
INTROSPECTION_RULES = [
    ("*", "__typename"),
    ("Query", "__schema"),
    ("Query", "__type"),
    ("__Type", "*"),
    ("__Schema", "*"),
    ("__Field", "*"),
    ("__Directive", "*"),
    ("__EnumValue", "*"),
    ("__InputValue", "*"),
]

# Public: every field that requires no role under the legacy RBAC map (its
# `PUBLIC_FIELDS` entries). Generated from that map; granted to every actor.
PUBLIC_RULES: list[tuple[str, str]] = [
    ("AccessLog", "actor"),
    ("AccessLog", "actor_object"),
    ("AccessLog", "id"),
    ("AccessLog", "model"),
    ("AccessLog", "time"),
    ("AccessLog", "uuids"),
    ("AccessLogPaged", "objects"),
    ("AccessLogPaged", "page_info"),
    ("Address", "address_type_uuid"),
    ("Address", "employee_uuid"),
    ("Address", "engagement_uuid"),
    ("Address", "href"),
    ("Address", "ituser_uuid"),
    ("Address", "name"),
    ("Address", "org_unit_uuid"),
    ("Address", "resolve"),
    ("Address", "type"),
    ("Address", "user_key"),
    ("Address", "uuid"),
    ("Address", "validity"),
    ("Address", "value"),
    ("Address", "value2"),
    ("Address", "visibility_uuid"),
    ("AddressRegistration", "actor"),
    ("AddressRegistration", "actor_object"),
    ("AddressRegistration", "current"),
    ("AddressRegistration", "end"),
    ("AddressRegistration", "model"),
    ("AddressRegistration", "note"),
    ("AddressRegistration", "registration_id"),
    ("AddressRegistration", "start"),
    ("AddressRegistration", "uuid"),
    ("AddressRegistration", "validities"),
    ("AddressResponse", "current"),
    ("AddressResponse", "objects"),
    ("AddressResponse", "registrations"),
    ("AddressResponse", "uuid"),
    ("AddressResponse", "validities"),
    ("AddressResponsePaged", "objects"),
    ("AddressResponsePaged", "page_info"),
    ("AddressResponseRegistration", "actor"),
    ("AddressResponseRegistration", "actor_object"),
    ("AddressResponseRegistration", "current"),
    ("AddressResponseRegistration", "end"),
    ("AddressResponseRegistration", "model"),
    ("AddressResponseRegistration", "note"),
    ("AddressResponseRegistration", "registration_id"),
    ("AddressResponseRegistration", "start"),
    ("AddressResponseRegistration", "uuid"),
    ("AddressResponseRegistration", "validities"),
    ("Association", "association_type_uuid"),
    ("Association", "dynamic_class_uuid"),
    ("Association", "employee_uuid"),
    ("Association", "it_user_uuid"),
    ("Association", "job_function_uuid"),
    ("Association", "org_unit_uuid"),
    ("Association", "primary_uuid"),
    ("Association", "substitute_uuid"),
    ("Association", "trade_union_uuid"),
    ("Association", "type"),
    ("Association", "user_key"),
    ("Association", "uuid"),
    ("Association", "validity"),
    ("AssociationRegistration", "actor"),
    ("AssociationRegistration", "actor_object"),
    ("AssociationRegistration", "current"),
    ("AssociationRegistration", "end"),
    ("AssociationRegistration", "model"),
    ("AssociationRegistration", "note"),
    ("AssociationRegistration", "registration_id"),
    ("AssociationRegistration", "start"),
    ("AssociationRegistration", "uuid"),
    ("AssociationRegistration", "validities"),
    ("AssociationResponse", "current"),
    ("AssociationResponse", "objects"),
    ("AssociationResponse", "registrations"),
    ("AssociationResponse", "uuid"),
    ("AssociationResponse", "validities"),
    ("AssociationResponsePaged", "objects"),
    ("AssociationResponsePaged", "page_info"),
    ("AssociationResponseRegistration", "actor"),
    ("AssociationResponseRegistration", "actor_object"),
    ("AssociationResponseRegistration", "current"),
    ("AssociationResponseRegistration", "end"),
    ("AssociationResponseRegistration", "model"),
    ("AssociationResponseRegistration", "note"),
    ("AssociationResponseRegistration", "registration_id"),
    ("AssociationResponseRegistration", "start"),
    ("AssociationResponseRegistration", "uuid"),
    ("AssociationResponseRegistration", "validities"),
    ("Class", "description"),
    ("Class", "example"),
    ("Class", "facet_uuid"),
    ("Class", "full_name"),
    ("Class", "it_system_uuid"),
    ("Class", "name"),
    ("Class", "org_uuid"),
    ("Class", "owner"),
    ("Class", "parent_uuid"),
    ("Class", "published"),
    ("Class", "scope"),
    ("Class", "type"),
    ("Class", "user_key"),
    ("Class", "uuid"),
    ("Class", "validity"),
    ("ClassRegistration", "actor"),
    ("ClassRegistration", "actor_object"),
    ("ClassRegistration", "current"),
    ("ClassRegistration", "end"),
    ("ClassRegistration", "model"),
    ("ClassRegistration", "note"),
    ("ClassRegistration", "registration_id"),
    ("ClassRegistration", "start"),
    ("ClassRegistration", "uuid"),
    ("ClassRegistration", "validities"),
    ("ClassResponse", "current"),
    ("ClassResponse", "objects"),
    ("ClassResponse", "registrations"),
    ("ClassResponse", "uuid"),
    ("ClassResponse", "validities"),
    ("ClassResponsePaged", "objects"),
    ("ClassResponsePaged", "page_info"),
    ("ClassResponseRegistration", "actor"),
    ("ClassResponseRegistration", "actor_object"),
    ("ClassResponseRegistration", "current"),
    ("ClassResponseRegistration", "end"),
    ("ClassResponseRegistration", "model"),
    ("ClassResponseRegistration", "note"),
    ("ClassResponseRegistration", "registration_id"),
    ("ClassResponseRegistration", "start"),
    ("ClassResponseRegistration", "uuid"),
    ("ClassResponseRegistration", "validities"),
    ("DARAddress", "description"),
    ("DARAddress", "door"),
    ("DARAddress", "floor"),
    ("DARAddress", "house_number"),
    ("DARAddress", "href"),
    ("DARAddress", "latitude"),
    ("DARAddress", "longitude"),
    ("DARAddress", "municipality_code"),
    ("DARAddress", "name"),
    ("DARAddress", "road_code"),
    ("DARAddress", "road_name"),
    ("DARAddress", "streetmap_href"),
    ("DARAddress", "supplementary_city"),
    ("DARAddress", "value"),
    ("DARAddress", "zip_code"),
    ("DARAddress", "zip_code_name"),
    ("DefaultAddress", "value"),
    ("Employee", "cpr_no"),
    ("Employee", "cpr_number"),
    ("Employee", "given_name"),
    ("Employee", "givenname"),
    ("Employee", "name"),
    ("Employee", "nickname"),
    ("Employee", "nickname_given_name"),
    ("Employee", "nickname_givenname"),
    ("Employee", "nickname_surname"),
    ("Employee", "seniority"),
    ("Employee", "surname"),
    ("Employee", "type"),
    ("Employee", "user_key"),
    ("Employee", "uuid"),
    ("Employee", "validity"),
    ("EmployeeResponse", "current"),
    ("EmployeeResponse", "objects"),
    ("EmployeeResponse", "registrations"),
    ("EmployeeResponse", "uuid"),
    ("EmployeeResponse", "validities"),
    ("EmployeeResponsePaged", "objects"),
    ("EmployeeResponsePaged", "page_info"),
    ("EmployeeResponseRegistration", "actor"),
    ("EmployeeResponseRegistration", "actor_object"),
    ("EmployeeResponseRegistration", "current"),
    ("EmployeeResponseRegistration", "end"),
    ("EmployeeResponseRegistration", "model"),
    ("EmployeeResponseRegistration", "note"),
    ("EmployeeResponseRegistration", "registration_id"),
    ("EmployeeResponseRegistration", "start"),
    ("EmployeeResponseRegistration", "uuid"),
    ("EmployeeResponseRegistration", "validities"),
    ("Engagement", "employee_uuid"),
    ("Engagement", "engagement_type_uuid"),
    ("Engagement", "extension_1"),
    ("Engagement", "extension_10"),
    ("Engagement", "extension_2"),
    ("Engagement", "extension_3"),
    ("Engagement", "extension_4"),
    ("Engagement", "extension_5"),
    ("Engagement", "extension_6"),
    ("Engagement", "extension_7"),
    ("Engagement", "extension_8"),
    ("Engagement", "extension_9"),
    ("Engagement", "fraction"),
    ("Engagement", "is_primary"),
    ("Engagement", "job_function_uuid"),
    ("Engagement", "leave_uuid"),
    ("Engagement", "org_unit_uuid"),
    ("Engagement", "primary_uuid"),
    ("Engagement", "type"),
    ("Engagement", "user_key"),
    ("Engagement", "uuid"),
    ("Engagement", "validity"),
    ("EngagementRegistration", "actor"),
    ("EngagementRegistration", "actor_object"),
    ("EngagementRegistration", "current"),
    ("EngagementRegistration", "end"),
    ("EngagementRegistration", "model"),
    ("EngagementRegistration", "note"),
    ("EngagementRegistration", "registration_id"),
    ("EngagementRegistration", "start"),
    ("EngagementRegistration", "uuid"),
    ("EngagementRegistration", "validities"),
    ("EngagementResponse", "current"),
    ("EngagementResponse", "objects"),
    ("EngagementResponse", "registrations"),
    ("EngagementResponse", "uuid"),
    ("EngagementResponse", "validities"),
    ("EngagementResponsePaged", "objects"),
    ("EngagementResponsePaged", "page_info"),
    ("EngagementResponseRegistration", "actor"),
    ("EngagementResponseRegistration", "actor_object"),
    ("EngagementResponseRegistration", "current"),
    ("EngagementResponseRegistration", "end"),
    ("EngagementResponseRegistration", "model"),
    ("EngagementResponseRegistration", "note"),
    ("EngagementResponseRegistration", "registration_id"),
    ("EngagementResponseRegistration", "start"),
    ("EngagementResponseRegistration", "uuid"),
    ("EngagementResponseRegistration", "validities"),
    ("Event", "priority"),
    ("Event", "subject"),
    ("Event", "token"),
    ("Facet", "description"),
    ("Facet", "org_uuid"),
    ("Facet", "parent_uuid"),
    ("Facet", "published"),
    ("Facet", "type"),
    ("Facet", "user_key"),
    ("Facet", "uuid"),
    ("Facet", "validity"),
    ("FacetRegistration", "actor"),
    ("FacetRegistration", "actor_object"),
    ("FacetRegistration", "current"),
    ("FacetRegistration", "end"),
    ("FacetRegistration", "model"),
    ("FacetRegistration", "note"),
    ("FacetRegistration", "registration_id"),
    ("FacetRegistration", "start"),
    ("FacetRegistration", "uuid"),
    ("FacetRegistration", "validities"),
    ("FacetResponse", "current"),
    ("FacetResponse", "objects"),
    ("FacetResponse", "registrations"),
    ("FacetResponse", "uuid"),
    ("FacetResponse", "validities"),
    ("FacetResponsePaged", "objects"),
    ("FacetResponsePaged", "page_info"),
    ("FacetResponseRegistration", "actor"),
    ("FacetResponseRegistration", "actor_object"),
    ("FacetResponseRegistration", "current"),
    ("FacetResponseRegistration", "end"),
    ("FacetResponseRegistration", "model"),
    ("FacetResponseRegistration", "note"),
    ("FacetResponseRegistration", "registration_id"),
    ("FacetResponseRegistration", "start"),
    ("FacetResponseRegistration", "uuid"),
    ("FacetResponseRegistration", "validities"),
    ("File", "base64_contents"),
    ("File", "file_name"),
    ("File", "file_store"),
    ("File", "text_contents"),
    ("FilePaged", "objects"),
    ("FilePaged", "page_info"),
    ("FullEvent", "priority"),
    ("FullEvent", "silenced"),
    ("FullEvent", "subject"),
    ("FullEventPaged", "objects"),
    ("FullEventPaged", "page_info"),
    ("Health", "identifier"),
    ("Health", "status"),
    ("HealthPaged", "objects"),
    ("HealthPaged", "page_info"),
    ("IRegistrationPaged", "objects"),
    ("IRegistrationPaged", "page_info"),
    ("ITSystem", "name"),
    ("ITSystem", "system_type"),
    ("ITSystem", "type"),
    ("ITSystem", "user_key"),
    ("ITSystem", "uuid"),
    ("ITSystem", "validity"),
    ("ITSystemRegistration", "actor"),
    ("ITSystemRegistration", "actor_object"),
    ("ITSystemRegistration", "current"),
    ("ITSystemRegistration", "end"),
    ("ITSystemRegistration", "model"),
    ("ITSystemRegistration", "note"),
    ("ITSystemRegistration", "registration_id"),
    ("ITSystemRegistration", "start"),
    ("ITSystemRegistration", "uuid"),
    ("ITSystemRegistration", "validities"),
    ("ITSystemResponse", "current"),
    ("ITSystemResponse", "objects"),
    ("ITSystemResponse", "registrations"),
    ("ITSystemResponse", "uuid"),
    ("ITSystemResponse", "validities"),
    ("ITSystemResponsePaged", "objects"),
    ("ITSystemResponsePaged", "page_info"),
    ("ITSystemResponseRegistration", "actor"),
    ("ITSystemResponseRegistration", "actor_object"),
    ("ITSystemResponseRegistration", "current"),
    ("ITSystemResponseRegistration", "end"),
    ("ITSystemResponseRegistration", "model"),
    ("ITSystemResponseRegistration", "note"),
    ("ITSystemResponseRegistration", "registration_id"),
    ("ITSystemResponseRegistration", "start"),
    ("ITSystemResponseRegistration", "uuid"),
    ("ITSystemResponseRegistration", "validities"),
    ("ITUser", "binding_type"),
    ("ITUser", "employee_uuid"),
    ("ITUser", "engagement_uuid"),
    ("ITUser", "engagement_uuids"),
    ("ITUser", "external_id"),
    ("ITUser", "itsystem_uuid"),
    ("ITUser", "org_unit_uuid"),
    ("ITUser", "primary_uuid"),
    ("ITUser", "type"),
    ("ITUser", "user_key"),
    ("ITUser", "uuid"),
    ("ITUser", "validity"),
    ("ITUserRegistration", "actor"),
    ("ITUserRegistration", "actor_object"),
    ("ITUserRegistration", "current"),
    ("ITUserRegistration", "end"),
    ("ITUserRegistration", "model"),
    ("ITUserRegistration", "note"),
    ("ITUserRegistration", "registration_id"),
    ("ITUserRegistration", "start"),
    ("ITUserRegistration", "uuid"),
    ("ITUserRegistration", "validities"),
    ("ITUserResponse", "current"),
    ("ITUserResponse", "objects"),
    ("ITUserResponse", "registrations"),
    ("ITUserResponse", "uuid"),
    ("ITUserResponse", "validities"),
    ("ITUserResponsePaged", "objects"),
    ("ITUserResponsePaged", "page_info"),
    ("ITUserResponseRegistration", "actor"),
    ("ITUserResponseRegistration", "actor_object"),
    ("ITUserResponseRegistration", "current"),
    ("ITUserResponseRegistration", "end"),
    ("ITUserResponseRegistration", "model"),
    ("ITUserResponseRegistration", "note"),
    ("ITUserResponseRegistration", "registration_id"),
    ("ITUserResponseRegistration", "start"),
    ("ITUserResponseRegistration", "uuid"),
    ("ITUserResponseRegistration", "validities"),
    ("KLE", "kle_aspect_uuids"),
    ("KLE", "kle_number_uuid"),
    ("KLE", "org_unit_uuid"),
    ("KLE", "type"),
    ("KLE", "user_key"),
    ("KLE", "uuid"),
    ("KLE", "validity"),
    ("KLERegistration", "actor"),
    ("KLERegistration", "actor_object"),
    ("KLERegistration", "current"),
    ("KLERegistration", "end"),
    ("KLERegistration", "model"),
    ("KLERegistration", "note"),
    ("KLERegistration", "registration_id"),
    ("KLERegistration", "start"),
    ("KLERegistration", "uuid"),
    ("KLERegistration", "validities"),
    ("KLEResponse", "current"),
    ("KLEResponse", "objects"),
    ("KLEResponse", "registrations"),
    ("KLEResponse", "uuid"),
    ("KLEResponse", "validities"),
    ("KLEResponsePaged", "objects"),
    ("KLEResponsePaged", "page_info"),
    ("KLEResponseRegistration", "actor"),
    ("KLEResponseRegistration", "actor_object"),
    ("KLEResponseRegistration", "current"),
    ("KLEResponseRegistration", "end"),
    ("KLEResponseRegistration", "model"),
    ("KLEResponseRegistration", "note"),
    ("KLEResponseRegistration", "registration_id"),
    ("KLEResponseRegistration", "start"),
    ("KLEResponseRegistration", "uuid"),
    ("KLEResponseRegistration", "validities"),
    ("Leave", "employee_uuid"),
    ("Leave", "engagement_uuid"),
    ("Leave", "leave_type_uuid"),
    ("Leave", "type"),
    ("Leave", "user_key"),
    ("Leave", "uuid"),
    ("Leave", "validity"),
    ("LeaveRegistration", "actor"),
    ("LeaveRegistration", "actor_object"),
    ("LeaveRegistration", "current"),
    ("LeaveRegistration", "end"),
    ("LeaveRegistration", "model"),
    ("LeaveRegistration", "note"),
    ("LeaveRegistration", "registration_id"),
    ("LeaveRegistration", "start"),
    ("LeaveRegistration", "uuid"),
    ("LeaveRegistration", "validities"),
    ("LeaveResponse", "current"),
    ("LeaveResponse", "objects"),
    ("LeaveResponse", "registrations"),
    ("LeaveResponse", "uuid"),
    ("LeaveResponse", "validities"),
    ("LeaveResponsePaged", "objects"),
    ("LeaveResponsePaged", "page_info"),
    ("LeaveResponseRegistration", "actor"),
    ("LeaveResponseRegistration", "actor_object"),
    ("LeaveResponseRegistration", "current"),
    ("LeaveResponseRegistration", "end"),
    ("LeaveResponseRegistration", "model"),
    ("LeaveResponseRegistration", "note"),
    ("LeaveResponseRegistration", "registration_id"),
    ("LeaveResponseRegistration", "start"),
    ("LeaveResponseRegistration", "uuid"),
    ("LeaveResponseRegistration", "validities"),
    ("Listener", "owner"),
    ("Listener", "routing_key"),
    ("Listener", "user_key"),
    ("Listener", "uuid"),
    ("ListenerPaged", "objects"),
    ("ListenerPaged", "page_info"),
    ("Manager", "employee_uuid"),
    ("Manager", "manager_level_uuid"),
    ("Manager", "manager_type_uuid"),
    ("Manager", "org_unit_uuid"),
    ("Manager", "responsibility_uuids"),
    ("Manager", "type"),
    ("Manager", "user_key"),
    ("Manager", "uuid"),
    ("Manager", "validity"),
    ("ManagerRegistration", "actor"),
    ("ManagerRegistration", "actor_object"),
    ("ManagerRegistration", "current"),
    ("ManagerRegistration", "end"),
    ("ManagerRegistration", "model"),
    ("ManagerRegistration", "note"),
    ("ManagerRegistration", "registration_id"),
    ("ManagerRegistration", "start"),
    ("ManagerRegistration", "uuid"),
    ("ManagerRegistration", "validities"),
    ("ManagerResponse", "current"),
    ("ManagerResponse", "objects"),
    ("ManagerResponse", "registrations"),
    ("ManagerResponse", "uuid"),
    ("ManagerResponse", "validities"),
    ("ManagerResponsePaged", "objects"),
    ("ManagerResponsePaged", "page_info"),
    ("ManagerResponseRegistration", "actor"),
    ("ManagerResponseRegistration", "actor_object"),
    ("ManagerResponseRegistration", "current"),
    ("ManagerResponseRegistration", "end"),
    ("ManagerResponseRegistration", "model"),
    ("ManagerResponseRegistration", "note"),
    ("ManagerResponseRegistration", "registration_id"),
    ("ManagerResponseRegistration", "start"),
    ("ManagerResponseRegistration", "uuid"),
    ("ManagerResponseRegistration", "validities"),
    ("MultifieldAddress", "name"),
    ("MultifieldAddress", "value"),
    ("MultifieldAddress", "value2"),
    ("Myself", "actor"),
    ("Myself", "email"),
    ("Myself", "roles"),
    ("Myself", "username"),
    ("Namespace", "name"),
    ("Namespace", "owner"),
    ("Namespace", "public"),
    ("NamespacePaged", "objects"),
    ("NamespacePaged", "page_info"),
    ("OpenValidity", "from"),
    ("OpenValidity", "to"),
    ("Organisation", "municipality_code"),
    ("Organisation", "name"),
    ("Organisation", "type"),
    ("Organisation", "user_key"),
    ("Organisation", "uuid"),
    ("OrganisationUnit", "name"),
    ("OrganisationUnit", "org_unit_hierarchy"),
    ("OrganisationUnit", "org_unit_level_uuid"),
    ("OrganisationUnit", "parent_uuid"),
    ("OrganisationUnit", "time_planning_uuid"),
    ("OrganisationUnit", "type"),
    ("OrganisationUnit", "unit_type_uuid"),
    ("OrganisationUnit", "user_key"),
    ("OrganisationUnit", "uuid"),
    ("OrganisationUnit", "validity"),
    ("OrganisationUnitRegistration", "actor"),
    ("OrganisationUnitRegistration", "actor_object"),
    ("OrganisationUnitRegistration", "current"),
    ("OrganisationUnitRegistration", "end"),
    ("OrganisationUnitRegistration", "model"),
    ("OrganisationUnitRegistration", "note"),
    ("OrganisationUnitRegistration", "registration_id"),
    ("OrganisationUnitRegistration", "start"),
    ("OrganisationUnitRegistration", "uuid"),
    ("OrganisationUnitRegistration", "validities"),
    ("OrganisationUnitResponse", "current"),
    ("OrganisationUnitResponse", "objects"),
    ("OrganisationUnitResponse", "registrations"),
    ("OrganisationUnitResponse", "uuid"),
    ("OrganisationUnitResponse", "validities"),
    ("OrganisationUnitResponsePaged", "objects"),
    ("OrganisationUnitResponsePaged", "page_info"),
    ("OrganisationUnitResponseRegistration", "actor"),
    ("OrganisationUnitResponseRegistration", "actor_object"),
    ("OrganisationUnitResponseRegistration", "current"),
    ("OrganisationUnitResponseRegistration", "end"),
    ("OrganisationUnitResponseRegistration", "model"),
    ("OrganisationUnitResponseRegistration", "note"),
    ("OrganisationUnitResponseRegistration", "registration_id"),
    ("OrganisationUnitResponseRegistration", "start"),
    ("OrganisationUnitResponseRegistration", "uuid"),
    ("OrganisationUnitResponseRegistration", "validities"),
    ("Owner", "employee_uuid"),
    ("Owner", "org_unit_uuid"),
    ("Owner", "owner_inference_priority"),
    ("Owner", "owner_uuid"),
    ("Owner", "type"),
    ("Owner", "user_key"),
    ("Owner", "uuid"),
    ("Owner", "validity"),
    ("OwnerRegistration", "actor"),
    ("OwnerRegistration", "actor_object"),
    ("OwnerRegistration", "current"),
    ("OwnerRegistration", "end"),
    ("OwnerRegistration", "model"),
    ("OwnerRegistration", "note"),
    ("OwnerRegistration", "registration_id"),
    ("OwnerRegistration", "start"),
    ("OwnerRegistration", "uuid"),
    ("OwnerRegistration", "validities"),
    ("OwnerResponse", "current"),
    ("OwnerResponse", "objects"),
    ("OwnerResponse", "registrations"),
    ("OwnerResponse", "uuid"),
    ("OwnerResponse", "validities"),
    ("OwnerResponsePaged", "objects"),
    ("OwnerResponsePaged", "page_info"),
    ("OwnerResponseRegistration", "actor"),
    ("OwnerResponseRegistration", "actor_object"),
    ("OwnerResponseRegistration", "current"),
    ("OwnerResponseRegistration", "end"),
    ("OwnerResponseRegistration", "model"),
    ("OwnerResponseRegistration", "note"),
    ("OwnerResponseRegistration", "registration_id"),
    ("OwnerResponseRegistration", "start"),
    ("OwnerResponseRegistration", "uuid"),
    ("OwnerResponseRegistration", "validities"),
    ("PageInfo", "next_cursor"),
    ("PersonRegistration", "actor"),
    ("PersonRegistration", "actor_object"),
    ("PersonRegistration", "current"),
    ("PersonRegistration", "end"),
    ("PersonRegistration", "model"),
    ("PersonRegistration", "note"),
    ("PersonRegistration", "registration_id"),
    ("PersonRegistration", "start"),
    ("PersonRegistration", "uuid"),
    ("PersonRegistration", "validities"),
    ("Query", "healths"),
    ("Query", "me"),
    ("Query", "version"),
    ("Registration", "actor"),
    ("Registration", "actor_object"),
    ("Registration", "end"),
    ("Registration", "model"),
    ("Registration", "note"),
    ("Registration", "registration_id"),
    ("Registration", "start"),
    ("Registration", "uuid"),
    ("RegistrationPaged", "objects"),
    ("RegistrationPaged", "page_info"),
    ("RelatedUnit", "org_unit_uuids"),
    ("RelatedUnit", "type"),
    ("RelatedUnit", "user_key"),
    ("RelatedUnit", "uuid"),
    ("RelatedUnit", "validity"),
    ("RelatedUnitRegistration", "actor"),
    ("RelatedUnitRegistration", "actor_object"),
    ("RelatedUnitRegistration", "current"),
    ("RelatedUnitRegistration", "end"),
    ("RelatedUnitRegistration", "model"),
    ("RelatedUnitRegistration", "note"),
    ("RelatedUnitRegistration", "registration_id"),
    ("RelatedUnitRegistration", "start"),
    ("RelatedUnitRegistration", "uuid"),
    ("RelatedUnitRegistration", "validities"),
    ("RelatedUnitResponse", "current"),
    ("RelatedUnitResponse", "objects"),
    ("RelatedUnitResponse", "registrations"),
    ("RelatedUnitResponse", "uuid"),
    ("RelatedUnitResponse", "validities"),
    ("RelatedUnitResponsePaged", "objects"),
    ("RelatedUnitResponsePaged", "page_info"),
    ("RelatedUnitResponseRegistration", "actor"),
    ("RelatedUnitResponseRegistration", "actor_object"),
    ("RelatedUnitResponseRegistration", "current"),
    ("RelatedUnitResponseRegistration", "end"),
    ("RelatedUnitResponseRegistration", "model"),
    ("RelatedUnitResponseRegistration", "note"),
    ("RelatedUnitResponseRegistration", "registration_id"),
    ("RelatedUnitResponseRegistration", "start"),
    ("RelatedUnitResponseRegistration", "uuid"),
    ("RelatedUnitResponseRegistration", "validities"),
    ("RoleBinding", "user_key"),
    ("RoleBinding", "uuid"),
    ("RoleBinding", "validity"),
    ("RoleBindingRegistration", "actor"),
    ("RoleBindingRegistration", "actor_object"),
    ("RoleBindingRegistration", "current"),
    ("RoleBindingRegistration", "end"),
    ("RoleBindingRegistration", "model"),
    ("RoleBindingRegistration", "note"),
    ("RoleBindingRegistration", "registration_id"),
    ("RoleBindingRegistration", "start"),
    ("RoleBindingRegistration", "uuid"),
    ("RoleBindingRegistration", "validities"),
    ("RoleBindingResponse", "current"),
    ("RoleBindingResponse", "objects"),
    ("RoleBindingResponse", "registrations"),
    ("RoleBindingResponse", "uuid"),
    ("RoleBindingResponse", "validities"),
    ("RoleBindingResponsePaged", "objects"),
    ("RoleBindingResponsePaged", "page_info"),
    ("RoleBindingResponseRegistration", "actor"),
    ("RoleBindingResponseRegistration", "actor_object"),
    ("RoleBindingResponseRegistration", "current"),
    ("RoleBindingResponseRegistration", "end"),
    ("RoleBindingResponseRegistration", "model"),
    ("RoleBindingResponseRegistration", "note"),
    ("RoleBindingResponseRegistration", "registration_id"),
    ("RoleBindingResponseRegistration", "start"),
    ("RoleBindingResponseRegistration", "uuid"),
    ("RoleBindingResponseRegistration", "validities"),
    ("SpecialActor", "display_name"),
    ("SpecialActor", "key"),
    ("SpecialActor", "uuid"),
    ("UUIDPaged", "objects"),
    ("UUIDPaged", "page_info"),
    ("UnknownActor", "display_name"),
    ("UnknownActor", "error"),
    ("UnknownActor", "uuid"),
    ("Validity", "from"),
    ("Validity", "to"),
    ("Version", "lora_version"),
    ("Version", "mo_hash"),
    ("Version", "mo_version"),
]


def upgrade() -> None:
    op.bulk_insert(
        policy,
        [
            {
                "id": PUBLIC_UUID,
                "name": "Public",
                "description": "Grants access to fields that require no role (public fields).",
                "activated": True,
            },
            {
                "id": INTROSPECTION_UUID,
                "name": "Introspection",
                "description": "Grants GraphQL introspection access to every actor.",
                "activated": True,
            },
        ],
    )
    op.bulk_insert(
        policy_actor,
        [
            {"kind": "all", "value": "", "policy_fk": PUBLIC_UUID},
            {"kind": "all", "value": "", "policy_fk": INTROSPECTION_UUID},
        ],
    )
    op.bulk_insert(
        policy_rule,
        [
            *[
                {"type": t, "field": f, "policy_fk": PUBLIC_UUID}
                for t, f in PUBLIC_RULES
            ],
            *[
                {"type": t, "field": f, "policy_fk": INTROSPECTION_UUID}
                for t, f in INTROSPECTION_RULES
            ],
        ],
    )


def downgrade() -> None:
    ids = f"'{PUBLIC_UUID}', '{INTROSPECTION_UUID}'"
    op.execute(f"DELETE FROM policy_rule WHERE policy_fk IN ({ids})")
    op.execute(f"DELETE FROM policy_actor WHERE policy_fk IN ({ids})")
    op.execute(f"DELETE FROM policy WHERE id IN ({ids})")
