# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Bootstrap the built-in policies

Seed the built-in policies on top of the policy-engine schema: the "Public"
policy grants every actor access to the fields that require no role under the
legacy RBAC map, the "Introspection" policy grants every actor GraphQL
introspection, the "Legacy" policy reproduces role-based RBAC (one explicit
rule per permission-gated field, gated on the required role via a CEL
condition) and the "Administrator"/"Reader" convenience policies grant
role-bound blanket access. The remaining legacy behaviour is migrated into the
database by later commits, each extending this migration.
"""

import json
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a4b5c6d7e8f9"
down_revision: str | Sequence[str] | None = "9f8e7d6c5b4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Well-known UUIDs (the policy name encoded in the tail).
POLICYADMIN_UUID = "ded1ca7e-9bac-5eed-706f-6c61646d696e"
PUBLIC_UUID = "7075626c-9bac-5eed-0000-7075626c6963"
INTROSPECTION_UUID = "696e7472-9bac-5eed-0000-696e74726f73"
LEGACY_UUID = "0b50137e-9bac-5eed-0000-6c6567616379"
OWNER_UUID = "6f776e65-9bac-5eed-0000-006f776e6572"
ADMINISTRATOR_UUID = "e5ca1a7e-9bac-5eed-0000-0061646d696e"
READER_UUID = "acce5500-9bac-5eed-0000-726561646572"

policy = sa.table(
    "policy",
    sa.column("id", sa.Uuid),
    sa.column("name", sa.String),
    sa.column("description", sa.String),
    sa.column("activated", sa.Boolean),
)
policy_actor = sa.table(
    "policy_actor",
    sa.column("kind", sa.String),
    sa.column("value", sa.String),
    sa.column("policy_fk", sa.Uuid),
)
policy_rule = sa.table(
    "policy_rule",
    sa.column("type", sa.String),
    sa.column("field", sa.String),
    sa.column("condition", sa.String),
    sa.column("filter", sa.String),
    sa.column("policy_fk", sa.Uuid),
)

# Policy Administrator: the (type, field) resources it grants.
POLICYADMIN_RULES = [
    ("Query", "policies"),
    ("Mutation", "policy_declare"),
    ("Mutation", "policy_delete"),
    ("Mutation", "policy_actor_declare"),
    ("Mutation", "policy_actors_declare"),
    ("Mutation", "policy_actor_delete"),
    ("Mutation", "policy_rule_declare"),
    ("Mutation", "policy_rules_declare"),
    ("Mutation", "policy_rule_delete"),
]

# Legacy: one rule per permission-gated (type, field), gated on the field's
# required RBAC role via `"<role>" in token.roles`. Generated from `RBAC_MAP`.
LEGACY_RULES: list[tuple[str, str, str]] = [
    ("Address", "address_type", '"read_class" in token.roles'),
    ("Address", "address_type_response", '"read_class" in token.roles'),
    ("Address", "employee", '"read_employee" in token.roles'),
    ("Address", "engagement", '"read_engagement" in token.roles'),
    ("Address", "engagement_response", '"read_engagement" in token.roles'),
    ("Address", "ituser", '"read_ituser" in token.roles'),
    ("Address", "ituser_response", '"read_ituser" in token.roles'),
    ("Address", "org_unit", '"read_org_unit" in token.roles'),
    ("Address", "org_unit_response", '"read_org_unit" in token.roles'),
    ("Address", "person", '"read_employee" in token.roles'),
    ("Address", "person_response", '"read_employee" in token.roles'),
    ("Address", "visibility", '"read_class" in token.roles'),
    ("Address", "visibility_response", '"read_class" in token.roles'),
    ("Association", "association_type", '"read_class" in token.roles'),
    ("Association", "association_type_response", '"read_class" in token.roles'),
    ("Association", "dynamic_class", '"read_class" in token.roles'),
    ("Association", "dynamic_class_response", '"read_class" in token.roles'),
    ("Association", "employee", '"read_employee" in token.roles'),
    ("Association", "it_user", '"read_ituser" in token.roles'),
    ("Association", "it_user_response", '"read_ituser" in token.roles'),
    ("Association", "job_function", '"read_class" in token.roles'),
    ("Association", "job_function_response", '"read_class" in token.roles'),
    ("Association", "org_unit", '"read_org_unit" in token.roles'),
    ("Association", "org_unit_response", '"read_org_unit" in token.roles'),
    ("Association", "person", '"read_employee" in token.roles'),
    ("Association", "person_response", '"read_employee" in token.roles'),
    ("Association", "primary", '"read_class" in token.roles'),
    ("Association", "primary_response", '"read_class" in token.roles'),
    ("Association", "substitute", '"read_employee" in token.roles'),
    ("Association", "substitute_response", '"read_employee" in token.roles'),
    ("Association", "trade_union", '"read_class" in token.roles'),
    ("Association", "trade_union_response", '"read_class" in token.roles'),
    ("Class", "children", '"read_class" in token.roles'),
    ("Class", "children_response", '"read_class" in token.roles'),
    ("Class", "facet", '"read_facet" in token.roles'),
    ("Class", "facet_response", '"read_facet" in token.roles'),
    ("Class", "it_system", '"read_itsystem" in token.roles'),
    ("Class", "it_system_response", '"read_itsystem" in token.roles'),
    ("Class", "parent", '"read_class" in token.roles'),
    ("Class", "parent_response", '"read_class" in token.roles'),
    ("Class", "top_level_facet", '"read_facet" in token.roles'),
    ("Employee", "addresses", '"read_address" in token.roles'),
    ("Employee", "addresses_response", '"read_address" in token.roles'),
    ("Employee", "associations", '"read_association" in token.roles'),
    ("Employee", "associations_response", '"read_association" in token.roles'),
    ("Employee", "engagements", '"read_engagement" in token.roles'),
    ("Employee", "engagements_response", '"read_engagement" in token.roles'),
    ("Employee", "itusers", '"read_ituser" in token.roles'),
    ("Employee", "itusers_response", '"read_ituser" in token.roles'),
    ("Employee", "leaves", '"read_leave" in token.roles'),
    ("Employee", "leaves_response", '"read_leave" in token.roles'),
    ("Employee", "manager_roles", '"read_manager" in token.roles'),
    ("Employee", "manager_roles_response", '"read_manager" in token.roles'),
    ("Engagement", "addresses_response", '"read_address" in token.roles'),
    ("Engagement", "employee", '"read_employee" in token.roles'),
    ("Engagement", "engagement_type", '"read_class" in token.roles'),
    ("Engagement", "engagement_type_response", '"read_class" in token.roles'),
    ("Engagement", "itusers", '"read_ituser" in token.roles'),
    ("Engagement", "itusers_response", '"read_ituser" in token.roles'),
    ("Engagement", "job_function", '"read_class" in token.roles'),
    ("Engagement", "job_function_response", '"read_class" in token.roles'),
    ("Engagement", "leave", '"read_leave" in token.roles'),
    ("Engagement", "leave_response", '"read_leave" in token.roles'),
    ("Engagement", "managers", '"read_manager" in token.roles'),
    ("Engagement", "org_unit", '"read_org_unit" in token.roles'),
    ("Engagement", "org_unit_response", '"read_org_unit" in token.roles'),
    ("Engagement", "person", '"read_employee" in token.roles'),
    ("Engagement", "person_response", '"read_employee" in token.roles'),
    ("Engagement", "primary", '"read_class" in token.roles'),
    ("Engagement", "primary_response", '"read_class" in token.roles'),
    ("Facet", "children", '"read_facet" in token.roles'),
    ("Facet", "children_response", '"read_facet" in token.roles'),
    ("Facet", "classes", '"read_class" in token.roles'),
    ("Facet", "classes_responses", '"read_class" in token.roles'),
    ("Facet", "parent", '"read_facet" in token.roles'),
    ("Facet", "parent_response", '"read_facet" in token.roles'),
    ("FullEvent", "listener", '"read_event_listener" in token.roles'),
    ("ITSystem", "roles", '"read_class" in token.roles'),
    ("ITSystem", "roles_response", '"read_class" in token.roles'),
    ("ITUser", "addresses", '"read_address" in token.roles'),
    ("ITUser", "addresses_response", '"read_address" in token.roles'),
    ("ITUser", "employee", '"read_employee" in token.roles'),
    ("ITUser", "engagement", '"read_engagement" in token.roles'),
    ("ITUser", "engagement_response", '"read_engagement" in token.roles'),
    ("ITUser", "engagements", '"read_engagement" in token.roles'),
    ("ITUser", "engagements_responses", '"read_engagement" in token.roles'),
    ("ITUser", "itsystem", '"read_itsystem" in token.roles'),
    ("ITUser", "itsystem_response", '"read_itsystem" in token.roles'),
    ("ITUser", "org_unit", '"read_org_unit" in token.roles'),
    ("ITUser", "org_unit_response", '"read_org_unit" in token.roles'),
    ("ITUser", "person", '"read_employee" in token.roles'),
    ("ITUser", "person_response", '"read_employee" in token.roles'),
    ("ITUser", "primary", '"read_class" in token.roles'),
    ("ITUser", "primary_response", '"read_class" in token.roles'),
    ("ITUser", "rolebindings", '"read_rolebinding" in token.roles'),
    ("ITUser", "rolebindings_response", '"read_rolebinding" in token.roles'),
    ("KLE", "kle_aspects", '"read_class" in token.roles'),
    ("KLE", "kle_aspects_response", '"read_class" in token.roles'),
    ("KLE", "kle_number", '"read_class" in token.roles'),
    ("KLE", "kle_number_response", '"read_class" in token.roles'),
    ("KLE", "org_unit", '"read_org_unit" in token.roles'),
    ("KLE", "org_unit_response", '"read_org_unit" in token.roles'),
    ("Leave", "employee", '"read_employee" in token.roles'),
    ("Leave", "engagement", '"read_engagement" in token.roles'),
    ("Leave", "engagement_response", '"read_engagement" in token.roles'),
    ("Leave", "leave_type", '"read_class" in token.roles'),
    ("Leave", "leave_type_response", '"read_class" in token.roles'),
    ("Leave", "person", '"read_employee" in token.roles'),
    ("Leave", "person_response", '"read_employee" in token.roles'),
    ("Listener", "events", '"read_event" in token.roles'),
    ("Listener", "namespace", '"read_event_namespace" in token.roles'),
    ("Manager", "employee", '"read_employee" in token.roles'),
    ("Manager", "engagement_response", '"read_engagement" in token.roles'),
    ("Manager", "manager_level", '"read_class" in token.roles'),
    ("Manager", "manager_level_response", '"read_class" in token.roles'),
    ("Manager", "manager_type", '"read_class" in token.roles'),
    ("Manager", "manager_type_response", '"read_class" in token.roles'),
    ("Manager", "org_unit", '"read_org_unit" in token.roles'),
    ("Manager", "org_unit_response", '"read_org_unit" in token.roles'),
    ("Manager", "person", '"read_employee" in token.roles'),
    ("Manager", "person_response", '"read_employee" in token.roles'),
    ("Manager", "responsibilities", '"read_class" in token.roles'),
    ("Manager", "responsibilities_response", '"read_class" in token.roles'),
    ("Mutation", "address_create", '"create_address" in token.roles'),
    ("Mutation", "address_delete", '"delete_address" in token.roles'),
    ("Mutation", "address_refresh", '"refresh_address" in token.roles'),
    ("Mutation", "address_terminate", '"terminate_address" in token.roles'),
    ("Mutation", "address_update", '"update_address" in token.roles'),
    ("Mutation", "addresses_create", '"create_address" in token.roles'),
    ("Mutation", "association_create", '"create_association" in token.roles'),
    ("Mutation", "association_refresh", '"refresh_association" in token.roles'),
    ("Mutation", "association_terminate", '"terminate_association" in token.roles'),
    ("Mutation", "association_update", '"update_association" in token.roles'),
    ("Mutation", "class_create", '"create_class" in token.roles'),
    ("Mutation", "class_delete", '"delete_class" in token.roles'),
    ("Mutation", "class_refresh", '"refresh_class" in token.roles'),
    ("Mutation", "class_terminate", '"terminate_class" in token.roles'),
    ("Mutation", "class_update", '"update_class" in token.roles'),
    ("Mutation", "employee_create", '"create_employee" in token.roles'),
    ("Mutation", "employee_delete", '"delete_employee" in token.roles'),
    ("Mutation", "employee_refresh", '"refresh_employee" in token.roles'),
    ("Mutation", "employee_terminate", '"terminate_employee" in token.roles'),
    ("Mutation", "employee_update", '"update_employee" in token.roles'),
    ("Mutation", "engagement_create", '"create_engagement" in token.roles'),
    ("Mutation", "engagement_delete", '"delete_engagement" in token.roles'),
    ("Mutation", "engagement_refresh", '"refresh_engagement" in token.roles'),
    ("Mutation", "engagement_terminate", '"terminate_engagement" in token.roles'),
    ("Mutation", "engagement_update", '"update_engagement" in token.roles'),
    ("Mutation", "engagements_create", '"create_engagement" in token.roles'),
    ("Mutation", "engagements_update", '"update_engagement" in token.roles'),
    ("Mutation", "event_acknowledge", '"acknowledge_event" in token.roles'),
    ("Mutation", "event_listener_declare", '"create_event_listener" in token.roles'),
    ("Mutation", "event_listener_delete", '"delete_event_listener" in token.roles'),
    ("Mutation", "event_namespace_declare", '"create_event_namespace" in token.roles'),
    ("Mutation", "event_namespace_delete", '"delete_event_namespace" in token.roles'),
    ("Mutation", "event_rerun", '"rerun_event" in token.roles'),
    ("Mutation", "event_send", '"send_event" in token.roles'),
    ("Mutation", "event_silence", '"silence_event" in token.roles'),
    ("Mutation", "event_unsilence", '"unsilence_event" in token.roles'),
    ("Mutation", "facet_create", '"create_facet" in token.roles'),
    ("Mutation", "facet_delete", '"delete_facet" in token.roles'),
    ("Mutation", "facet_refresh", '"refresh_facet" in token.roles'),
    ("Mutation", "facet_terminate", '"terminate_facet" in token.roles'),
    ("Mutation", "facet_update", '"update_facet" in token.roles'),
    ("Mutation", "itassociation_create", '"create_association" in token.roles'),
    ("Mutation", "itassociation_terminate", '"terminate_association" in token.roles'),
    ("Mutation", "itassociation_update", '"update_association" in token.roles'),
    ("Mutation", "itsystem_create", '"create_itsystem" in token.roles'),
    ("Mutation", "itsystem_delete", '"delete_itsystem" in token.roles'),
    ("Mutation", "itsystem_refresh", '"refresh_itsystem" in token.roles'),
    ("Mutation", "itsystem_terminate", '"terminate_itsystem" in token.roles'),
    ("Mutation", "itsystem_update", '"update_itsystem" in token.roles'),
    ("Mutation", "ituser_create", '"create_ituser" in token.roles'),
    ("Mutation", "ituser_delete", '"delete_ituser" in token.roles'),
    ("Mutation", "ituser_refresh", '"refresh_ituser" in token.roles'),
    ("Mutation", "ituser_terminate", '"terminate_ituser" in token.roles'),
    ("Mutation", "ituser_update", '"update_ituser" in token.roles'),
    ("Mutation", "itusers_create", '"create_ituser" in token.roles'),
    ("Mutation", "kle_create", '"create_kle" in token.roles'),
    ("Mutation", "kle_refresh", '"refresh_kle" in token.roles'),
    ("Mutation", "kle_terminate", '"terminate_kle" in token.roles'),
    ("Mutation", "kle_update", '"update_kle" in token.roles'),
    ("Mutation", "leave_create", '"create_leave" in token.roles'),
    ("Mutation", "leave_refresh", '"refresh_leave" in token.roles'),
    ("Mutation", "leave_terminate", '"terminate_leave" in token.roles'),
    ("Mutation", "leave_update", '"update_leave" in token.roles'),
    ("Mutation", "manager_create", '"create_manager" in token.roles'),
    ("Mutation", "manager_delete", '"delete_manager" in token.roles'),
    ("Mutation", "manager_refresh", '"refresh_manager" in token.roles'),
    ("Mutation", "manager_terminate", '"terminate_manager" in token.roles'),
    ("Mutation", "manager_update", '"update_manager" in token.roles'),
    ("Mutation", "managers_create", '"create_manager" in token.roles'),
    ("Mutation", "org_create", '"create_org" in token.roles'),
    ("Mutation", "org_unit_create", '"create_org_unit" in token.roles'),
    ("Mutation", "org_unit_delete", '"delete_org_unit" in token.roles'),
    ("Mutation", "org_unit_refresh", '"refresh_org_unit" in token.roles'),
    ("Mutation", "org_unit_terminate", '"terminate_org_unit" in token.roles'),
    ("Mutation", "org_unit_update", '"update_org_unit" in token.roles'),
    ("Mutation", "policy_actor_declare", '"create_policy" in token.roles'),
    ("Mutation", "policy_actor_delete", '"delete_policy" in token.roles'),
    ("Mutation", "policy_actors_declare", '"create_policy" in token.roles'),
    ("Mutation", "policy_declare", '"create_policy" in token.roles'),
    ("Mutation", "policy_delete", '"delete_policy" in token.roles'),
    ("Mutation", "policy_rule_declare", '"create_policy" in token.roles'),
    ("Mutation", "policy_rule_delete", '"delete_policy" in token.roles'),
    ("Mutation", "policy_rules_declare", '"create_policy" in token.roles'),
    ("Mutation", "owner_create", '"create_owner" in token.roles'),
    ("Mutation", "owner_refresh", '"refresh_owner" in token.roles'),
    ("Mutation", "owner_terminate", '"terminate_owner" in token.roles'),
    ("Mutation", "owner_update", '"update_owner" in token.roles'),
    ("Mutation", "related_unit_refresh", '"refresh_related_unit" in token.roles'),
    ("Mutation", "related_units_update", '"update_related_unit" in token.roles'),
    ("Mutation", "rolebinding_create", '"create_rolebinding" in token.roles'),
    ("Mutation", "rolebinding_delete", '"delete_rolebinding" in token.roles'),
    ("Mutation", "rolebinding_refresh", '"refresh_rolebinding" in token.roles'),
    ("Mutation", "rolebinding_terminate", '"terminate_rolebinding" in token.roles'),
    ("Mutation", "rolebinding_update", '"update_rolebinding" in token.roles'),
    ("Mutation", "rolebindings_create", '"create_rolebinding" in token.roles'),
    ("Mutation", "upload_file", '"upload_files" in token.roles'),
    ("Namespace", "listeners", '"read_event_namespace" in token.roles'),
    ("OrganisationUnit", "addresses", '"read_address" in token.roles'),
    ("OrganisationUnit", "addresses_response", '"read_address" in token.roles'),
    ("OrganisationUnit", "ancestors", '"read_org_unit" in token.roles'),
    ("OrganisationUnit", "associations", '"read_association" in token.roles'),
    ("OrganisationUnit", "associations_response", '"read_association" in token.roles'),
    ("OrganisationUnit", "child_count", '"read_org_unit" in token.roles'),
    ("OrganisationUnit", "children", '"read_org_unit" in token.roles'),
    ("OrganisationUnit", "children_response", '"read_org_unit" in token.roles'),
    ("OrganisationUnit", "engagements", '"read_engagement" in token.roles'),
    ("OrganisationUnit", "engagements_response", '"read_engagement" in token.roles'),
    ("OrganisationUnit", "has_children", '"read_org_unit" in token.roles'),
    ("OrganisationUnit", "itusers", '"read_ituser" in token.roles'),
    ("OrganisationUnit", "itusers_response", '"read_ituser" in token.roles'),
    ("OrganisationUnit", "kles", '"read_kle" in token.roles'),
    ("OrganisationUnit", "kles_response", '"read_kle" in token.roles'),
    ("OrganisationUnit", "leaves", '"read_leave" in token.roles'),
    ("OrganisationUnit", "leaves_response", '"read_leave" in token.roles'),
    ("OrganisationUnit", "managers", '"read_manager" in token.roles'),
    ("OrganisationUnit", "managers_response", '"read_manager" in token.roles'),
    ("OrganisationUnit", "org_unit_hierarchy_model", '"read_class" in token.roles'),
    ("OrganisationUnit", "org_unit_level", '"read_class" in token.roles'),
    ("OrganisationUnit", "owners", '"read_owner" in token.roles'),
    ("OrganisationUnit", "parent", '"read_org_unit" in token.roles'),
    ("OrganisationUnit", "parent_response", '"read_org_unit" in token.roles'),
    ("OrganisationUnit", "related_units", '"read_related_unit" in token.roles'),
    (
        "OrganisationUnit",
        "related_units_response",
        '"read_related_unit" in token.roles',
    ),
    ("OrganisationUnit", "root", '"read_org_unit" in token.roles'),
    ("OrganisationUnit", "root_response", '"read_org_unit" in token.roles'),
    ("OrganisationUnit", "time_planning", '"read_class" in token.roles'),
    ("OrganisationUnit", "time_planning_response", '"read_class" in token.roles'),
    ("OrganisationUnit", "unit_hierarchy_response", '"read_class" in token.roles'),
    ("OrganisationUnit", "unit_level_response", '"read_class" in token.roles'),
    ("OrganisationUnit", "unit_type", '"read_class" in token.roles'),
    ("OrganisationUnit", "unit_type_response", '"read_class" in token.roles'),
    ("Owner", "org_unit", '"read_org_unit" in token.roles'),
    ("Owner", "org_unit_response", '"read_org_unit" in token.roles'),
    ("Owner", "owner", '"read_owner" in token.roles'),
    ("Owner", "owner_response", '"read_owner" in token.roles'),
    ("Owner", "person", '"read_employee" in token.roles'),
    ("Owner", "person_response", '"read_employee" in token.roles'),
    ("Query", "access_log", '"read_accesslog" in token.roles'),
    ("Query", "addresses", '"read_address" in token.roles'),
    ("Query", "associations", '"read_association" in token.roles'),
    ("Query", "classes", '"read_class" in token.roles'),
    ("Query", "employees", '"read_employee" in token.roles'),
    ("Query", "engagements", '"read_engagement" in token.roles'),
    ("Query", "event_fetch", '"fetch_event" in token.roles'),
    ("Query", "event_listeners", '"read_event_listener" in token.roles'),
    ("Query", "event_namespaces", '"read_event_namespace" in token.roles'),
    ("Query", "events", '"read_event" in token.roles'),
    ("Query", "facets", '"read_facet" in token.roles'),
    ("Query", "files", '"read_file" in token.roles'),
    ("Query", "itsystems", '"read_itsystem" in token.roles'),
    ("Query", "itusers", '"read_ituser" in token.roles'),
    ("Query", "kles", '"read_kle" in token.roles'),
    ("Query", "leaves", '"read_leave" in token.roles'),
    ("Query", "managers", '"read_manager" in token.roles'),
    ("Query", "org", '"read_org" in token.roles'),
    ("Query", "org_units", '"read_org_unit" in token.roles'),
    ("Query", "owners", '"read_owner" in token.roles'),
    ("Query", "policies", '"read_policy" in token.roles'),
    ("Query", "persons", '"read_employee" in token.roles'),
    ("Query", "registrations", '"read_registration" in token.roles'),
    ("Query", "related_units", '"read_related_unit" in token.roles'),
    ("Query", "rolebindings", '"read_rolebinding" in token.roles'),
    ("RelatedUnit", "org_units", '"read_org_unit" in token.roles'),
    ("RelatedUnit", "org_units_response", '"read_org_unit" in token.roles'),
    ("RoleBinding", "ituser", '"read_ituser" in token.roles'),
    ("RoleBinding", "ituser_response", '"read_ituser" in token.roles'),
    ("RoleBinding", "org_unit", '"read_org_unit" in token.roles'),
    ("RoleBinding", "org_unit_response", '"read_org_unit" in token.roles'),
    ("RoleBinding", "role", '"read_class" in token.roles'),
    ("RoleBinding", "role_response", '"read_class" in token.roles'),
    ("SpecialActor", "event_listeners", '"read_event_listener" in token.roles'),
    ("SpecialActor", "event_namespaces", '"read_event_namespace" in token.roles'),
    ("UnknownActor", "event_listeners", '"read_event_listener" in token.roles'),
    ("UnknownActor", "event_namespaces", '"read_event_namespace" in token.roles'),
]

# Introspection: allow GraphQL introspection for every actor. `__typename` is a
# meta-field that can appear under any type; the __-prefixed introspection types
# carry the remaining introspection fields.
INTROSPECTION_RULES = [
    ("*", "__typename"),
    ("Query", "__schema"),
    ("Query", "__type"),
    ("__Type", "*"),
    ("__Schema", "*"),
    ("__Field", "*"),
    ("__Directive", "*"),
    ("__EnumValue", "*"),
    ("__InputValue", "*"),
]

# Public: every field that requires no role under the legacy RBAC map (its
# `PUBLIC_FIELDS` entries). Generated from that map; granted to every actor.
PUBLIC_RULES: list[tuple[str, str]] = [
    ("AccessLog", "actor"),
    ("AccessLog", "actor_object"),
    ("AccessLog", "id"),
    ("AccessLog", "model"),
    ("AccessLog", "time"),
    ("AccessLog", "uuids"),
    ("AccessLogPaged", "objects"),
    ("AccessLogPaged", "page_info"),
    ("Address", "address_type_uuid"),
    ("Address", "employee_uuid"),
    ("Address", "engagement_uuid"),
    ("Address", "href"),
    ("Address", "ituser_uuid"),
    ("Address", "name"),
    ("Address", "org_unit_uuid"),
    ("Address", "resolve"),
    ("Address", "type"),
    ("Address", "user_key"),
    ("Address", "uuid"),
    ("Address", "validity"),
    ("Address", "value"),
    ("Address", "value2"),
    ("Address", "visibility_uuid"),
    ("AddressRegistration", "actor"),
    ("AddressRegistration", "actor_object"),
    ("AddressRegistration", "current"),
    ("AddressRegistration", "end"),
    ("AddressRegistration", "model"),
    ("AddressRegistration", "note"),
    ("AddressRegistration", "registration_id"),
    ("AddressRegistration", "start"),
    ("AddressRegistration", "uuid"),
    ("AddressRegistration", "validities"),
    ("AddressResponse", "current"),
    ("AddressResponse", "objects"),
    ("AddressResponse", "registrations"),
    ("AddressResponse", "uuid"),
    ("AddressResponse", "validities"),
    ("AddressResponsePaged", "objects"),
    ("AddressResponsePaged", "page_info"),
    ("AddressResponseRegistration", "actor"),
    ("AddressResponseRegistration", "actor_object"),
    ("AddressResponseRegistration", "current"),
    ("AddressResponseRegistration", "end"),
    ("AddressResponseRegistration", "model"),
    ("AddressResponseRegistration", "note"),
    ("AddressResponseRegistration", "registration_id"),
    ("AddressResponseRegistration", "start"),
    ("AddressResponseRegistration", "uuid"),
    ("AddressResponseRegistration", "validities"),
    ("Association", "association_type_uuid"),
    ("Association", "dynamic_class_uuid"),
    ("Association", "employee_uuid"),
    ("Association", "it_user_uuid"),
    ("Association", "job_function_uuid"),
    ("Association", "org_unit_uuid"),
    ("Association", "primary_uuid"),
    ("Association", "substitute_uuid"),
    ("Association", "trade_union_uuid"),
    ("Association", "type"),
    ("Association", "user_key"),
    ("Association", "uuid"),
    ("Association", "validity"),
    ("AssociationRegistration", "actor"),
    ("AssociationRegistration", "actor_object"),
    ("AssociationRegistration", "current"),
    ("AssociationRegistration", "end"),
    ("AssociationRegistration", "model"),
    ("AssociationRegistration", "note"),
    ("AssociationRegistration", "registration_id"),
    ("AssociationRegistration", "start"),
    ("AssociationRegistration", "uuid"),
    ("AssociationRegistration", "validities"),
    ("AssociationResponse", "current"),
    ("AssociationResponse", "objects"),
    ("AssociationResponse", "registrations"),
    ("AssociationResponse", "uuid"),
    ("AssociationResponse", "validities"),
    ("AssociationResponsePaged", "objects"),
    ("AssociationResponsePaged", "page_info"),
    ("AssociationResponseRegistration", "actor"),
    ("AssociationResponseRegistration", "actor_object"),
    ("AssociationResponseRegistration", "current"),
    ("AssociationResponseRegistration", "end"),
    ("AssociationResponseRegistration", "model"),
    ("AssociationResponseRegistration", "note"),
    ("AssociationResponseRegistration", "registration_id"),
    ("AssociationResponseRegistration", "start"),
    ("AssociationResponseRegistration", "uuid"),
    ("AssociationResponseRegistration", "validities"),
    ("Class", "description"),
    ("Class", "example"),
    ("Class", "facet_uuid"),
    ("Class", "full_name"),
    ("Class", "it_system_uuid"),
    ("Class", "name"),
    ("Class", "org_uuid"),
    ("Class", "owner"),
    ("Class", "parent_uuid"),
    ("Class", "published"),
    ("Class", "scope"),
    ("Class", "type"),
    ("Class", "user_key"),
    ("Class", "uuid"),
    ("Class", "validity"),
    ("ClassRegistration", "actor"),
    ("ClassRegistration", "actor_object"),
    ("ClassRegistration", "current"),
    ("ClassRegistration", "end"),
    ("ClassRegistration", "model"),
    ("ClassRegistration", "note"),
    ("ClassRegistration", "registration_id"),
    ("ClassRegistration", "start"),
    ("ClassRegistration", "uuid"),
    ("ClassRegistration", "validities"),
    ("ClassResponse", "current"),
    ("ClassResponse", "objects"),
    ("ClassResponse", "registrations"),
    ("ClassResponse", "uuid"),
    ("ClassResponse", "validities"),
    ("ClassResponsePaged", "objects"),
    ("ClassResponsePaged", "page_info"),
    ("ClassResponseRegistration", "actor"),
    ("ClassResponseRegistration", "actor_object"),
    ("ClassResponseRegistration", "current"),
    ("ClassResponseRegistration", "end"),
    ("ClassResponseRegistration", "model"),
    ("ClassResponseRegistration", "note"),
    ("ClassResponseRegistration", "registration_id"),
    ("ClassResponseRegistration", "start"),
    ("ClassResponseRegistration", "uuid"),
    ("ClassResponseRegistration", "validities"),
    ("DARAddress", "description"),
    ("DARAddress", "door"),
    ("DARAddress", "floor"),
    ("DARAddress", "house_number"),
    ("DARAddress", "href"),
    ("DARAddress", "latitude"),
    ("DARAddress", "longitude"),
    ("DARAddress", "municipality_code"),
    ("DARAddress", "name"),
    ("DARAddress", "road_code"),
    ("DARAddress", "road_name"),
    ("DARAddress", "streetmap_href"),
    ("DARAddress", "supplementary_city"),
    ("DARAddress", "value"),
    ("DARAddress", "zip_code"),
    ("DARAddress", "zip_code_name"),
    ("DefaultAddress", "value"),
    ("Employee", "cpr_no"),
    ("Employee", "cpr_number"),
    ("Employee", "given_name"),
    ("Employee", "givenname"),
    ("Employee", "name"),
    ("Employee", "nickname"),
    ("Employee", "nickname_given_name"),
    ("Employee", "nickname_givenname"),
    ("Employee", "nickname_surname"),
    ("Employee", "seniority"),
    ("Employee", "surname"),
    ("Employee", "type"),
    ("Employee", "user_key"),
    ("Employee", "uuid"),
    ("Employee", "validity"),
    ("EmployeeResponse", "current"),
    ("EmployeeResponse", "objects"),
    ("EmployeeResponse", "registrations"),
    ("EmployeeResponse", "uuid"),
    ("EmployeeResponse", "validities"),
    ("EmployeeResponsePaged", "objects"),
    ("EmployeeResponsePaged", "page_info"),
    ("EmployeeResponseRegistration", "actor"),
    ("EmployeeResponseRegistration", "actor_object"),
    ("EmployeeResponseRegistration", "current"),
    ("EmployeeResponseRegistration", "end"),
    ("EmployeeResponseRegistration", "model"),
    ("EmployeeResponseRegistration", "note"),
    ("EmployeeResponseRegistration", "registration_id"),
    ("EmployeeResponseRegistration", "start"),
    ("EmployeeResponseRegistration", "uuid"),
    ("EmployeeResponseRegistration", "validities"),
    ("Engagement", "employee_uuid"),
    ("Engagement", "engagement_type_uuid"),
    ("Engagement", "extension_1"),
    ("Engagement", "extension_10"),
    ("Engagement", "extension_2"),
    ("Engagement", "extension_3"),
    ("Engagement", "extension_4"),
    ("Engagement", "extension_5"),
    ("Engagement", "extension_6"),
    ("Engagement", "extension_7"),
    ("Engagement", "extension_8"),
    ("Engagement", "extension_9"),
    ("Engagement", "fraction"),
    ("Engagement", "is_primary"),
    ("Engagement", "job_function_uuid"),
    ("Engagement", "leave_uuid"),
    ("Engagement", "org_unit_uuid"),
    ("Engagement", "primary_uuid"),
    ("Engagement", "type"),
    ("Engagement", "user_key"),
    ("Engagement", "uuid"),
    ("Engagement", "validity"),
    ("EngagementRegistration", "actor"),
    ("EngagementRegistration", "actor_object"),
    ("EngagementRegistration", "current"),
    ("EngagementRegistration", "end"),
    ("EngagementRegistration", "model"),
    ("EngagementRegistration", "note"),
    ("EngagementRegistration", "registration_id"),
    ("EngagementRegistration", "start"),
    ("EngagementRegistration", "uuid"),
    ("EngagementRegistration", "validities"),
    ("EngagementResponse", "current"),
    ("EngagementResponse", "objects"),
    ("EngagementResponse", "registrations"),
    ("EngagementResponse", "uuid"),
    ("EngagementResponse", "validities"),
    ("EngagementResponsePaged", "objects"),
    ("EngagementResponsePaged", "page_info"),
    ("EngagementResponseRegistration", "actor"),
    ("EngagementResponseRegistration", "actor_object"),
    ("EngagementResponseRegistration", "current"),
    ("EngagementResponseRegistration", "end"),
    ("EngagementResponseRegistration", "model"),
    ("EngagementResponseRegistration", "note"),
    ("EngagementResponseRegistration", "registration_id"),
    ("EngagementResponseRegistration", "start"),
    ("EngagementResponseRegistration", "uuid"),
    ("EngagementResponseRegistration", "validities"),
    ("Event", "priority"),
    ("Event", "subject"),
    ("Event", "token"),
    ("Facet", "description"),
    ("Facet", "org_uuid"),
    ("Facet", "parent_uuid"),
    ("Facet", "published"),
    ("Facet", "type"),
    ("Facet", "user_key"),
    ("Facet", "uuid"),
    ("Facet", "validity"),
    ("FacetRegistration", "actor"),
    ("FacetRegistration", "actor_object"),
    ("FacetRegistration", "current"),
    ("FacetRegistration", "end"),
    ("FacetRegistration", "model"),
    ("FacetRegistration", "note"),
    ("FacetRegistration", "registration_id"),
    ("FacetRegistration", "start"),
    ("FacetRegistration", "uuid"),
    ("FacetRegistration", "validities"),
    ("FacetResponse", "current"),
    ("FacetResponse", "objects"),
    ("FacetResponse", "registrations"),
    ("FacetResponse", "uuid"),
    ("FacetResponse", "validities"),
    ("FacetResponsePaged", "objects"),
    ("FacetResponsePaged", "page_info"),
    ("FacetResponseRegistration", "actor"),
    ("FacetResponseRegistration", "actor_object"),
    ("FacetResponseRegistration", "current"),
    ("FacetResponseRegistration", "end"),
    ("FacetResponseRegistration", "model"),
    ("FacetResponseRegistration", "note"),
    ("FacetResponseRegistration", "registration_id"),
    ("FacetResponseRegistration", "start"),
    ("FacetResponseRegistration", "uuid"),
    ("FacetResponseRegistration", "validities"),
    ("File", "base64_contents"),
    ("File", "file_name"),
    ("File", "file_store"),
    ("File", "text_contents"),
    ("FilePaged", "objects"),
    ("FilePaged", "page_info"),
    ("FullEvent", "priority"),
    ("FullEvent", "silenced"),
    ("FullEvent", "subject"),
    ("FullEventPaged", "objects"),
    ("FullEventPaged", "page_info"),
    ("Health", "identifier"),
    ("Health", "status"),
    ("HealthPaged", "objects"),
    ("HealthPaged", "page_info"),
    ("IRegistrationPaged", "objects"),
    ("IRegistrationPaged", "page_info"),
    ("ITSystem", "name"),
    ("ITSystem", "system_type"),
    ("ITSystem", "type"),
    ("ITSystem", "user_key"),
    ("ITSystem", "uuid"),
    ("ITSystem", "validity"),
    ("ITSystemRegistration", "actor"),
    ("ITSystemRegistration", "actor_object"),
    ("ITSystemRegistration", "current"),
    ("ITSystemRegistration", "end"),
    ("ITSystemRegistration", "model"),
    ("ITSystemRegistration", "note"),
    ("ITSystemRegistration", "registration_id"),
    ("ITSystemRegistration", "start"),
    ("ITSystemRegistration", "uuid"),
    ("ITSystemRegistration", "validities"),
    ("ITSystemResponse", "current"),
    ("ITSystemResponse", "objects"),
    ("ITSystemResponse", "registrations"),
    ("ITSystemResponse", "uuid"),
    ("ITSystemResponse", "validities"),
    ("ITSystemResponsePaged", "objects"),
    ("ITSystemResponsePaged", "page_info"),
    ("ITSystemResponseRegistration", "actor"),
    ("ITSystemResponseRegistration", "actor_object"),
    ("ITSystemResponseRegistration", "current"),
    ("ITSystemResponseRegistration", "end"),
    ("ITSystemResponseRegistration", "model"),
    ("ITSystemResponseRegistration", "note"),
    ("ITSystemResponseRegistration", "registration_id"),
    ("ITSystemResponseRegistration", "start"),
    ("ITSystemResponseRegistration", "uuid"),
    ("ITSystemResponseRegistration", "validities"),
    ("ITUser", "binding_type"),
    ("ITUser", "employee_uuid"),
    ("ITUser", "engagement_uuid"),
    ("ITUser", "engagement_uuids"),
    ("ITUser", "external_id"),
    ("ITUser", "itsystem_uuid"),
    ("ITUser", "org_unit_uuid"),
    ("ITUser", "primary_uuid"),
    ("ITUser", "type"),
    ("ITUser", "user_key"),
    ("ITUser", "uuid"),
    ("ITUser", "validity"),
    ("ITUserRegistration", "actor"),
    ("ITUserRegistration", "actor_object"),
    ("ITUserRegistration", "current"),
    ("ITUserRegistration", "end"),
    ("ITUserRegistration", "model"),
    ("ITUserRegistration", "note"),
    ("ITUserRegistration", "registration_id"),
    ("ITUserRegistration", "start"),
    ("ITUserRegistration", "uuid"),
    ("ITUserRegistration", "validities"),
    ("ITUserResponse", "current"),
    ("ITUserResponse", "objects"),
    ("ITUserResponse", "registrations"),
    ("ITUserResponse", "uuid"),
    ("ITUserResponse", "validities"),
    ("ITUserResponsePaged", "objects"),
    ("ITUserResponsePaged", "page_info"),
    ("ITUserResponseRegistration", "actor"),
    ("ITUserResponseRegistration", "actor_object"),
    ("ITUserResponseRegistration", "current"),
    ("ITUserResponseRegistration", "end"),
    ("ITUserResponseRegistration", "model"),
    ("ITUserResponseRegistration", "note"),
    ("ITUserResponseRegistration", "registration_id"),
    ("ITUserResponseRegistration", "start"),
    ("ITUserResponseRegistration", "uuid"),
    ("ITUserResponseRegistration", "validities"),
    ("KLE", "kle_aspect_uuids"),
    ("KLE", "kle_number_uuid"),
    ("KLE", "org_unit_uuid"),
    ("KLE", "type"),
    ("KLE", "user_key"),
    ("KLE", "uuid"),
    ("KLE", "validity"),
    ("KLERegistration", "actor"),
    ("KLERegistration", "actor_object"),
    ("KLERegistration", "current"),
    ("KLERegistration", "end"),
    ("KLERegistration", "model"),
    ("KLERegistration", "note"),
    ("KLERegistration", "registration_id"),
    ("KLERegistration", "start"),
    ("KLERegistration", "uuid"),
    ("KLERegistration", "validities"),
    ("KLEResponse", "current"),
    ("KLEResponse", "objects"),
    ("KLEResponse", "registrations"),
    ("KLEResponse", "uuid"),
    ("KLEResponse", "validities"),
    ("KLEResponsePaged", "objects"),
    ("KLEResponsePaged", "page_info"),
    ("KLEResponseRegistration", "actor"),
    ("KLEResponseRegistration", "actor_object"),
    ("KLEResponseRegistration", "current"),
    ("KLEResponseRegistration", "end"),
    ("KLEResponseRegistration", "model"),
    ("KLEResponseRegistration", "note"),
    ("KLEResponseRegistration", "registration_id"),
    ("KLEResponseRegistration", "start"),
    ("KLEResponseRegistration", "uuid"),
    ("KLEResponseRegistration", "validities"),
    ("Leave", "employee_uuid"),
    ("Leave", "engagement_uuid"),
    ("Leave", "leave_type_uuid"),
    ("Leave", "type"),
    ("Leave", "user_key"),
    ("Leave", "uuid"),
    ("Leave", "validity"),
    ("LeaveRegistration", "actor"),
    ("LeaveRegistration", "actor_object"),
    ("LeaveRegistration", "current"),
    ("LeaveRegistration", "end"),
    ("LeaveRegistration", "model"),
    ("LeaveRegistration", "note"),
    ("LeaveRegistration", "registration_id"),
    ("LeaveRegistration", "start"),
    ("LeaveRegistration", "uuid"),
    ("LeaveRegistration", "validities"),
    ("LeaveResponse", "current"),
    ("LeaveResponse", "objects"),
    ("LeaveResponse", "registrations"),
    ("LeaveResponse", "uuid"),
    ("LeaveResponse", "validities"),
    ("LeaveResponsePaged", "objects"),
    ("LeaveResponsePaged", "page_info"),
    ("LeaveResponseRegistration", "actor"),
    ("LeaveResponseRegistration", "actor_object"),
    ("LeaveResponseRegistration", "current"),
    ("LeaveResponseRegistration", "end"),
    ("LeaveResponseRegistration", "model"),
    ("LeaveResponseRegistration", "note"),
    ("LeaveResponseRegistration", "registration_id"),
    ("LeaveResponseRegistration", "start"),
    ("LeaveResponseRegistration", "uuid"),
    ("LeaveResponseRegistration", "validities"),
    ("Listener", "owner"),
    ("Listener", "routing_key"),
    ("Listener", "user_key"),
    ("Listener", "uuid"),
    ("ListenerPaged", "objects"),
    ("ListenerPaged", "page_info"),
    ("Manager", "employee_uuid"),
    ("Manager", "manager_level_uuid"),
    ("Manager", "manager_type_uuid"),
    ("Manager", "org_unit_uuid"),
    ("Manager", "responsibility_uuids"),
    ("Manager", "type"),
    ("Manager", "user_key"),
    ("Manager", "uuid"),
    ("Manager", "validity"),
    ("ManagerRegistration", "actor"),
    ("ManagerRegistration", "actor_object"),
    ("ManagerRegistration", "current"),
    ("ManagerRegistration", "end"),
    ("ManagerRegistration", "model"),
    ("ManagerRegistration", "note"),
    ("ManagerRegistration", "registration_id"),
    ("ManagerRegistration", "start"),
    ("ManagerRegistration", "uuid"),
    ("ManagerRegistration", "validities"),
    ("ManagerResponse", "current"),
    ("ManagerResponse", "objects"),
    ("ManagerResponse", "registrations"),
    ("ManagerResponse", "uuid"),
    ("ManagerResponse", "validities"),
    ("ManagerResponsePaged", "objects"),
    ("ManagerResponsePaged", "page_info"),
    ("ManagerResponseRegistration", "actor"),
    ("ManagerResponseRegistration", "actor_object"),
    ("ManagerResponseRegistration", "current"),
    ("ManagerResponseRegistration", "end"),
    ("ManagerResponseRegistration", "model"),
    ("ManagerResponseRegistration", "note"),
    ("ManagerResponseRegistration", "registration_id"),
    ("ManagerResponseRegistration", "start"),
    ("ManagerResponseRegistration", "uuid"),
    ("ManagerResponseRegistration", "validities"),
    ("MultifieldAddress", "name"),
    ("MultifieldAddress", "value"),
    ("MultifieldAddress", "value2"),
    ("Myself", "actor"),
    ("Myself", "email"),
    ("Myself", "policies"),
    ("Myself", "roles"),
    ("Myself", "username"),
    ("Namespace", "name"),
    ("Namespace", "owner"),
    ("Namespace", "public"),
    ("NamespacePaged", "objects"),
    ("NamespacePaged", "page_info"),
    ("OpenValidity", "from"),
    ("OpenValidity", "to"),
    ("Organisation", "municipality_code"),
    ("Organisation", "name"),
    ("Organisation", "type"),
    ("Organisation", "user_key"),
    ("Organisation", "uuid"),
    ("OrganisationUnit", "name"),
    ("OrganisationUnit", "org_unit_hierarchy"),
    ("OrganisationUnit", "org_unit_level_uuid"),
    ("OrganisationUnit", "parent_uuid"),
    ("OrganisationUnit", "time_planning_uuid"),
    ("OrganisationUnit", "type"),
    ("OrganisationUnit", "unit_type_uuid"),
    ("OrganisationUnit", "user_key"),
    ("OrganisationUnit", "uuid"),
    ("OrganisationUnit", "validity"),
    ("OrganisationUnitRegistration", "actor"),
    ("OrganisationUnitRegistration", "actor_object"),
    ("OrganisationUnitRegistration", "current"),
    ("OrganisationUnitRegistration", "end"),
    ("OrganisationUnitRegistration", "model"),
    ("OrganisationUnitRegistration", "note"),
    ("OrganisationUnitRegistration", "registration_id"),
    ("OrganisationUnitRegistration", "start"),
    ("OrganisationUnitRegistration", "uuid"),
    ("OrganisationUnitRegistration", "validities"),
    ("OrganisationUnitResponse", "current"),
    ("OrganisationUnitResponse", "objects"),
    ("OrganisationUnitResponse", "registrations"),
    ("OrganisationUnitResponse", "uuid"),
    ("OrganisationUnitResponse", "validities"),
    ("OrganisationUnitResponsePaged", "objects"),
    ("OrganisationUnitResponsePaged", "page_info"),
    ("OrganisationUnitResponseRegistration", "actor"),
    ("OrganisationUnitResponseRegistration", "actor_object"),
    ("OrganisationUnitResponseRegistration", "current"),
    ("OrganisationUnitResponseRegistration", "end"),
    ("OrganisationUnitResponseRegistration", "model"),
    ("OrganisationUnitResponseRegistration", "note"),
    ("OrganisationUnitResponseRegistration", "registration_id"),
    ("OrganisationUnitResponseRegistration", "start"),
    ("OrganisationUnitResponseRegistration", "uuid"),
    ("OrganisationUnitResponseRegistration", "validities"),
    ("Owner", "employee_uuid"),
    ("Owner", "org_unit_uuid"),
    ("Owner", "owner_inference_priority"),
    ("Owner", "owner_uuid"),
    ("Owner", "type"),
    ("Owner", "user_key"),
    ("Owner", "uuid"),
    ("Owner", "validity"),
    ("OwnerRegistration", "actor"),
    ("OwnerRegistration", "actor_object"),
    ("OwnerRegistration", "current"),
    ("OwnerRegistration", "end"),
    ("OwnerRegistration", "model"),
    ("OwnerRegistration", "note"),
    ("OwnerRegistration", "registration_id"),
    ("OwnerRegistration", "start"),
    ("OwnerRegistration", "uuid"),
    ("OwnerRegistration", "validities"),
    ("OwnerResponse", "current"),
    ("OwnerResponse", "objects"),
    ("OwnerResponse", "registrations"),
    ("OwnerResponse", "uuid"),
    ("OwnerResponse", "validities"),
    ("OwnerResponsePaged", "objects"),
    ("OwnerResponsePaged", "page_info"),
    ("OwnerResponseRegistration", "actor"),
    ("OwnerResponseRegistration", "actor_object"),
    ("OwnerResponseRegistration", "current"),
    ("OwnerResponseRegistration", "end"),
    ("OwnerResponseRegistration", "model"),
    ("OwnerResponseRegistration", "note"),
    ("OwnerResponseRegistration", "registration_id"),
    ("OwnerResponseRegistration", "start"),
    ("OwnerResponseRegistration", "uuid"),
    ("OwnerResponseRegistration", "validities"),
    ("PageInfo", "next_cursor"),
    ("PersonRegistration", "actor"),
    ("PersonRegistration", "actor_object"),
    ("PersonRegistration", "current"),
    ("PersonRegistration", "end"),
    ("PersonRegistration", "model"),
    ("PersonRegistration", "note"),
    ("PersonRegistration", "registration_id"),
    ("PersonRegistration", "start"),
    ("PersonRegistration", "uuid"),
    ("PersonRegistration", "validities"),
    ("Policy", "activated"),
    ("Policy", "actors"),
    ("Policy", "description"),
    ("Policy", "name"),
    ("Policy", "rules"),
    ("Policy", "uuid"),
    ("PolicyActor", "kind"),
    ("PolicyActor", "uuid"),
    ("PolicyActor", "value"),
    ("PolicyPaged", "objects"),
    ("PolicyPaged", "page_info"),
    ("PolicyRule", "condition"),
    ("PolicyRule", "field"),
    ("PolicyRule", "filter"),
    ("PolicyRule", "type"),
    ("PolicyRule", "uuid"),
    ("Query", "healths"),
    ("Query", "me"),
    ("Query", "version"),
    ("Registration", "actor"),
    ("Registration", "actor_object"),
    ("Registration", "end"),
    ("Registration", "model"),
    ("Registration", "note"),
    ("Registration", "registration_id"),
    ("Registration", "start"),
    ("Registration", "uuid"),
    ("RegistrationPaged", "objects"),
    ("RegistrationPaged", "page_info"),
    ("RelatedUnit", "org_unit_uuids"),
    ("RelatedUnit", "type"),
    ("RelatedUnit", "user_key"),
    ("RelatedUnit", "uuid"),
    ("RelatedUnit", "validity"),
    ("RelatedUnitRegistration", "actor"),
    ("RelatedUnitRegistration", "actor_object"),
    ("RelatedUnitRegistration", "current"),
    ("RelatedUnitRegistration", "end"),
    ("RelatedUnitRegistration", "model"),
    ("RelatedUnitRegistration", "note"),
    ("RelatedUnitRegistration", "registration_id"),
    ("RelatedUnitRegistration", "start"),
    ("RelatedUnitRegistration", "uuid"),
    ("RelatedUnitRegistration", "validities"),
    ("RelatedUnitResponse", "current"),
    ("RelatedUnitResponse", "objects"),
    ("RelatedUnitResponse", "registrations"),
    ("RelatedUnitResponse", "uuid"),
    ("RelatedUnitResponse", "validities"),
    ("RelatedUnitResponsePaged", "objects"),
    ("RelatedUnitResponsePaged", "page_info"),
    ("RelatedUnitResponseRegistration", "actor"),
    ("RelatedUnitResponseRegistration", "actor_object"),
    ("RelatedUnitResponseRegistration", "current"),
    ("RelatedUnitResponseRegistration", "end"),
    ("RelatedUnitResponseRegistration", "model"),
    ("RelatedUnitResponseRegistration", "note"),
    ("RelatedUnitResponseRegistration", "registration_id"),
    ("RelatedUnitResponseRegistration", "start"),
    ("RelatedUnitResponseRegistration", "uuid"),
    ("RelatedUnitResponseRegistration", "validities"),
    ("RoleBinding", "user_key"),
    ("RoleBinding", "uuid"),
    ("RoleBinding", "validity"),
    ("RoleBindingRegistration", "actor"),
    ("RoleBindingRegistration", "actor_object"),
    ("RoleBindingRegistration", "current"),
    ("RoleBindingRegistration", "end"),
    ("RoleBindingRegistration", "model"),
    ("RoleBindingRegistration", "note"),
    ("RoleBindingRegistration", "registration_id"),
    ("RoleBindingRegistration", "start"),
    ("RoleBindingRegistration", "uuid"),
    ("RoleBindingRegistration", "validities"),
    ("RoleBindingResponse", "current"),
    ("RoleBindingResponse", "objects"),
    ("RoleBindingResponse", "registrations"),
    ("RoleBindingResponse", "uuid"),
    ("RoleBindingResponse", "validities"),
    ("RoleBindingResponsePaged", "objects"),
    ("RoleBindingResponsePaged", "page_info"),
    ("RoleBindingResponseRegistration", "actor"),
    ("RoleBindingResponseRegistration", "actor_object"),
    ("RoleBindingResponseRegistration", "current"),
    ("RoleBindingResponseRegistration", "end"),
    ("RoleBindingResponseRegistration", "model"),
    ("RoleBindingResponseRegistration", "note"),
    ("RoleBindingResponseRegistration", "registration_id"),
    ("RoleBindingResponseRegistration", "start"),
    ("RoleBindingResponseRegistration", "uuid"),
    ("RoleBindingResponseRegistration", "validities"),
    ("SpecialActor", "display_name"),
    ("SpecialActor", "key"),
    ("SpecialActor", "uuid"),
    ("UUIDPaged", "objects"),
    ("UUIDPaged", "page_info"),
    ("UnknownActor", "display_name"),
    ("UnknownActor", "error"),
    ("UnknownActor", "uuid"),
    ("Validity", "from"),
    ("Validity", "to"),
    ("Version", "lora_version"),
    ("Version", "mo_hash"),
    ("Version", "mo_version"),
]


class _Cel(str):
    """A raw, unquoted CEL expression embedded in a check-spec (e.g. `actor`)."""


def _cel_json(value: object) -> str:
    """Serialize a check-spec to a CEL map literal: JSON, with bare `_Cel`."""
    if isinstance(value, _Cel):
        return str(value)
    if isinstance(value, dict):
        items = ", ".join(f"{json.dumps(k)}: {_cel_json(v)}" for k, v in value.items())
        return "{" + items + "}"
    if isinstance(value, list):
        return "[" + ", ".join(_cel_json(v) for v in value) + "]"
    return json.dumps(value)


_ACTOR = _Cel("actor")
# The owned entity, filtered by its owning person (`actor`).
_OWN_PERSON = {"owner": {"owner": {"uuids": [_ACTOR]}}}
# ... extended up the org-unit tree (self-or-ancestor).
_OWN_UNIT = {"ancestor": _OWN_PERSON}


def _unit(field: str) -> str:
    """Require ownership of the org-unit identified by ``field`` (hierarchical)."""
    return _cel_json(
        {
            "collection": "org_unit",
            "check": "IN",
            "field": _Cel(field),
            "filter": _OWN_UNIT,
        }
    )


def _person(field: str) -> str:
    """Require ownership of the person identified by ``field``."""
    return _cel_json(
        {
            "collection": "employee",
            "check": "IN",
            "field": _Cel(field),
            "filter": _OWN_PERSON,
        }
    )


def _obj_unit(collection: str, field: str) -> str:
    """Require the object (``field``) to link an org-unit the caller owns."""
    return _cel_json(
        {
            "collection": collection,
            "check": "IN",
            "field": _Cel(field),
            "filter": {"org_unit": _OWN_UNIT},
        }
    )


def _obj_person(collection: str, field: str) -> str:
    """Require the object (``field``) to link a person the caller owns."""
    return _cel_json(
        {
            "collection": collection,
            "check": "IN",
            "field": _Cel(field),
            "filter": {"employee": _OWN_PERSON},
        }
    )


# Detail-create branch: own the linked org-unit if present, else the person.
def _create_branch(item: str, person_field: str) -> str:
    return (
        f"{item}.org_unit != null ? {_unit(item + '.org_unit')} "
        f": {_person(person_field)}"
    )


def _person_ref(collection: str, item: str) -> str:
    """The CEL expression selecting the linked person's uuid for ``collection``.

    ``AddressCreateInput`` exposes both ``person`` and its ``employee`` alias
    (either may be set); the other create inputs only have ``person``.
    """
    if collection == "address":
        return f"({item}.employee != null ? {item}.employee : {item}.person)"
    return f"{item}.person"


# (field, filter-CEL) rules. A collection with two entries for one field is an
# OR (the object may link either an org-unit or a person).
OWNER_RULES: list[tuple[str, str]] = []


def _rule(field: str, filter_cel: str) -> None:
    OWNER_RULES.append((field, filter_cel))


# -- Detail collections -------------------------------------------------------
# Org-unit-mandatory (create -> own the org-unit; upd/term/del -> own the
# object's org-unit). `association` also covers the `itassociation_*` mutators.
for collection, fields in {
    "association": ["association", "itassociation"],
    "kle": ["kle"],
    "manager": ["manager"],
}.items():
    for prefix in fields:
        _rule(f"{prefix}_create", _unit("input.org_unit"))
        _rule(f"{prefix}_update", _obj_unit(collection, "input.uuid"))
        _rule(f"{prefix}_terminate", _obj_unit(collection, "input.uuid"))

# Engagement: create/terminate/delete require owning the (object's) org-unit.
# Update must additionally own the *destination* org-unit when the engagement is
# moved -- mirroring the legacy owner check, which required owning both source
# and target. The filter returns a list of check-specs (all must pass, i.e. AND).
_rule("engagement_create", _unit("input.org_unit"))
_rule(
    "engagement_update",
    f"[{_obj_unit('engagement', 'input.uuid')}]"
    f" + (input.org_unit != null ? [{_unit('input.org_unit')}] : [])",
)
_rule("engagement_terminate", _obj_unit("engagement", "input.uuid"))
_rule("engagement_delete", _obj_unit("engagement", "input.uuid"))
_rule("engagements_create", f"input.map(i, {_unit('i.org_unit')})")
_rule(
    "engagements_update",
    f"input.map(i, {_obj_unit('engagement', 'i.uuid')})"
    f" + input.filter(i, i.org_unit != null).map(i, {_unit('i.org_unit')})",
)
# manager has a bulk create.
_rule("managers_create", f"input.map(i, {_unit('i.org_unit')})")

# Person-only (leave).
_rule("leave_create", _person("input.person"))
_rule("leave_update", _obj_person("leave", "input.uuid"))
_rule("leave_terminate", _obj_person("leave", "input.uuid"))

# Rolebinding: org-unit (nullable, no person) + delete + bulk create.
for field in ("rolebinding_update", "rolebinding_terminate", "rolebinding_delete"):
    _rule(field, _obj_unit("rolebinding", "input.uuid"))
_rule("rolebinding_create", _unit("input.org_unit"))
_rule("rolebindings_create", f"input.map(i, {_unit('i.org_unit')})")

# Either org-unit or person (address, ituser, owner): two rules for
# upd/term/del, a branch for create.
for collection, ops in {
    "address": ("update", "terminate", "delete"),
    "ituser": ("update", "terminate", "delete"),
    "owner": ("update", "terminate"),
}.items():
    for op_name in ops:
        _rule(f"{collection}_{op_name}", _obj_unit(collection, "input.uuid"))
        _rule(f"{collection}_{op_name}", _obj_person(collection, "input.uuid"))
    _rule(
        f"{collection}_create",
        _create_branch("input", _person_ref(collection, "input")),
    )
# address / ituser bulk create.
_rule(
    "addresses_create",
    f"input.map(i, {_create_branch('i', _person_ref('address', 'i'))})",
)
_rule(
    "itusers_create", f"input.map(i, {_create_branch('i', _person_ref('ituser', 'i'))})"
)

# related_unit: only a (single-input) update, keyed on the origin unit.
_rule("related_units_update", _unit("input.origin"))

# -- Employee -----------------------------------------------------------------
# Own the person to mutate it. A brand-new uuid has no owners -> create denied.
for op_name in ("create", "update", "terminate", "delete"):
    _rule(f"employee_{op_name}", _person("input.uuid"))

# -- Org-unit -----------------------------------------------------------------
_rule("org_unit_create", _unit("input.parent"))
_rule("org_unit_terminate", _unit("input.uuid"))
_rule("org_unit_delete", _unit("input.uuid"))
# Move: always own the unit; additionally own the *new* parent, but only when the
# parent actually changed (mirrors check_owner's `if parent := ...` guard).
_rule(
    "org_unit_update",
    f"[{_unit('input.uuid')}] + "
    f"(input.parent != null && input.parent != current.parent "
    f"? [{_unit('input.parent')}] : [])",
)


def upgrade() -> None:
    op.bulk_insert(
        policy,
        [
            {
                "id": POLICYADMIN_UUID,
                "name": "Policy Administrator",
                "description": "Bootstrap policy for administering policies.",
                "activated": True,
            },
            {
                "id": PUBLIC_UUID,
                "name": "Public",
                "description": "Grants access to fields that require no role (public fields).",
                "activated": True,
            },
            {
                "id": INTROSPECTION_UUID,
                "name": "Introspection",
                "description": "Grants GraphQL introspection access to every actor.",
                "activated": True,
            },
            {
                "id": LEGACY_UUID,
                "name": "Legacy",
                "description": "Reproduces legacy RBAC: grants any field whose required role is on the token.",
                "activated": True,
            },
            {
                "id": OWNER_UUID,
                "name": "Owner",
                "description": "Grants owners access to the entities they own. A default starter policy; customize or remove it as needed.",
                "activated": True,
            },
            {
                "id": ADMINISTRATOR_UUID,
                "name": "Administrator",
                "description": "Grants access to all queries and mutators.",
                "activated": True,
            },
            {
                "id": READER_UUID,
                "name": "Reader",
                "description": "Grants read access to all queries.",
                "activated": True,
            },
        ],
    )
    op.bulk_insert(
        policy_actor,
        [
            {"kind": "role", "value": "admin", "policy_fk": POLICYADMIN_UUID},
            {"kind": "all", "value": "", "policy_fk": PUBLIC_UUID},
            {"kind": "all", "value": "", "policy_fk": INTROSPECTION_UUID},
            {"kind": "all", "value": "", "policy_fk": LEGACY_UUID},
            {"kind": "role", "value": "owner", "policy_fk": OWNER_UUID},
            {"kind": "role", "value": "admin", "policy_fk": ADMINISTRATOR_UUID},
            {"kind": "role", "value": "reader", "policy_fk": READER_UUID},
        ],
    )
    op.bulk_insert(
        policy_rule,
        [
            *[
                {
                    "type": t,
                    "field": f,
                    "condition": None,
                    "filter": None,
                    "policy_fk": POLICYADMIN_UUID,
                }
                for t, f in POLICYADMIN_RULES
            ],
            *[
                {
                    "type": t,
                    "field": f,
                    "condition": None,
                    "filter": None,
                    "policy_fk": PUBLIC_UUID,
                }
                for t, f in PUBLIC_RULES
            ],
            *[
                {
                    "type": t,
                    "field": f,
                    "condition": None,
                    "filter": None,
                    "policy_fk": INTROSPECTION_UUID,
                }
                for t, f in INTROSPECTION_RULES
            ],
            *[
                {
                    "type": t,
                    "field": f,
                    "condition": c,
                    "filter": None,
                    "policy_fk": LEGACY_UUID,
                }
                for t, f, c in LEGACY_RULES
            ],
            *[
                {
                    "type": "Mutation",
                    "field": field,
                    "condition": None,
                    "filter": flt,
                    "policy_fk": OWNER_UUID,
                }
                for field, flt in OWNER_RULES
            ],
            {
                "type": "Query",
                "field": "*",
                "condition": None,
                "filter": None,
                "policy_fk": ADMINISTRATOR_UUID,
            },
            {
                "type": "Mutation",
                "field": "*",
                "condition": None,
                "filter": None,
                "policy_fk": ADMINISTRATOR_UUID,
            },
            {
                "type": "Query",
                "field": "*",
                "condition": None,
                "filter": None,
                "policy_fk": READER_UUID,
            },
        ],
    )


def downgrade() -> None:
    ids = (
        f"'{POLICYADMIN_UUID}', '{PUBLIC_UUID}', '{INTROSPECTION_UUID}', "
        f"'{LEGACY_UUID}', '{OWNER_UUID}', '{ADMINISTRATOR_UUID}', '{READER_UUID}'"
    )
    op.execute(f"DELETE FROM policy_rule WHERE policy_fk IN ({ids})")
    op.execute(f"DELETE FROM policy_actor WHERE policy_fk IN ({ids})")
    op.execute(f"DELETE FROM policy WHERE id IN ({ids})")
