# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime
from uuid import UUID

import pytest

from mo_ldap_import_export.autogenerated_graphql_client import EngagementCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.environments.main import get_employment_interval
from mo_ldap_import_export.utils import MO_TZ


@pytest.mark.integration_test
@pytest.mark.usefixtures("test_client")
async def test_get_employment_interval_with_exclusion(
    graphql_client: GraphQLClient,
    mo_person: UUID,
    mo_org_unit: UUID,
    jurist: UUID,
    primary: UUID,
    ansat: UUID,
    praktikant: UUID,
) -> None:
    await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key="included_1",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            validity={"from": "2020-01-01T00:00:00Z", "to": "2020-12-31T00:00:00Z"},
        )
    )
    await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key="included_2",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            validity={"from": "2021-01-01T00:00:00Z", "to": "2021-12-31T00:00:00Z"},
        )
    )
    await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key="excluded_1",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=praktikant,
            job_function=jurist,
            primary=primary,
            validity={"from": "2019-01-01T00:00:00Z", "to": "2022-12-31T00:00:00Z"},
        )
    )

    start_date, end_date = await get_employment_interval(
        graphql_client,
        mo_person,
        exclude_engagement_types={praktikant},
    )

    assert start_date == datetime(2020, 1, 1, tzinfo=MO_TZ)
    assert end_date == datetime(2021, 12, 31, tzinfo=MO_TZ)


@pytest.mark.integration_test
@pytest.mark.usefixtures("test_client")
async def test_get_employment_interval_with_all_excluded(
    graphql_client: GraphQLClient,
    mo_person: UUID,
    mo_org_unit: UUID,
    jurist: UUID,
    primary: UUID,
    praktikant: UUID,
) -> None:
    """When all engagements are excluded, the function should not crash."""
    await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key="excluded_1",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=praktikant,
            job_function=jurist,
            primary=primary,
            validity={"from": "2019-01-01T00:00:00Z", "to": "2022-12-31T00:00:00Z"},
        )
    )

    start_date, end_date = await get_employment_interval(
        graphql_client,
        mo_person,
        exclude_engagement_types={praktikant},
    )

    assert start_date is None
    assert end_date is None
