# SPDX-FileCopyrightText: 2022 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

stages:
  - release

include:
  - project: labs/salt-automation
    file: gitlab-ci-templates/common/rules.v1.yml

Release to PyPI:
  extends:
    - .rules:semver-core
  stage: release
  needs: []
  image: python:3-slim
  variables:
    POETRY_VIRTUALENVS_CREATE: "false"
    POETRY_VIRTUALENVS_IN_PROJECT: "false"
  before_script:
    - pip install --no-cache-dir poetry
  script:
    - sed -i "s/^version = .*$/version = \"${CI_COMMIT_TAG}\"/g" pyproject.toml
    - poetry publish --build --no-interaction --username __token__ --password ${PYPI_TOKEN}
