# Copyright (C) 2020 Magenta ApS, http://magenta.dk.
# Contact: info@magenta.dk.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
# Changes to this file requires approval from Labs. Please add a person from   #
# Labs as required approval to your MR if you have any changes.                #
################################################################################

# This file contains the docker-specific configuration. If you want to
# configure OS2MO in development setting, refer to
# ``dev-environment/mo-dev-settings.toml``.

[log]
activity_log_path = "/log/activity.log"
trace_log_path = "/log/trace.log"
