# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0


# DO NOT CHANGE. This file contains the default configuration for OS2MO.
# DO NOT CHANGE. You can configure OS2MO in the mo-dev-settings.toml file.


hide_cpr_numbers = false
dummy_mode = false
ca_bundle = ""

# If application is deployed behind a proxy. Makes url_for generate URLs for
# this specific server name regardless of where the request comes from
server_name = ""


[lora]
url = "http://localhost:8080/"
max_request_length = 4096
default_page_size = 2000
tree_search_limit = 100


[autocomplete]
access_address_count = 5
address_count = 10


[organisation]
name = ""
user_key = ""
uuid = ""


[session]
cookie_name = "session"
permanent = true
permanent_lifetime = 3600
service_session_lifetime = 2678400

[session.database]
sqlalchemy_uri = ""
sqlalchemy_table = "sessions"
name = "sessions"
user = "sessions"
password = "sessions"
host = "localhost"
port = 5432


[saml_sso]
# flask_saml_sso reads many of these off of app.config. Please refer to
# settings.py to see exactly which are used and what flask_saml_sso
# configuration parameter they map to.
enable = false
idp_metadata_url = "/url/to/sso/metadata"
idp_metadata_file = ""
idp_insecure = false
force_https = false
name_id_format = "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
lowercase_urlencoding = true
want_name_id = true
want_attribute_statement = false
requested_authn_context = true
requested_authn_context_comparison = "exact"
username_from_nameid = true
username_attr = ""
key_file = ""
cert_file = ""
signature_algorithm = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
digest_algorithm = "http://www.w3.org/2001/04/xmlenc#sha256"
requests_signed = false
duplicate_attributes = true
api_token_restrict = false
api_token_restrict_attr = ""
api_token_restrict_value = ""


[query_export]
directory = ""


[service_platformen]
uuid = ""
agreement_uuid = ""
municipality_uuid = ""
system_uuid = ""
certificate_path = ""


[configuration.database]
name = "mora"
user = "mora"
password = "mora"
host = "localhost"
port = 5432


[amqp]
enable = false
os2mo_exchange = "os2mo_queue"
host = "localhost"
port = 5672


[triggers]
modules = []


[log]
activity_log_path = "activity.log"
log_path = "os2mo.log"
log_level = "WARNING"


[external_integration]
# Path to where the org unit integration is running
org_unit = ""
