# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0


# DO NOT CHANGE. This file contains the default configuration for OS2MO.
# DO NOT CHANGE. You can configure OS2MO in the mo-dev-settings.toml file.


hide_cpr_numbers = false
dummy_mode = false
ENV='production'

# If the application is deployed behind a proxy. Makes url_for generate URLs
# for this specific server name regardless of where the request comes from.
server_name = ""
# If the application is accessed from javascript from another host, this
# should be enabled.
enable_cors = false


[lora]
url = "http://localhost:80/"


[autocomplete]
access_address_count = 5
address_count = 10


[organisation]
name = ""
user_key = ""
uuid = ""


[auth]
keycloak_schema = "https"
keycloak_host = "keycloak"
keycloak_port = 443
keycloak_realm = "mo"
keycloak_signing_alg = "RS256"


[query_export]
directory = ""


[service_platformen]
uuid = ""
agreement_uuid = ""
municipality_uuid = ""
system_uuid = ""
certificate_path = ""
# production flag for sp integration module
sp_production = true


[configuration.database]
name = "mora"
user = "mora"
password = "mora"
host = "localhost"
port = 5432


[amqp]
enable = false
os2mo_exchange = "os2mo_queue"
host = "localhost"
port = 5672

[triggers]
modules = []

[triggers.http_trigger]
enabled = false
http_endpoints = []

[log]
log_path = ""
log_level = "WARNING"


[external_integration]
# Path to where the org unit integration is running
org_unit = ""


[[navlinks]]
# Default to empty set of navlinks
