# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Which entities each mutator touches, for the owner check.

Maps a GraphQL mutation field to the `(collection, permission_type)` of the
entities it acts on. This is used solely to extract the entities an owner must
own for the owner check; access control itself keys off the mutator name.
"""

from mora.graphapi.permissions import CollectionPermissionType
from mora.graphapi.permissions import Collections

OwnerEntities = tuple[Collections, CollectionPermissionType]

OWNER_ENTITIES: dict[str, OwnerEntities] = {
    "address_create": ("address", "create"),
    "address_delete": ("address", "delete"),
    "address_refresh": ("address", "refresh"),
    "address_terminate": ("address", "terminate"),
    "address_update": ("address", "update"),
    "addresses_create": ("address", "create"),
    "association_create": ("association", "create"),
    "association_delete": ("association", "delete"),
    "association_refresh": ("association", "refresh"),
    "association_terminate": ("association", "terminate"),
    "association_update": ("association", "update"),
    "class_create": ("class", "create"),
    "class_delete": ("class", "delete"),
    "class_refresh": ("class", "refresh"),
    "class_terminate": ("class", "terminate"),
    "class_update": ("class", "update"),
    "employee_create": ("employee", "create"),
    "employee_delete": ("employee", "delete"),
    "employee_refresh": ("employee", "refresh"),
    "employee_terminate": ("employee", "terminate"),
    "employee_update": ("employee", "update"),
    "engagement_create": ("engagement", "create"),
    "engagement_delete": ("engagement", "delete"),
    "engagement_refresh": ("engagement", "refresh"),
    "engagement_terminate": ("engagement", "terminate"),
    "engagement_update": ("engagement", "update"),
    "engagements_create": ("engagement", "create"),
    "engagements_update": ("engagement", "update"),
    "event_listener_declare": ("event_listener", "create"),
    "event_listener_delete": ("event_listener", "delete"),
    "event_namespace_declare": ("event_namespace", "create"),
    "event_namespace_delete": ("event_namespace", "delete"),
    "facet_create": ("facet", "create"),
    "facet_delete": ("facet", "delete"),
    "facet_refresh": ("facet", "refresh"),
    "facet_terminate": ("facet", "terminate"),
    "facet_update": ("facet", "update"),
    "itassociation_create": ("association", "create"),
    "itassociation_terminate": ("association", "terminate"),
    "itassociation_update": ("association", "update"),
    "itsystem_create": ("itsystem", "create"),
    "itsystem_delete": ("itsystem", "delete"),
    "itsystem_refresh": ("itsystem", "refresh"),
    "itsystem_terminate": ("itsystem", "terminate"),
    "itsystem_update": ("itsystem", "update"),
    "ituser_create": ("ituser", "create"),
    "ituser_delete": ("ituser", "delete"),
    "ituser_refresh": ("ituser", "refresh"),
    "ituser_terminate": ("ituser", "terminate"),
    "ituser_update": ("ituser", "update"),
    "itusers_create": ("ituser", "create"),
    "kle_create": ("kle", "create"),
    "kle_delete": ("kle", "delete"),
    "kle_refresh": ("kle", "refresh"),
    "kle_terminate": ("kle", "terminate"),
    "kle_update": ("kle", "update"),
    "leave_create": ("leave", "create"),
    "leave_delete": ("leave", "delete"),
    "leave_refresh": ("leave", "refresh"),
    "leave_terminate": ("leave", "terminate"),
    "leave_update": ("leave", "update"),
    "manager_create": ("manager", "create"),
    "manager_delete": ("manager", "delete"),
    "manager_refresh": ("manager", "refresh"),
    "manager_terminate": ("manager", "terminate"),
    "manager_update": ("manager", "update"),
    "managers_create": ("manager", "create"),
    "org_create": ("org", "create"),
    "org_unit_create": ("org_unit", "create"),
    "org_unit_delete": ("org_unit", "delete"),
    "org_unit_refresh": ("org_unit", "refresh"),
    "org_unit_terminate": ("org_unit", "terminate"),
    "org_unit_update": ("org_unit", "update"),
    "owner_create": ("owner", "create"),
    "owner_delete": ("owner", "delete"),
    "owner_refresh": ("owner", "refresh"),
    "owner_terminate": ("owner", "terminate"),
    "owner_update": ("owner", "update"),
    "related_unit_refresh": ("related_unit", "refresh"),
    "related_units_update": ("related_unit", "update"),
    "rolebinding_create": ("rolebinding", "create"),
    "rolebinding_delete": ("rolebinding", "delete"),
    "rolebinding_refresh": ("rolebinding", "refresh"),
    "rolebinding_terminate": ("rolebinding", "terminate"),
    "rolebinding_update": ("rolebinding", "update"),
    "rolebindings_create": ("rolebinding", "create"),
}
