# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
    from mora.graphapi.permissions import CollectionPermissionType
    from mora.graphapi.permissions import Collections

# A derived RBAC requirement: (role, collection, permission_type).
# `collection` and `permission_type` are `None` for roles that do not
# follow the `{type}_{collection}` pattern (e.g. `fetch_event`), which also
# means the owner-fallback does not apply.
RBACRequirement = tuple[str, "Collections | None", "CollectionPermissionType | None"]

# Fields which are public: every user may access them.
PUBLIC_FIELDS: frozenset[tuple[str, str]] = frozenset(
    {
        ("AccessLog", "actor"),
        ("AccessLog", "actor_object"),
        ("AccessLog", "id"),
        ("AccessLog", "model"),
        ("AccessLog", "time"),
        ("AccessLog", "uuids"),
        ("AccessLogPaged", "objects"),
        ("AccessLogPaged", "page_info"),
        ("Address", "address_type_uuid"),
        ("Address", "employee_uuid"),
        ("Address", "engagement_uuid"),
        ("Address", "href"),
        ("Address", "ituser_uuid"),
        ("Address", "name"),
        ("Address", "org_unit_uuid"),
        ("Address", "resolve"),
        ("Address", "type"),
        ("Address", "user_key"),
        ("Address", "uuid"),
        ("Address", "validity"),
        ("Address", "value"),
        ("Address", "value2"),
        ("Address", "visibility_uuid"),
        ("AddressRegistration", "actor"),
        ("AddressRegistration", "actor_object"),
        ("AddressRegistration", "current"),
        ("AddressRegistration", "end"),
        ("AddressRegistration", "model"),
        ("AddressRegistration", "note"),
        ("AddressRegistration", "registration_id"),
        ("AddressRegistration", "start"),
        ("AddressRegistration", "uuid"),
        ("AddressRegistration", "validities"),
        ("AddressResponse", "current"),
        ("AddressResponse", "objects"),
        ("AddressResponse", "registrations"),
        ("AddressResponse", "uuid"),
        ("AddressResponse", "validities"),
        ("AddressResponsePaged", "objects"),
        ("AddressResponsePaged", "page_info"),
        ("AddressResponseRegistration", "actor"),
        ("AddressResponseRegistration", "actor_object"),
        ("AddressResponseRegistration", "current"),
        ("AddressResponseRegistration", "end"),
        ("AddressResponseRegistration", "model"),
        ("AddressResponseRegistration", "note"),
        ("AddressResponseRegistration", "registration_id"),
        ("AddressResponseRegistration", "start"),
        ("AddressResponseRegistration", "uuid"),
        ("AddressResponseRegistration", "validities"),
        ("Association", "association_type_uuid"),
        ("Association", "dynamic_class_uuid"),
        ("Association", "employee_uuid"),
        ("Association", "it_user_uuid"),
        ("Association", "job_function_uuid"),
        ("Association", "org_unit_uuid"),
        ("Association", "primary_uuid"),
        ("Association", "substitute_uuid"),
        ("Association", "trade_union_uuid"),
        ("Association", "type"),
        ("Association", "user_key"),
        ("Association", "uuid"),
        ("Association", "validity"),
        ("AssociationRegistration", "actor"),
        ("AssociationRegistration", "actor_object"),
        ("AssociationRegistration", "current"),
        ("AssociationRegistration", "end"),
        ("AssociationRegistration", "model"),
        ("AssociationRegistration", "note"),
        ("AssociationRegistration", "registration_id"),
        ("AssociationRegistration", "start"),
        ("AssociationRegistration", "uuid"),
        ("AssociationRegistration", "validities"),
        ("AssociationResponse", "current"),
        ("AssociationResponse", "objects"),
        ("AssociationResponse", "registrations"),
        ("AssociationResponse", "uuid"),
        ("AssociationResponse", "validities"),
        ("AssociationResponsePaged", "objects"),
        ("AssociationResponsePaged", "page_info"),
        ("AssociationResponseRegistration", "actor"),
        ("AssociationResponseRegistration", "actor_object"),
        ("AssociationResponseRegistration", "current"),
        ("AssociationResponseRegistration", "end"),
        ("AssociationResponseRegistration", "model"),
        ("AssociationResponseRegistration", "note"),
        ("AssociationResponseRegistration", "registration_id"),
        ("AssociationResponseRegistration", "start"),
        ("AssociationResponseRegistration", "uuid"),
        ("AssociationResponseRegistration", "validities"),
        ("Class", "description"),
        ("Class", "example"),
        ("Class", "facet_uuid"),
        ("Class", "full_name"),
        ("Class", "it_system_uuid"),
        ("Class", "name"),
        ("Class", "org_uuid"),
        ("Class", "owner"),
        ("Class", "parent_uuid"),
        ("Class", "published"),
        ("Class", "scope"),
        ("Class", "type"),
        ("Class", "user_key"),
        ("Class", "uuid"),
        ("Class", "validity"),
        ("ClassRegistration", "actor"),
        ("ClassRegistration", "actor_object"),
        ("ClassRegistration", "current"),
        ("ClassRegistration", "end"),
        ("ClassRegistration", "model"),
        ("ClassRegistration", "note"),
        ("ClassRegistration", "registration_id"),
        ("ClassRegistration", "start"),
        ("ClassRegistration", "uuid"),
        ("ClassRegistration", "validities"),
        ("ClassResponse", "current"),
        ("ClassResponse", "objects"),
        ("ClassResponse", "registrations"),
        ("ClassResponse", "uuid"),
        ("ClassResponse", "validities"),
        ("ClassResponsePaged", "objects"),
        ("ClassResponsePaged", "page_info"),
        ("ClassResponseRegistration", "actor"),
        ("ClassResponseRegistration", "actor_object"),
        ("ClassResponseRegistration", "current"),
        ("ClassResponseRegistration", "end"),
        ("ClassResponseRegistration", "model"),
        ("ClassResponseRegistration", "note"),
        ("ClassResponseRegistration", "registration_id"),
        ("ClassResponseRegistration", "start"),
        ("ClassResponseRegistration", "uuid"),
        ("ClassResponseRegistration", "validities"),
        ("DARAddress", "description"),
        ("DARAddress", "door"),
        ("DARAddress", "floor"),
        ("DARAddress", "house_number"),
        ("DARAddress", "href"),
        ("DARAddress", "latitude"),
        ("DARAddress", "longitude"),
        ("DARAddress", "municipality_code"),
        ("DARAddress", "name"),
        ("DARAddress", "road_code"),
        ("DARAddress", "road_name"),
        ("DARAddress", "streetmap_href"),
        ("DARAddress", "supplementary_city"),
        ("DARAddress", "value"),
        ("DARAddress", "zip_code"),
        ("DARAddress", "zip_code_name"),
        ("DefaultAddress", "value"),
        ("Employee", "cpr_no"),
        ("Employee", "cpr_number"),
        ("Employee", "given_name"),
        ("Employee", "givenname"),
        ("Employee", "name"),
        ("Employee", "nickname"),
        ("Employee", "nickname_given_name"),
        ("Employee", "nickname_givenname"),
        ("Employee", "nickname_surname"),
        ("Employee", "seniority"),
        ("Employee", "surname"),
        ("Employee", "type"),
        ("Employee", "user_key"),
        ("Employee", "uuid"),
        ("Employee", "validity"),
        ("EmployeeResponse", "current"),
        ("EmployeeResponse", "objects"),
        ("EmployeeResponse", "registrations"),
        ("EmployeeResponse", "uuid"),
        ("EmployeeResponse", "validities"),
        ("EmployeeResponsePaged", "objects"),
        ("EmployeeResponsePaged", "page_info"),
        ("EmployeeResponseRegistration", "actor"),
        ("EmployeeResponseRegistration", "actor_object"),
        ("EmployeeResponseRegistration", "current"),
        ("EmployeeResponseRegistration", "end"),
        ("EmployeeResponseRegistration", "model"),
        ("EmployeeResponseRegistration", "note"),
        ("EmployeeResponseRegistration", "registration_id"),
        ("EmployeeResponseRegistration", "start"),
        ("EmployeeResponseRegistration", "uuid"),
        ("EmployeeResponseRegistration", "validities"),
        ("Engagement", "employee_uuid"),
        ("Engagement", "engagement_type_uuid"),
        ("Engagement", "extension_1"),
        ("Engagement", "extension_10"),
        ("Engagement", "extension_2"),
        ("Engagement", "extension_3"),
        ("Engagement", "extension_4"),
        ("Engagement", "extension_5"),
        ("Engagement", "extension_6"),
        ("Engagement", "extension_7"),
        ("Engagement", "extension_8"),
        ("Engagement", "extension_9"),
        ("Engagement", "fraction"),
        ("Engagement", "is_primary"),
        ("Engagement", "job_function_uuid"),
        ("Engagement", "leave_uuid"),
        ("Engagement", "org_unit_uuid"),
        ("Engagement", "primary_uuid"),
        ("Engagement", "type"),
        ("Engagement", "user_key"),
        ("Engagement", "uuid"),
        ("Engagement", "validity"),
        ("EngagementRegistration", "actor"),
        ("EngagementRegistration", "actor_object"),
        ("EngagementRegistration", "current"),
        ("EngagementRegistration", "end"),
        ("EngagementRegistration", "model"),
        ("EngagementRegistration", "note"),
        ("EngagementRegistration", "registration_id"),
        ("EngagementRegistration", "start"),
        ("EngagementRegistration", "uuid"),
        ("EngagementRegistration", "validities"),
        ("EngagementResponse", "current"),
        ("EngagementResponse", "objects"),
        ("EngagementResponse", "registrations"),
        ("EngagementResponse", "uuid"),
        ("EngagementResponse", "validities"),
        ("EngagementResponsePaged", "objects"),
        ("EngagementResponsePaged", "page_info"),
        ("EngagementResponseRegistration", "actor"),
        ("EngagementResponseRegistration", "actor_object"),
        ("EngagementResponseRegistration", "current"),
        ("EngagementResponseRegistration", "end"),
        ("EngagementResponseRegistration", "model"),
        ("EngagementResponseRegistration", "note"),
        ("EngagementResponseRegistration", "registration_id"),
        ("EngagementResponseRegistration", "start"),
        ("EngagementResponseRegistration", "uuid"),
        ("EngagementResponseRegistration", "validities"),
        ("Event", "priority"),
        ("Event", "subject"),
        ("Event", "token"),
        ("Facet", "description"),
        ("Facet", "org_uuid"),
        ("Facet", "parent_uuid"),
        ("Facet", "published"),
        ("Facet", "type"),
        ("Facet", "user_key"),
        ("Facet", "uuid"),
        ("Facet", "validity"),
        ("FacetRegistration", "actor"),
        ("FacetRegistration", "actor_object"),
        ("FacetRegistration", "current"),
        ("FacetRegistration", "end"),
        ("FacetRegistration", "model"),
        ("FacetRegistration", "note"),
        ("FacetRegistration", "registration_id"),
        ("FacetRegistration", "start"),
        ("FacetRegistration", "uuid"),
        ("FacetRegistration", "validities"),
        ("FacetResponse", "current"),
        ("FacetResponse", "objects"),
        ("FacetResponse", "registrations"),
        ("FacetResponse", "uuid"),
        ("FacetResponse", "validities"),
        ("FacetResponsePaged", "objects"),
        ("FacetResponsePaged", "page_info"),
        ("FacetResponseRegistration", "actor"),
        ("FacetResponseRegistration", "actor_object"),
        ("FacetResponseRegistration", "current"),
        ("FacetResponseRegistration", "end"),
        ("FacetResponseRegistration", "model"),
        ("FacetResponseRegistration", "note"),
        ("FacetResponseRegistration", "registration_id"),
        ("FacetResponseRegistration", "start"),
        ("FacetResponseRegistration", "uuid"),
        ("FacetResponseRegistration", "validities"),
        ("File", "base64_contents"),
        ("File", "file_name"),
        ("File", "file_store"),
        ("File", "text_contents"),
        ("FilePaged", "objects"),
        ("FilePaged", "page_info"),
        ("FullEvent", "priority"),
        ("FullEvent", "silenced"),
        ("FullEvent", "subject"),
        ("FullEventPaged", "objects"),
        ("FullEventPaged", "page_info"),
        ("Health", "identifier"),
        ("Health", "status"),
        ("HealthPaged", "objects"),
        ("HealthPaged", "page_info"),
        ("IRegistrationPaged", "objects"),
        ("IRegistrationPaged", "page_info"),
        ("ITSystem", "name"),
        ("ITSystem", "system_type"),
        ("ITSystem", "type"),
        ("ITSystem", "user_key"),
        ("ITSystem", "uuid"),
        ("ITSystem", "validity"),
        ("ITSystemRegistration", "actor"),
        ("ITSystemRegistration", "actor_object"),
        ("ITSystemRegistration", "current"),
        ("ITSystemRegistration", "end"),
        ("ITSystemRegistration", "model"),
        ("ITSystemRegistration", "note"),
        ("ITSystemRegistration", "registration_id"),
        ("ITSystemRegistration", "start"),
        ("ITSystemRegistration", "uuid"),
        ("ITSystemRegistration", "validities"),
        ("ITSystemResponse", "current"),
        ("ITSystemResponse", "objects"),
        ("ITSystemResponse", "registrations"),
        ("ITSystemResponse", "uuid"),
        ("ITSystemResponse", "validities"),
        ("ITSystemResponsePaged", "objects"),
        ("ITSystemResponsePaged", "page_info"),
        ("ITSystemResponseRegistration", "actor"),
        ("ITSystemResponseRegistration", "actor_object"),
        ("ITSystemResponseRegistration", "current"),
        ("ITSystemResponseRegistration", "end"),
        ("ITSystemResponseRegistration", "model"),
        ("ITSystemResponseRegistration", "note"),
        ("ITSystemResponseRegistration", "registration_id"),
        ("ITSystemResponseRegistration", "start"),
        ("ITSystemResponseRegistration", "uuid"),
        ("ITSystemResponseRegistration", "validities"),
        ("ITUser", "binding_type"),
        ("ITUser", "employee_uuid"),
        ("ITUser", "engagement_uuid"),
        ("ITUser", "engagement_uuids"),
        ("ITUser", "external_id"),
        ("ITUser", "itsystem_uuid"),
        ("ITUser", "org_unit_uuid"),
        ("ITUser", "primary_uuid"),
        ("ITUser", "type"),
        ("ITUser", "user_key"),
        ("ITUser", "uuid"),
        ("ITUser", "validity"),
        ("ITUserRegistration", "actor"),
        ("ITUserRegistration", "actor_object"),
        ("ITUserRegistration", "current"),
        ("ITUserRegistration", "end"),
        ("ITUserRegistration", "model"),
        ("ITUserRegistration", "note"),
        ("ITUserRegistration", "registration_id"),
        ("ITUserRegistration", "start"),
        ("ITUserRegistration", "uuid"),
        ("ITUserRegistration", "validities"),
        ("ITUserResponse", "current"),
        ("ITUserResponse", "objects"),
        ("ITUserResponse", "registrations"),
        ("ITUserResponse", "uuid"),
        ("ITUserResponse", "validities"),
        ("ITUserResponsePaged", "objects"),
        ("ITUserResponsePaged", "page_info"),
        ("ITUserResponseRegistration", "actor"),
        ("ITUserResponseRegistration", "actor_object"),
        ("ITUserResponseRegistration", "current"),
        ("ITUserResponseRegistration", "end"),
        ("ITUserResponseRegistration", "model"),
        ("ITUserResponseRegistration", "note"),
        ("ITUserResponseRegistration", "registration_id"),
        ("ITUserResponseRegistration", "start"),
        ("ITUserResponseRegistration", "uuid"),
        ("ITUserResponseRegistration", "validities"),
        ("KLE", "kle_aspect_uuids"),
        ("KLE", "kle_number_uuid"),
        ("KLE", "org_unit_uuid"),
        ("KLE", "type"),
        ("KLE", "user_key"),
        ("KLE", "uuid"),
        ("KLE", "validity"),
        ("KLERegistration", "actor"),
        ("KLERegistration", "actor_object"),
        ("KLERegistration", "current"),
        ("KLERegistration", "end"),
        ("KLERegistration", "model"),
        ("KLERegistration", "note"),
        ("KLERegistration", "registration_id"),
        ("KLERegistration", "start"),
        ("KLERegistration", "uuid"),
        ("KLERegistration", "validities"),
        ("KLEResponse", "current"),
        ("KLEResponse", "objects"),
        ("KLEResponse", "registrations"),
        ("KLEResponse", "uuid"),
        ("KLEResponse", "validities"),
        ("KLEResponsePaged", "objects"),
        ("KLEResponsePaged", "page_info"),
        ("KLEResponseRegistration", "actor"),
        ("KLEResponseRegistration", "actor_object"),
        ("KLEResponseRegistration", "current"),
        ("KLEResponseRegistration", "end"),
        ("KLEResponseRegistration", "model"),
        ("KLEResponseRegistration", "note"),
        ("KLEResponseRegistration", "registration_id"),
        ("KLEResponseRegistration", "start"),
        ("KLEResponseRegistration", "uuid"),
        ("KLEResponseRegistration", "validities"),
        ("Leave", "employee_uuid"),
        ("Leave", "engagement_uuid"),
        ("Leave", "leave_type_uuid"),
        ("Leave", "type"),
        ("Leave", "user_key"),
        ("Leave", "uuid"),
        ("Leave", "validity"),
        ("LeaveRegistration", "actor"),
        ("LeaveRegistration", "actor_object"),
        ("LeaveRegistration", "current"),
        ("LeaveRegistration", "end"),
        ("LeaveRegistration", "model"),
        ("LeaveRegistration", "note"),
        ("LeaveRegistration", "registration_id"),
        ("LeaveRegistration", "start"),
        ("LeaveRegistration", "uuid"),
        ("LeaveRegistration", "validities"),
        ("LeaveResponse", "current"),
        ("LeaveResponse", "objects"),
        ("LeaveResponse", "registrations"),
        ("LeaveResponse", "uuid"),
        ("LeaveResponse", "validities"),
        ("LeaveResponsePaged", "objects"),
        ("LeaveResponsePaged", "page_info"),
        ("LeaveResponseRegistration", "actor"),
        ("LeaveResponseRegistration", "actor_object"),
        ("LeaveResponseRegistration", "current"),
        ("LeaveResponseRegistration", "end"),
        ("LeaveResponseRegistration", "model"),
        ("LeaveResponseRegistration", "note"),
        ("LeaveResponseRegistration", "registration_id"),
        ("LeaveResponseRegistration", "start"),
        ("LeaveResponseRegistration", "uuid"),
        ("LeaveResponseRegistration", "validities"),
        ("Listener", "owner"),
        ("Listener", "routing_key"),
        ("Listener", "user_key"),
        ("Listener", "uuid"),
        ("ListenerPaged", "objects"),
        ("ListenerPaged", "page_info"),
        ("Manager", "employee_uuid"),
        ("Manager", "manager_level_uuid"),
        ("Manager", "manager_type_uuid"),
        ("Manager", "org_unit_uuid"),
        ("Manager", "responsibility_uuids"),
        ("Manager", "type"),
        ("Manager", "user_key"),
        ("Manager", "uuid"),
        ("Manager", "validity"),
        ("ManagerRegistration", "actor"),
        ("ManagerRegistration", "actor_object"),
        ("ManagerRegistration", "current"),
        ("ManagerRegistration", "end"),
        ("ManagerRegistration", "model"),
        ("ManagerRegistration", "note"),
        ("ManagerRegistration", "registration_id"),
        ("ManagerRegistration", "start"),
        ("ManagerRegistration", "uuid"),
        ("ManagerRegistration", "validities"),
        ("ManagerResponse", "current"),
        ("ManagerResponse", "objects"),
        ("ManagerResponse", "registrations"),
        ("ManagerResponse", "uuid"),
        ("ManagerResponse", "validities"),
        ("ManagerResponsePaged", "objects"),
        ("ManagerResponsePaged", "page_info"),
        ("ManagerResponseRegistration", "actor"),
        ("ManagerResponseRegistration", "actor_object"),
        ("ManagerResponseRegistration", "current"),
        ("ManagerResponseRegistration", "end"),
        ("ManagerResponseRegistration", "model"),
        ("ManagerResponseRegistration", "note"),
        ("ManagerResponseRegistration", "registration_id"),
        ("ManagerResponseRegistration", "start"),
        ("ManagerResponseRegistration", "uuid"),
        ("ManagerResponseRegistration", "validities"),
        ("MultifieldAddress", "name"),
        ("MultifieldAddress", "value"),
        ("MultifieldAddress", "value2"),
        ("Myself", "actor"),
        ("Myself", "email"),
        ("Myself", "roles"),
        ("Myself", "username"),
        ("Namespace", "name"),
        ("Namespace", "owner"),
        ("Namespace", "public"),
        ("NamespacePaged", "objects"),
        ("NamespacePaged", "page_info"),
        ("OpenValidity", "from"),
        ("OpenValidity", "to"),
        ("Organisation", "municipality_code"),
        ("Organisation", "name"),
        ("Organisation", "type"),
        ("Organisation", "user_key"),
        ("Organisation", "uuid"),
        ("OrganisationUnit", "name"),
        ("OrganisationUnit", "org_unit_hierarchy"),
        ("OrganisationUnit", "org_unit_level_uuid"),
        ("OrganisationUnit", "parent_uuid"),
        ("OrganisationUnit", "time_planning_uuid"),
        ("OrganisationUnit", "type"),
        ("OrganisationUnit", "unit_type_uuid"),
        ("OrganisationUnit", "user_key"),
        ("OrganisationUnit", "uuid"),
        ("OrganisationUnit", "validity"),
        ("OrganisationUnitRegistration", "actor"),
        ("OrganisationUnitRegistration", "actor_object"),
        ("OrganisationUnitRegistration", "current"),
        ("OrganisationUnitRegistration", "end"),
        ("OrganisationUnitRegistration", "model"),
        ("OrganisationUnitRegistration", "note"),
        ("OrganisationUnitRegistration", "registration_id"),
        ("OrganisationUnitRegistration", "start"),
        ("OrganisationUnitRegistration", "uuid"),
        ("OrganisationUnitRegistration", "validities"),
        ("OrganisationUnitResponse", "current"),
        ("OrganisationUnitResponse", "objects"),
        ("OrganisationUnitResponse", "registrations"),
        ("OrganisationUnitResponse", "uuid"),
        ("OrganisationUnitResponse", "validities"),
        ("OrganisationUnitResponsePaged", "objects"),
        ("OrganisationUnitResponsePaged", "page_info"),
        ("OrganisationUnitResponseRegistration", "actor"),
        ("OrganisationUnitResponseRegistration", "actor_object"),
        ("OrganisationUnitResponseRegistration", "current"),
        ("OrganisationUnitResponseRegistration", "end"),
        ("OrganisationUnitResponseRegistration", "model"),
        ("OrganisationUnitResponseRegistration", "note"),
        ("OrganisationUnitResponseRegistration", "registration_id"),
        ("OrganisationUnitResponseRegistration", "start"),
        ("OrganisationUnitResponseRegistration", "uuid"),
        ("OrganisationUnitResponseRegistration", "validities"),
        ("Owner", "employee_uuid"),
        ("Owner", "org_unit_uuid"),
        ("Owner", "owner_inference_priority"),
        ("Owner", "owner_uuid"),
        ("Owner", "type"),
        ("Owner", "user_key"),
        ("Owner", "uuid"),
        ("Owner", "validity"),
        ("OwnerRegistration", "actor"),
        ("OwnerRegistration", "actor_object"),
        ("OwnerRegistration", "current"),
        ("OwnerRegistration", "end"),
        ("OwnerRegistration", "model"),
        ("OwnerRegistration", "note"),
        ("OwnerRegistration", "registration_id"),
        ("OwnerRegistration", "start"),
        ("OwnerRegistration", "uuid"),
        ("OwnerRegistration", "validities"),
        ("OwnerResponse", "current"),
        ("OwnerResponse", "objects"),
        ("OwnerResponse", "registrations"),
        ("OwnerResponse", "uuid"),
        ("OwnerResponse", "validities"),
        ("OwnerResponsePaged", "objects"),
        ("OwnerResponsePaged", "page_info"),
        ("OwnerResponseRegistration", "actor"),
        ("OwnerResponseRegistration", "actor_object"),
        ("OwnerResponseRegistration", "current"),
        ("OwnerResponseRegistration", "end"),
        ("OwnerResponseRegistration", "model"),
        ("OwnerResponseRegistration", "note"),
        ("OwnerResponseRegistration", "registration_id"),
        ("OwnerResponseRegistration", "start"),
        ("OwnerResponseRegistration", "uuid"),
        ("OwnerResponseRegistration", "validities"),
        ("PageInfo", "next_cursor"),
        ("PersonRegistration", "actor"),
        ("PersonRegistration", "actor_object"),
        ("PersonRegistration", "current"),
        ("PersonRegistration", "end"),
        ("PersonRegistration", "model"),
        ("PersonRegistration", "note"),
        ("PersonRegistration", "registration_id"),
        ("PersonRegistration", "start"),
        ("PersonRegistration", "uuid"),
        ("PersonRegistration", "validities"),
        ("Query", "healths"),
        ("Query", "me"),
        ("Query", "version"),
        ("Registration", "actor"),
        ("Registration", "actor_object"),
        ("Registration", "end"),
        ("Registration", "model"),
        ("Registration", "note"),
        ("Registration", "registration_id"),
        ("Registration", "start"),
        ("Registration", "uuid"),
        ("RegistrationPaged", "objects"),
        ("RegistrationPaged", "page_info"),
        ("RelatedUnit", "org_unit_uuids"),
        ("RelatedUnit", "type"),
        ("RelatedUnit", "user_key"),
        ("RelatedUnit", "uuid"),
        ("RelatedUnit", "validity"),
        ("RelatedUnitRegistration", "actor"),
        ("RelatedUnitRegistration", "actor_object"),
        ("RelatedUnitRegistration", "current"),
        ("RelatedUnitRegistration", "end"),
        ("RelatedUnitRegistration", "model"),
        ("RelatedUnitRegistration", "note"),
        ("RelatedUnitRegistration", "registration_id"),
        ("RelatedUnitRegistration", "start"),
        ("RelatedUnitRegistration", "uuid"),
        ("RelatedUnitRegistration", "validities"),
        ("RelatedUnitResponse", "current"),
        ("RelatedUnitResponse", "objects"),
        ("RelatedUnitResponse", "registrations"),
        ("RelatedUnitResponse", "uuid"),
        ("RelatedUnitResponse", "validities"),
        ("RelatedUnitResponsePaged", "objects"),
        ("RelatedUnitResponsePaged", "page_info"),
        ("RelatedUnitResponseRegistration", "actor"),
        ("RelatedUnitResponseRegistration", "actor_object"),
        ("RelatedUnitResponseRegistration", "current"),
        ("RelatedUnitResponseRegistration", "end"),
        ("RelatedUnitResponseRegistration", "model"),
        ("RelatedUnitResponseRegistration", "note"),
        ("RelatedUnitResponseRegistration", "registration_id"),
        ("RelatedUnitResponseRegistration", "start"),
        ("RelatedUnitResponseRegistration", "uuid"),
        ("RelatedUnitResponseRegistration", "validities"),
        ("RoleBinding", "user_key"),
        ("RoleBinding", "uuid"),
        ("RoleBinding", "validity"),
        ("RoleBindingRegistration", "actor"),
        ("RoleBindingRegistration", "actor_object"),
        ("RoleBindingRegistration", "current"),
        ("RoleBindingRegistration", "end"),
        ("RoleBindingRegistration", "model"),
        ("RoleBindingRegistration", "note"),
        ("RoleBindingRegistration", "registration_id"),
        ("RoleBindingRegistration", "start"),
        ("RoleBindingRegistration", "uuid"),
        ("RoleBindingRegistration", "validities"),
        ("RoleBindingResponse", "current"),
        ("RoleBindingResponse", "objects"),
        ("RoleBindingResponse", "registrations"),
        ("RoleBindingResponse", "uuid"),
        ("RoleBindingResponse", "validities"),
        ("RoleBindingResponsePaged", "objects"),
        ("RoleBindingResponsePaged", "page_info"),
        ("RoleBindingResponseRegistration", "actor"),
        ("RoleBindingResponseRegistration", "actor_object"),
        ("RoleBindingResponseRegistration", "current"),
        ("RoleBindingResponseRegistration", "end"),
        ("RoleBindingResponseRegistration", "model"),
        ("RoleBindingResponseRegistration", "note"),
        ("RoleBindingResponseRegistration", "registration_id"),
        ("RoleBindingResponseRegistration", "start"),
        ("RoleBindingResponseRegistration", "uuid"),
        ("RoleBindingResponseRegistration", "validities"),
        ("SpecialActor", "display_name"),
        ("SpecialActor", "key"),
        ("SpecialActor", "uuid"),
        ("UUIDPaged", "objects"),
        ("UUIDPaged", "page_info"),
        ("UnknownActor", "display_name"),
        ("UnknownActor", "error"),
        ("UnknownActor", "uuid"),
        ("Validity", "from"),
        ("Validity", "to"),
        ("Version", "lora_version"),
        ("Version", "mo_hash"),
        ("Version", "mo_version"),
    }
)

# Map of every schema field to its RBAC requirement. Fields without an
# entry are rejected; a `None` requirement means the field is public.
RBAC_MAP: dict[tuple[str, str], RBACRequirement | None] = {
    **dict.fromkeys(PUBLIC_FIELDS, None),
    ("Address", "address_type"): ("read_class", "class", "read"),
    ("Address", "address_type_response"): ("read_class", "class", "read"),
    ("Address", "employee"): ("read_employee", "employee", "read"),
    ("Address", "engagement"): ("read_engagement", "engagement", "read"),
    ("Address", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("Address", "ituser"): ("read_ituser", "ituser", "read"),
    ("Address", "ituser_response"): ("read_ituser", "ituser", "read"),
    ("Address", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Address", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Address", "person"): ("read_employee", "employee", "read"),
    ("Address", "person_response"): ("read_employee", "employee", "read"),
    ("Address", "visibility"): ("read_class", "class", "read"),
    ("Address", "visibility_response"): ("read_class", "class", "read"),
    ("Association", "association_type"): ("read_class", "class", "read"),
    ("Association", "association_type_response"): ("read_class", "class", "read"),
    ("Association", "dynamic_class"): ("read_class", "class", "read"),
    ("Association", "dynamic_class_response"): ("read_class", "class", "read"),
    ("Association", "employee"): ("read_employee", "employee", "read"),
    ("Association", "it_user"): ("read_ituser", "ituser", "read"),
    ("Association", "it_user_response"): ("read_ituser", "ituser", "read"),
    ("Association", "job_function"): ("read_class", "class", "read"),
    ("Association", "job_function_response"): ("read_class", "class", "read"),
    ("Association", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Association", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Association", "person"): ("read_employee", "employee", "read"),
    ("Association", "person_response"): ("read_employee", "employee", "read"),
    ("Association", "primary"): ("read_class", "class", "read"),
    ("Association", "primary_response"): ("read_class", "class", "read"),
    ("Association", "substitute"): ("read_employee", "employee", "read"),
    ("Association", "substitute_response"): ("read_employee", "employee", "read"),
    ("Association", "trade_union"): ("read_class", "class", "read"),
    ("Association", "trade_union_response"): ("read_class", "class", "read"),
    ("Class", "children"): ("read_class", "class", "read"),
    ("Class", "children_response"): ("read_class", "class", "read"),
    ("Class", "facet"): ("read_facet", "facet", "read"),
    ("Class", "facet_response"): ("read_facet", "facet", "read"),
    ("Class", "it_system"): ("read_itsystem", "itsystem", "read"),
    ("Class", "it_system_response"): ("read_itsystem", "itsystem", "read"),
    ("Class", "parent"): ("read_class", "class", "read"),
    ("Class", "parent_response"): ("read_class", "class", "read"),
    ("Class", "top_level_facet"): ("read_facet", "facet", "read"),
    ("Employee", "addresses"): ("read_address", "address", "read"),
    ("Employee", "addresses_response"): ("read_address", "address", "read"),
    ("Employee", "associations"): ("read_association", "association", "read"),
    ("Employee", "associations_response"): ("read_association", "association", "read"),
    ("Employee", "engagements"): ("read_engagement", "engagement", "read"),
    ("Employee", "engagements_response"): ("read_engagement", "engagement", "read"),
    ("Employee", "itusers"): ("read_ituser", "ituser", "read"),
    ("Employee", "itusers_response"): ("read_ituser", "ituser", "read"),
    ("Employee", "leaves"): ("read_leave", "leave", "read"),
    ("Employee", "leaves_response"): ("read_leave", "leave", "read"),
    ("Employee", "manager_roles"): ("read_manager", "manager", "read"),
    ("Employee", "manager_roles_response"): ("read_manager", "manager", "read"),
    ("Engagement", "addresses_response"): ("read_address", "address", "read"),
    ("Engagement", "employee"): ("read_employee", "employee", "read"),
    ("Engagement", "engagement_type"): ("read_class", "class", "read"),
    ("Engagement", "engagement_type_response"): ("read_class", "class", "read"),
    ("Engagement", "itusers"): ("read_ituser", "ituser", "read"),
    ("Engagement", "itusers_response"): ("read_ituser", "ituser", "read"),
    ("Engagement", "job_function"): ("read_class", "class", "read"),
    ("Engagement", "job_function_response"): ("read_class", "class", "read"),
    ("Engagement", "leave"): ("read_leave", "leave", "read"),
    ("Engagement", "leave_response"): ("read_leave", "leave", "read"),
    ("Engagement", "managers"): ("read_manager", "manager", "read"),
    ("Engagement", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Engagement", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Engagement", "person"): ("read_employee", "employee", "read"),
    ("Engagement", "person_response"): ("read_employee", "employee", "read"),
    ("Engagement", "primary"): ("read_class", "class", "read"),
    ("Engagement", "primary_response"): ("read_class", "class", "read"),
    ("Facet", "children"): ("read_facet", "facet", "read"),
    ("Facet", "children_response"): ("read_facet", "facet", "read"),
    ("Facet", "classes"): ("read_class", "class", "read"),
    ("Facet", "classes_responses"): ("read_class", "class", "read"),
    ("Facet", "parent"): ("read_facet", "facet", "read"),
    ("Facet", "parent_response"): ("read_facet", "facet", "read"),
    ("FullEvent", "listener"): ("read_event_listener", "event_listener", "read"),
    ("ITSystem", "roles"): ("read_class", "class", "read"),
    ("ITSystem", "roles_response"): ("read_class", "class", "read"),
    ("ITUser", "addresses"): ("read_address", "address", "read"),
    ("ITUser", "addresses_response"): ("read_address", "address", "read"),
    ("ITUser", "employee"): ("read_employee", "employee", "read"),
    ("ITUser", "engagement"): ("read_engagement", "engagement", "read"),
    ("ITUser", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("ITUser", "engagements"): ("read_engagement", "engagement", "read"),
    ("ITUser", "engagements_responses"): ("read_engagement", "engagement", "read"),
    ("ITUser", "itsystem"): ("read_itsystem", "itsystem", "read"),
    ("ITUser", "itsystem_response"): ("read_itsystem", "itsystem", "read"),
    ("ITUser", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("ITUser", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("ITUser", "person"): ("read_employee", "employee", "read"),
    ("ITUser", "person_response"): ("read_employee", "employee", "read"),
    ("ITUser", "primary"): ("read_class", "class", "read"),
    ("ITUser", "primary_response"): ("read_class", "class", "read"),
    ("ITUser", "rolebindings"): ("read_rolebinding", "rolebinding", "read"),
    ("ITUser", "rolebindings_response"): ("read_rolebinding", "rolebinding", "read"),
    ("KLE", "kle_aspects"): ("read_class", "class", "read"),
    ("KLE", "kle_aspects_response"): ("read_class", "class", "read"),
    ("KLE", "kle_number"): ("read_class", "class", "read"),
    ("KLE", "kle_number_response"): ("read_class", "class", "read"),
    ("KLE", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("KLE", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Leave", "employee"): ("read_employee", "employee", "read"),
    ("Leave", "engagement"): ("read_engagement", "engagement", "read"),
    ("Leave", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("Leave", "leave_type"): ("read_class", "class", "read"),
    ("Leave", "leave_type_response"): ("read_class", "class", "read"),
    ("Leave", "person"): ("read_employee", "employee", "read"),
    ("Leave", "person_response"): ("read_employee", "employee", "read"),
    ("Listener", "events"): ("read_event", "event", "read"),
    ("Listener", "namespace"): ("read_event_namespace", "event_namespace", "read"),
    ("Manager", "employee"): ("read_employee", "employee", "read"),
    ("Manager", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("Manager", "manager_level"): ("read_class", "class", "read"),
    ("Manager", "manager_level_response"): ("read_class", "class", "read"),
    ("Manager", "manager_type"): ("read_class", "class", "read"),
    ("Manager", "manager_type_response"): ("read_class", "class", "read"),
    ("Manager", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Manager", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Manager", "person"): ("read_employee", "employee", "read"),
    ("Manager", "person_response"): ("read_employee", "employee", "read"),
    ("Manager", "responsibilities"): ("read_class", "class", "read"),
    ("Manager", "responsibilities_response"): ("read_class", "class", "read"),
    ("Mutation", "address_create"): ("create_address", "address", "create"),
    ("Mutation", "address_delete"): ("delete_address", "address", "delete"),
    ("Mutation", "address_refresh"): ("refresh_address", "address", "refresh"),
    ("Mutation", "address_terminate"): ("terminate_address", "address", "terminate"),
    ("Mutation", "address_update"): ("update_address", "address", "update"),
    ("Mutation", "addresses_create"): ("create_address", "address", "create"),
    ("Mutation", "association_create"): ("create_association", "association", "create"),
    ("Mutation", "association_refresh"): (
        "refresh_association",
        "association",
        "refresh",
    ),
    ("Mutation", "association_terminate"): (
        "terminate_association",
        "association",
        "terminate",
    ),
    ("Mutation", "association_update"): ("update_association", "association", "update"),
    ("Mutation", "class_create"): ("create_class", "class", "create"),
    ("Mutation", "class_delete"): ("delete_class", "class", "delete"),
    ("Mutation", "class_refresh"): ("refresh_class", "class", "refresh"),
    ("Mutation", "class_terminate"): ("terminate_class", "class", "terminate"),
    ("Mutation", "class_update"): ("update_class", "class", "update"),
    ("Mutation", "employee_create"): ("create_employee", "employee", "create"),
    ("Mutation", "employee_delete"): ("delete_employee", "employee", "delete"),
    ("Mutation", "employee_refresh"): ("refresh_employee", "employee", "refresh"),
    ("Mutation", "employee_terminate"): ("terminate_employee", "employee", "terminate"),
    ("Mutation", "employee_update"): ("update_employee", "employee", "update"),
    ("Mutation", "engagement_create"): ("create_engagement", "engagement", "create"),
    ("Mutation", "engagement_delete"): ("delete_engagement", "engagement", "delete"),
    ("Mutation", "engagement_refresh"): ("refresh_engagement", "engagement", "refresh"),
    ("Mutation", "engagement_terminate"): (
        "terminate_engagement",
        "engagement",
        "terminate",
    ),
    ("Mutation", "engagement_update"): ("update_engagement", "engagement", "update"),
    ("Mutation", "engagements_create"): ("create_engagement", "engagement", "create"),
    ("Mutation", "engagements_update"): ("update_engagement", "engagement", "update"),
    ("Mutation", "event_acknowledge"): ("acknowledge_event", None, None),
    ("Mutation", "event_listener_declare"): (
        "create_event_listener",
        "event_listener",
        "create",
    ),
    ("Mutation", "event_listener_delete"): (
        "delete_event_listener",
        "event_listener",
        "delete",
    ),
    ("Mutation", "event_namespace_declare"): (
        "create_event_namespace",
        "event_namespace",
        "create",
    ),
    ("Mutation", "event_namespace_delete"): (
        "delete_event_namespace",
        "event_namespace",
        "delete",
    ),
    ("Mutation", "event_rerun"): ("rerun_event", None, None),
    ("Mutation", "event_send"): ("send_event", None, None),
    ("Mutation", "event_silence"): ("silence_event", None, None),
    ("Mutation", "event_unsilence"): ("unsilence_event", None, None),
    ("Mutation", "facet_create"): ("create_facet", "facet", "create"),
    ("Mutation", "facet_delete"): ("delete_facet", "facet", "delete"),
    ("Mutation", "facet_refresh"): ("refresh_facet", "facet", "refresh"),
    ("Mutation", "facet_terminate"): ("terminate_facet", "facet", "terminate"),
    ("Mutation", "facet_update"): ("update_facet", "facet", "update"),
    ("Mutation", "itassociation_create"): (
        "create_association",
        "association",
        "create",
    ),
    ("Mutation", "itassociation_terminate"): (
        "terminate_association",
        "association",
        "terminate",
    ),
    ("Mutation", "itassociation_update"): (
        "update_association",
        "association",
        "update",
    ),
    ("Mutation", "itsystem_create"): ("create_itsystem", "itsystem", "create"),
    ("Mutation", "itsystem_delete"): ("delete_itsystem", "itsystem", "delete"),
    ("Mutation", "itsystem_refresh"): ("refresh_itsystem", "itsystem", "refresh"),
    ("Mutation", "itsystem_terminate"): ("terminate_itsystem", "itsystem", "terminate"),
    ("Mutation", "itsystem_update"): ("update_itsystem", "itsystem", "update"),
    ("Mutation", "ituser_create"): ("create_ituser", "ituser", "create"),
    ("Mutation", "ituser_delete"): ("delete_ituser", "ituser", "delete"),
    ("Mutation", "ituser_refresh"): ("refresh_ituser", "ituser", "refresh"),
    ("Mutation", "ituser_terminate"): ("terminate_ituser", "ituser", "terminate"),
    ("Mutation", "ituser_update"): ("update_ituser", "ituser", "update"),
    ("Mutation", "itusers_create"): ("create_ituser", "ituser", "create"),
    ("Mutation", "kle_create"): ("create_kle", "kle", "create"),
    ("Mutation", "kle_refresh"): ("refresh_kle", "kle", "refresh"),
    ("Mutation", "kle_terminate"): ("terminate_kle", "kle", "terminate"),
    ("Mutation", "kle_update"): ("update_kle", "kle", "update"),
    ("Mutation", "leave_create"): ("create_leave", "leave", "create"),
    ("Mutation", "leave_refresh"): ("refresh_leave", "leave", "refresh"),
    ("Mutation", "leave_terminate"): ("terminate_leave", "leave", "terminate"),
    ("Mutation", "leave_update"): ("update_leave", "leave", "update"),
    ("Mutation", "manager_create"): ("create_manager", "manager", "create"),
    ("Mutation", "manager_delete"): ("delete_manager", "manager", "delete"),
    ("Mutation", "manager_refresh"): ("refresh_manager", "manager", "refresh"),
    ("Mutation", "manager_terminate"): ("terminate_manager", "manager", "terminate"),
    ("Mutation", "manager_update"): ("update_manager", "manager", "update"),
    ("Mutation", "managers_create"): ("create_manager", "manager", "create"),
    ("Mutation", "org_create"): ("create_org", "org", "create"),
    ("Mutation", "org_unit_create"): ("create_org_unit", "org_unit", "create"),
    ("Mutation", "org_unit_delete"): ("delete_org_unit", "org_unit", "delete"),
    ("Mutation", "org_unit_refresh"): ("refresh_org_unit", "org_unit", "refresh"),
    ("Mutation", "org_unit_terminate"): ("terminate_org_unit", "org_unit", "terminate"),
    ("Mutation", "org_unit_update"): ("update_org_unit", "org_unit", "update"),
    ("Mutation", "owner_create"): ("create_owner", "owner", "create"),
    ("Mutation", "owner_refresh"): ("refresh_owner", "owner", "refresh"),
    ("Mutation", "owner_terminate"): ("terminate_owner", "owner", "terminate"),
    ("Mutation", "owner_update"): ("update_owner", "owner", "update"),
    ("Mutation", "related_unit_refresh"): (
        "refresh_related_unit",
        "related_unit",
        "refresh",
    ),
    ("Mutation", "related_units_update"): (
        "update_related_unit",
        "related_unit",
        "update",
    ),
    ("Mutation", "rolebinding_create"): ("create_rolebinding", "rolebinding", "create"),
    ("Mutation", "rolebinding_delete"): ("delete_rolebinding", "rolebinding", "delete"),
    ("Mutation", "rolebinding_refresh"): (
        "refresh_rolebinding",
        "rolebinding",
        "refresh",
    ),
    ("Mutation", "rolebinding_terminate"): (
        "terminate_rolebinding",
        "rolebinding",
        "terminate",
    ),
    ("Mutation", "rolebinding_update"): ("update_rolebinding", "rolebinding", "update"),
    ("Mutation", "rolebindings_create"): (
        "create_rolebinding",
        "rolebinding",
        "create",
    ),
    ("Mutation", "upload_file"): ("upload_files", None, None),
    ("Namespace", "listeners"): ("read_event_namespace", "event_namespace", "read"),
    ("OrganisationUnit", "addresses"): ("read_address", "address", "read"),
    ("OrganisationUnit", "addresses_response"): ("read_address", "address", "read"),
    ("OrganisationUnit", "ancestors"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "associations"): ("read_association", "association", "read"),
    ("OrganisationUnit", "associations_response"): (
        "read_association",
        "association",
        "read",
    ),
    ("OrganisationUnit", "child_count"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "children"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "children_response"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "engagements"): ("read_engagement", "engagement", "read"),
    ("OrganisationUnit", "engagements_response"): (
        "read_engagement",
        "engagement",
        "read",
    ),
    ("OrganisationUnit", "has_children"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "itusers"): ("read_ituser", "ituser", "read"),
    ("OrganisationUnit", "itusers_response"): ("read_ituser", "ituser", "read"),
    ("OrganisationUnit", "kles"): ("read_kle", "kle", "read"),
    ("OrganisationUnit", "kles_response"): ("read_kle", "kle", "read"),
    ("OrganisationUnit", "leaves"): ("read_leave", "leave", "read"),
    ("OrganisationUnit", "leaves_response"): ("read_leave", "leave", "read"),
    ("OrganisationUnit", "managers"): ("read_manager", "manager", "read"),
    ("OrganisationUnit", "managers_response"): ("read_manager", "manager", "read"),
    ("OrganisationUnit", "org_unit_hierarchy_model"): ("read_class", "class", "read"),
    ("OrganisationUnit", "org_unit_level"): ("read_class", "class", "read"),
    ("OrganisationUnit", "owners"): ("read_owner", "owner", "read"),
    ("OrganisationUnit", "parent"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "parent_response"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "related_units"): (
        "read_related_unit",
        "related_unit",
        "read",
    ),
    ("OrganisationUnit", "related_units_response"): (
        "read_related_unit",
        "related_unit",
        "read",
    ),
    ("OrganisationUnit", "root"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "root_response"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "time_planning"): ("read_class", "class", "read"),
    ("OrganisationUnit", "time_planning_response"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_hierarchy_response"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_level_response"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_type"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_type_response"): ("read_class", "class", "read"),
    ("Owner", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Owner", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Owner", "owner"): ("read_owner", "owner", "read"),
    ("Owner", "owner_response"): ("read_owner", "owner", "read"),
    ("Owner", "person"): ("read_employee", "employee", "read"),
    ("Owner", "person_response"): ("read_employee", "employee", "read"),
    ("Query", "access_log"): ("read_accesslog", "accesslog", "read"),
    ("Query", "addresses"): ("read_address", "address", "read"),
    ("Query", "associations"): ("read_association", "association", "read"),
    ("Query", "classes"): ("read_class", "class", "read"),
    ("Query", "employees"): ("read_employee", "employee", "read"),
    ("Query", "engagements"): ("read_engagement", "engagement", "read"),
    ("Query", "event_fetch"): ("fetch_event", None, None),
    ("Query", "event_listeners"): ("read_event_listener", "event_listener", "read"),
    ("Query", "event_namespaces"): ("read_event_namespace", "event_namespace", "read"),
    ("Query", "events"): ("read_event", "event", "read"),
    ("Query", "facets"): ("read_facet", "facet", "read"),
    ("Query", "files"): ("read_file", "file", "read"),
    ("Query", "itsystems"): ("read_itsystem", "itsystem", "read"),
    ("Query", "itusers"): ("read_ituser", "ituser", "read"),
    ("Query", "kles"): ("read_kle", "kle", "read"),
    ("Query", "leaves"): ("read_leave", "leave", "read"),
    ("Query", "managers"): ("read_manager", "manager", "read"),
    ("Query", "org"): ("read_org", "org", "read"),
    ("Query", "org_units"): ("read_org_unit", "org_unit", "read"),
    ("Query", "owners"): ("read_owner", "owner", "read"),
    ("Query", "persons"): ("read_employee", "employee", "read"),
    ("Query", "registrations"): ("read_registration", "registration", "read"),
    ("Query", "related_units"): ("read_related_unit", "related_unit", "read"),
    ("Query", "rolebindings"): ("read_rolebinding", "rolebinding", "read"),
    ("RelatedUnit", "org_units"): ("read_org_unit", "org_unit", "read"),
    ("RelatedUnit", "org_units_response"): ("read_org_unit", "org_unit", "read"),
    ("RoleBinding", "ituser"): ("read_ituser", "ituser", "read"),
    ("RoleBinding", "ituser_response"): ("read_ituser", "ituser", "read"),
    ("RoleBinding", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("RoleBinding", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("RoleBinding", "role"): ("read_class", "class", "read"),
    ("RoleBinding", "role_response"): ("read_class", "class", "read"),
    ("SpecialActor", "event_listeners"): (
        "read_event_listener",
        "event_listener",
        "read",
    ),
    ("SpecialActor", "event_namespaces"): (
        "read_event_namespace",
        "event_namespace",
        "read",
    ),
    ("UnknownActor", "event_listeners"): (
        "read_event_listener",
        "event_listener",
        "read",
    ),
    ("UnknownActor", "event_namespaces"): (
        "read_event_namespace",
        "event_namespace",
        "read",
    ),
}
