# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
    from mora.graphapi.permissions import CollectionPermissionType
    from mora.graphapi.permissions import Collections

# A derived RBAC requirement: (role, collection, permission_type).
# `collection` and `permission_type` are `None` for roles that do not
# follow the `{type}_{collection}` pattern (e.g. `fetch_event`), which also
# means the owner-fallback does not apply.
RBACRequirement = tuple[str, "Collections | None", "CollectionPermissionType | None"]

#: Explicit map of every RBAC-protected field to its requirement tuple.
RBAC_MAP: dict[tuple[str, str], RBACRequirement] = {
    ("Actor", "event_listeners"): ("read_event_listener", "event_listener", "read"),
    ("Actor", "event_namespaces"): ("read_event_namespace", "event_namespace", "read"),
    ("Address", "address_type"): ("read_class", "class", "read"),
    ("Address", "address_type_response"): ("read_class", "class", "read"),
    ("Address", "employee"): ("read_employee", "employee", "read"),
    ("Address", "engagement"): ("read_engagement", "engagement", "read"),
    ("Address", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("Address", "ituser"): ("read_ituser", "ituser", "read"),
    ("Address", "ituser_response"): ("read_ituser", "ituser", "read"),
    ("Address", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Address", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Address", "person"): ("read_employee", "employee", "read"),
    ("Address", "person_response"): ("read_employee", "employee", "read"),
    ("Address", "visibility"): ("read_class", "class", "read"),
    ("Address", "visibility_response"): ("read_class", "class", "read"),
    ("Association", "association_type"): ("read_class", "class", "read"),
    ("Association", "association_type_response"): ("read_class", "class", "read"),
    ("Association", "dynamic_class"): ("read_class", "class", "read"),
    ("Association", "dynamic_class_response"): ("read_class", "class", "read"),
    ("Association", "employee"): ("read_employee", "employee", "read"),
    ("Association", "it_user"): ("read_ituser", "ituser", "read"),
    ("Association", "it_user_response"): ("read_ituser", "ituser", "read"),
    ("Association", "job_function"): ("read_class", "class", "read"),
    ("Association", "job_function_response"): ("read_class", "class", "read"),
    ("Association", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Association", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Association", "person"): ("read_employee", "employee", "read"),
    ("Association", "person_response"): ("read_employee", "employee", "read"),
    ("Association", "primary"): ("read_class", "class", "read"),
    ("Association", "primary_response"): ("read_class", "class", "read"),
    ("Association", "substitute"): ("read_employee", "employee", "read"),
    ("Association", "substitute_response"): ("read_employee", "employee", "read"),
    ("Association", "trade_union"): ("read_class", "class", "read"),
    ("Association", "trade_union_response"): ("read_class", "class", "read"),
    ("Class", "children"): ("read_class", "class", "read"),
    ("Class", "children_response"): ("read_class", "class", "read"),
    ("Class", "facet"): ("read_facet", "facet", "read"),
    ("Class", "facet_response"): ("read_facet", "facet", "read"),
    ("Class", "it_system"): ("read_itsystem", "itsystem", "read"),
    ("Class", "it_system_response"): ("read_itsystem", "itsystem", "read"),
    ("Class", "parent"): ("read_class", "class", "read"),
    ("Class", "parent_response"): ("read_class", "class", "read"),
    ("Class", "top_level_facet"): ("read_facet", "facet", "read"),
    ("Employee", "addresses"): ("read_address", "address", "read"),
    ("Employee", "addresses_response"): ("read_address", "address", "read"),
    ("Employee", "associations"): ("read_association", "association", "read"),
    ("Employee", "associations_response"): ("read_association", "association", "read"),
    ("Employee", "engagements"): ("read_engagement", "engagement", "read"),
    ("Employee", "engagements_response"): ("read_engagement", "engagement", "read"),
    ("Employee", "itusers"): ("read_ituser", "ituser", "read"),
    ("Employee", "itusers_response"): ("read_ituser", "ituser", "read"),
    ("Employee", "leaves"): ("read_leave", "leave", "read"),
    ("Employee", "leaves_response"): ("read_leave", "leave", "read"),
    ("Employee", "manager_roles"): ("read_manager", "manager", "read"),
    ("Employee", "manager_roles_response"): ("read_manager", "manager", "read"),
    ("Engagement", "addresses_response"): ("read_address", "address", "read"),
    ("Engagement", "employee"): ("read_employee", "employee", "read"),
    ("Engagement", "engagement_type"): ("read_class", "class", "read"),
    ("Engagement", "engagement_type_response"): ("read_class", "class", "read"),
    ("Engagement", "itusers"): ("read_ituser", "ituser", "read"),
    ("Engagement", "itusers_response"): ("read_ituser", "ituser", "read"),
    ("Engagement", "job_function"): ("read_class", "class", "read"),
    ("Engagement", "job_function_response"): ("read_class", "class", "read"),
    ("Engagement", "leave"): ("read_leave", "leave", "read"),
    ("Engagement", "leave_response"): ("read_leave", "leave", "read"),
    ("Engagement", "managers"): ("read_manager", "manager", "read"),
    ("Engagement", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Engagement", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Engagement", "person"): ("read_employee", "employee", "read"),
    ("Engagement", "person_response"): ("read_employee", "employee", "read"),
    ("Engagement", "primary"): ("read_class", "class", "read"),
    ("Engagement", "primary_response"): ("read_class", "class", "read"),
    ("Facet", "children"): ("read_facet", "facet", "read"),
    ("Facet", "children_response"): ("read_facet", "facet", "read"),
    ("Facet", "classes"): ("read_class", "class", "read"),
    ("Facet", "classes_responses"): ("read_class", "class", "read"),
    ("Facet", "parent"): ("read_facet", "facet", "read"),
    ("Facet", "parent_response"): ("read_facet", "facet", "read"),
    ("FullEvent", "listener"): ("read_event_listener", "event_listener", "read"),
    ("ITSystem", "roles"): ("read_class", "class", "read"),
    ("ITSystem", "roles_response"): ("read_class", "class", "read"),
    ("ITUser", "addresses"): ("read_address", "address", "read"),
    ("ITUser", "addresses_response"): ("read_address", "address", "read"),
    ("ITUser", "employee"): ("read_employee", "employee", "read"),
    ("ITUser", "engagement"): ("read_engagement", "engagement", "read"),
    ("ITUser", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("ITUser", "engagements"): ("read_engagement", "engagement", "read"),
    ("ITUser", "engagements_responses"): ("read_engagement", "engagement", "read"),
    ("ITUser", "itsystem"): ("read_itsystem", "itsystem", "read"),
    ("ITUser", "itsystem_response"): ("read_itsystem", "itsystem", "read"),
    ("ITUser", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("ITUser", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("ITUser", "person"): ("read_employee", "employee", "read"),
    ("ITUser", "person_response"): ("read_employee", "employee", "read"),
    ("ITUser", "primary"): ("read_class", "class", "read"),
    ("ITUser", "primary_response"): ("read_class", "class", "read"),
    ("ITUser", "rolebindings"): ("read_rolebinding", "rolebinding", "read"),
    ("ITUser", "rolebindings_response"): ("read_rolebinding", "rolebinding", "read"),
    ("KLE", "kle_aspects"): ("read_class", "class", "read"),
    ("KLE", "kle_aspects_response"): ("read_class", "class", "read"),
    ("KLE", "kle_number__v22"): ("read_class", "class", "read"),
    ("KLE", "kle_number__v23"): ("read_class", "class", "read"),
    ("KLE", "kle_number_response"): ("read_class", "class", "read"),
    ("KLE", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("KLE", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Leave", "employee"): ("read_employee", "employee", "read"),
    ("Leave", "engagement"): ("read_engagement", "engagement", "read"),
    ("Leave", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("Leave", "leave_type"): ("read_class", "class", "read"),
    ("Leave", "leave_type_response"): ("read_class", "class", "read"),
    ("Leave", "person"): ("read_employee", "employee", "read"),
    ("Leave", "person_response"): ("read_employee", "employee", "read"),
    ("Listener", "events"): ("read_event", "event", "read"),
    ("Listener", "namespace"): ("read_event_namespace", "event_namespace", "read"),
    ("Manager", "employee"): ("read_employee", "employee", "read"),
    ("Manager", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("Manager", "manager_level"): ("read_class", "class", "read"),
    ("Manager", "manager_level_response"): ("read_class", "class", "read"),
    ("Manager", "manager_type"): ("read_class", "class", "read"),
    ("Manager", "manager_type_response"): ("read_class", "class", "read"),
    ("Manager", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Manager", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Manager", "person"): ("read_employee", "employee", "read"),
    ("Manager", "person_response"): ("read_employee", "employee", "read"),
    ("Manager", "responsibilities"): ("read_class", "class", "read"),
    ("Manager", "responsibilities_response"): ("read_class", "class", "read"),
    ("Mutation", "address_create"): ("create_address", "address", "create"),
    ("Mutation", "address_delete"): ("delete_address", "address", "delete"),
    ("Mutation", "address_refresh"): ("refresh_address", "address", "refresh"),
    ("Mutation", "address_terminate"): ("terminate_address", "address", "terminate"),
    ("Mutation", "address_update"): ("update_address", "address", "update"),
    ("Mutation", "addresses_create"): ("create_address", "address", "create"),
    ("Mutation", "association_create"): ("create_association", "association", "create"),
    ("Mutation", "association_refresh"): (
        "refresh_association",
        "association",
        "refresh",
    ),
    ("Mutation", "association_terminate"): (
        "terminate_association",
        "association",
        "terminate",
    ),
    ("Mutation", "association_update"): ("update_association", "association", "update"),
    ("Mutation", "class_create"): ("create_class", "class", "create"),
    ("Mutation", "class_delete"): ("delete_class", "class", "delete"),
    ("Mutation", "class_refresh"): ("refresh_class", "class", "refresh"),
    ("Mutation", "class_terminate"): ("terminate_class", "class", "terminate"),
    ("Mutation", "class_update"): ("update_class", "class", "update"),
    ("Mutation", "employee_create"): ("create_employee", "employee", "create"),
    ("Mutation", "employee_delete"): ("delete_employee", "employee", "delete"),
    ("Mutation", "employee_refresh"): ("refresh_employee", "employee", "refresh"),
    ("Mutation", "employee_terminate"): ("terminate_employee", "employee", "terminate"),
    ("Mutation", "employee_update"): ("update_employee", "employee", "update"),
    ("Mutation", "engagement_create"): ("create_engagement", "engagement", "create"),
    ("Mutation", "engagement_delete"): ("delete_engagement", "engagement", "delete"),
    ("Mutation", "engagement_refresh"): ("refresh_engagement", "engagement", "refresh"),
    ("Mutation", "engagement_terminate"): (
        "terminate_engagement",
        "engagement",
        "terminate",
    ),
    ("Mutation", "engagement_update"): ("update_engagement", "engagement", "update"),
    ("Mutation", "engagements_create"): ("create_engagement", "engagement", "create"),
    ("Mutation", "engagements_update"): ("update_engagement", "engagement", "update"),
    ("Mutation", "event_acknowledge"): ("acknowledge_event", None, None),
    ("Mutation", "event_listener_declare"): (
        "create_event_listener",
        "event_listener",
        "create",
    ),
    ("Mutation", "event_listener_delete"): (
        "delete_event_listener",
        "event_listener",
        "delete",
    ),
    ("Mutation", "event_namespace_declare"): (
        "create_event_namespace",
        "event_namespace",
        "create",
    ),
    ("Mutation", "event_namespace_delete"): (
        "delete_event_namespace",
        "event_namespace",
        "delete",
    ),
    ("Mutation", "event_rerun"): ("rerun_event", None, None),
    ("Mutation", "event_send"): ("send_event", None, None),
    ("Mutation", "event_silence"): ("silence_event", None, None),
    ("Mutation", "event_unsilence"): ("unsilence_event", None, None),
    ("Mutation", "facet_create"): ("create_facet", "facet", "create"),
    ("Mutation", "facet_delete"): ("delete_facet", "facet", "delete"),
    ("Mutation", "facet_refresh"): ("refresh_facet", "facet", "refresh"),
    ("Mutation", "facet_terminate"): ("terminate_facet", "facet", "terminate"),
    ("Mutation", "facet_update"): ("update_facet", "facet", "update"),
    ("Mutation", "itassociation_create"): (
        "create_association",
        "association",
        "create",
    ),
    ("Mutation", "itassociation_terminate"): (
        "terminate_association",
        "association",
        "terminate",
    ),
    ("Mutation", "itassociation_update"): (
        "update_association",
        "association",
        "update",
    ),
    ("Mutation", "itsystem_create"): ("create_itsystem", "itsystem", "create"),
    ("Mutation", "itsystem_delete"): ("delete_itsystem", "itsystem", "delete"),
    ("Mutation", "itsystem_refresh"): ("refresh_itsystem", "itsystem", "refresh"),
    ("Mutation", "itsystem_terminate"): ("terminate_itsystem", "itsystem", "terminate"),
    ("Mutation", "itsystem_update"): ("update_itsystem", "itsystem", "update"),
    ("Mutation", "ituser_create"): ("create_ituser", "ituser", "create"),
    ("Mutation", "ituser_delete"): ("delete_ituser", "ituser", "delete"),
    ("Mutation", "ituser_refresh"): ("refresh_ituser", "ituser", "refresh"),
    ("Mutation", "ituser_terminate"): ("terminate_ituser", "ituser", "terminate"),
    ("Mutation", "ituser_update"): ("update_ituser", "ituser", "update"),
    ("Mutation", "itusers_create"): ("create_ituser", "ituser", "create"),
    ("Mutation", "kle_create"): ("create_kle", "kle", "create"),
    ("Mutation", "kle_refresh"): ("refresh_kle", "kle", "refresh"),
    ("Mutation", "kle_terminate"): ("terminate_kle", "kle", "terminate"),
    ("Mutation", "kle_update"): ("update_kle", "kle", "update"),
    ("Mutation", "leave_create"): ("create_leave", "leave", "create"),
    ("Mutation", "leave_refresh"): ("refresh_leave", "leave", "refresh"),
    ("Mutation", "leave_terminate"): ("terminate_leave", "leave", "terminate"),
    ("Mutation", "leave_update"): ("update_leave", "leave", "update"),
    ("Mutation", "manager_create"): ("create_manager", "manager", "create"),
    ("Mutation", "manager_refresh"): ("refresh_manager", "manager", "refresh"),
    ("Mutation", "manager_terminate"): ("terminate_manager", "manager", "terminate"),
    ("Mutation", "manager_update"): ("update_manager", "manager", "update"),
    ("Mutation", "managers_create"): ("create_manager", "manager", "create"),
    ("Mutation", "org_create"): ("create_org", "org", "create"),
    ("Mutation", "org_unit_create"): ("create_org_unit", "org_unit", "create"),
    ("Mutation", "org_unit_delete"): ("delete_org_unit", "org_unit", "delete"),
    ("Mutation", "org_unit_refresh"): ("refresh_org_unit", "org_unit", "refresh"),
    ("Mutation", "org_unit_terminate"): ("terminate_org_unit", "org_unit", "terminate"),
    ("Mutation", "org_unit_update"): ("update_org_unit", "org_unit", "update"),
    ("Mutation", "owner_create"): ("create_owner", "owner", "create"),
    ("Mutation", "owner_refresh"): ("refresh_owner", "owner", "refresh"),
    ("Mutation", "owner_terminate"): ("terminate_owner", "owner", "terminate"),
    ("Mutation", "owner_update"): ("update_owner", "owner", "update"),
    ("Mutation", "related_unit_refresh"): (
        "refresh_related_unit",
        "related_unit",
        "refresh",
    ),
    ("Mutation", "related_units_update"): (
        "update_related_unit",
        "related_unit",
        "update",
    ),
    ("Mutation", "rolebinding_create"): ("create_rolebinding", "rolebinding", "create"),
    ("Mutation", "rolebinding_delete"): ("delete_rolebinding", "rolebinding", "delete"),
    ("Mutation", "rolebinding_refresh"): (
        "refresh_rolebinding",
        "rolebinding",
        "refresh",
    ),
    ("Mutation", "rolebinding_terminate"): (
        "terminate_rolebinding",
        "rolebinding",
        "terminate",
    ),
    ("Mutation", "rolebinding_update"): ("update_rolebinding", "rolebinding", "update"),
    ("Mutation", "rolebindings_create"): (
        "create_rolebinding",
        "rolebinding",
        "create",
    ),
    ("Mutation", "upload_file"): ("upload_files", None, None),
    # NB: Namespace.listeners checks read_event_namespace (not read_event_listener);
    # this preserves the original per-field permission_classes behaviour.
    ("Namespace", "listeners"): ("read_event_namespace", "event_namespace", "read"),
    ("OrganisationUnit", "addresses"): ("read_address", "address", "read"),
    ("OrganisationUnit", "addresses_response"): ("read_address", "address", "read"),
    ("OrganisationUnit", "ancestors"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "associations"): ("read_association", "association", "read"),
    ("OrganisationUnit", "associations_response"): (
        "read_association",
        "association",
        "read",
    ),
    ("OrganisationUnit", "child_count"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "children"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "children_response"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "engagements"): ("read_engagement", "engagement", "read"),
    ("OrganisationUnit", "engagements_response"): (
        "read_engagement",
        "engagement",
        "read",
    ),
    ("OrganisationUnit", "has_children"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "itusers"): ("read_ituser", "ituser", "read"),
    ("OrganisationUnit", "itusers_response"): ("read_ituser", "ituser", "read"),
    ("OrganisationUnit", "kles"): ("read_kle", "kle", "read"),
    ("OrganisationUnit", "kles_response"): ("read_kle", "kle", "read"),
    ("OrganisationUnit", "leaves"): ("read_leave", "leave", "read"),
    ("OrganisationUnit", "leaves_response"): ("read_leave", "leave", "read"),
    ("OrganisationUnit", "managers"): ("read_manager", "manager", "read"),
    ("OrganisationUnit", "managers__v23"): ("read_manager", "manager", "read"),
    ("OrganisationUnit", "managers_response"): ("read_manager", "manager", "read"),
    ("OrganisationUnit", "org_unit_hierarchy_model"): ("read_class", "class", "read"),
    ("OrganisationUnit", "org_unit_level"): ("read_class", "class", "read"),
    ("OrganisationUnit", "owners"): ("read_owner", "owner", "read"),
    ("OrganisationUnit", "parent"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "parent_response"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "related_units"): (
        "read_related_unit",
        "related_unit",
        "read",
    ),
    ("OrganisationUnit", "related_units_response"): (
        "read_related_unit",
        "related_unit",
        "read",
    ),
    ("OrganisationUnit", "root"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "root_response"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "time_planning"): ("read_class", "class", "read"),
    ("OrganisationUnit", "time_planning_response"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_hierarchy_response"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_level_response"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_type"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_type_response"): ("read_class", "class", "read"),
    ("Owner", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Owner", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Owner", "owner"): ("read_owner", "owner", "read"),
    ("Owner", "owner_response"): ("read_owner", "owner", "read"),
    ("Owner", "person"): ("read_employee", "employee", "read"),
    ("Owner", "person_response"): ("read_employee", "employee", "read"),
    ("Query", "access_log"): ("read_accesslog", "accesslog", "read"),
    ("Query", "addresses"): ("read_address", "address", "read"),
    ("Query", "associations"): ("read_association", "association", "read"),
    ("Query", "classes"): ("read_class", "class", "read"),
    ("Query", "employees"): ("read_employee", "employee", "read"),
    ("Query", "engagements"): ("read_engagement", "engagement", "read"),
    ("Query", "event_fetch"): ("fetch_event", None, None),
    ("Query", "event_listeners"): ("read_event_listener", "event_listener", "read"),
    ("Query", "event_namespaces"): ("read_event_namespace", "event_namespace", "read"),
    ("Query", "events"): ("read_event", "event", "read"),
    ("Query", "facets"): ("read_facet", "facet", "read"),
    ("Query", "files"): ("read_file", "file", "read"),
    ("Query", "itsystems"): ("read_itsystem", "itsystem", "read"),
    ("Query", "itusers"): ("read_ituser", "ituser", "read"),
    ("Query", "kles"): ("read_kle", "kle", "read"),
    ("Query", "leaves"): ("read_leave", "leave", "read"),
    ("Query", "managers"): ("read_manager", "manager", "read"),
    ("Query", "org"): ("read_org", "org", "read"),
    ("Query", "org_units"): ("read_org_unit", "org_unit", "read"),
    ("Query", "owners"): ("read_owner", "owner", "read"),
    ("Query", "persons"): ("read_employee", "employee", "read"),
    ("Query", "registrations__v25"): ("read_registration", "registration", "read"),
    ("Query", "registrations__v26"): ("read_registration", "registration", "read"),
    ("Query", "related_units"): ("read_related_unit", "related_unit", "read"),
    ("Query", "rolebindings"): ("read_rolebinding", "rolebinding", "read"),
    ("RelatedUnit", "org_units"): ("read_org_unit", "org_unit", "read"),
    ("RelatedUnit", "org_units_response"): ("read_org_unit", "org_unit", "read"),
    ("RoleBinding", "ituser"): ("read_ituser", "ituser", "read"),
    ("RoleBinding", "ituser_response"): ("read_ituser", "ituser", "read"),
    ("RoleBinding", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("RoleBinding", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("RoleBinding", "role"): ("read_class", "class", "read"),
    ("RoleBinding", "role_response"): ("read_class", "class", "read"),
}
