# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
    from mora.graphapi.permissions import CollectionPermissionType
    from mora.graphapi.permissions import Collections

# A derived RBAC requirement: (role, collection, permission_type).
# `collection` and `permission_type` are `None` for roles that do not
# follow the `{type}_{collection}` pattern (e.g. `fetch_event`), which also
# means the owner-fallback does not apply.
RBACRequirement = tuple[str, "Collections | None", "CollectionPermissionType | None"]

# Map of every schema field to its RBAC requirement. Fields without an
# entry are rejected; a `None` requirement means the field is public.
RBAC_MAP: dict[tuple[str, str], RBACRequirement | None] = {
    ("AccessLog", "actor"): None,
    ("AccessLog", "actor_object"): None,
    ("AccessLog", "id"): None,
    ("AccessLog", "model"): None,
    ("AccessLog", "time"): None,
    ("AccessLog", "uuids"): None,
    ("AccessLogPaged", "objects"): None,
    ("AccessLogPaged", "page_info"): None,
    ("Address", "address_type"): ("read_class", "class", "read"),
    ("Address", "address_type_response"): ("read_class", "class", "read"),
    ("Address", "address_type_uuid"): None,
    ("Address", "employee"): ("read_employee", "employee", "read"),
    ("Address", "employee_uuid"): None,
    ("Address", "engagement"): ("read_engagement", "engagement", "read"),
    ("Address", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("Address", "engagement_uuid"): None,
    ("Address", "href"): None,
    ("Address", "ituser"): ("read_ituser", "ituser", "read"),
    ("Address", "ituser_response"): ("read_ituser", "ituser", "read"),
    ("Address", "ituser_uuid"): None,
    ("Address", "name"): None,
    ("Address", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Address", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Address", "org_unit_uuid"): None,
    ("Address", "person"): ("read_employee", "employee", "read"),
    ("Address", "person_response"): ("read_employee", "employee", "read"),
    ("Address", "resolve"): None,
    ("Address", "type"): None,
    ("Address", "user_key"): None,
    ("Address", "uuid"): None,
    ("Address", "validity"): None,
    ("Address", "value"): None,
    ("Address", "value2"): None,
    ("Address", "visibility"): ("read_class", "class", "read"),
    ("Address", "visibility_response"): ("read_class", "class", "read"),
    ("Address", "visibility_uuid"): None,
    ("AddressRegistration", "actor"): None,
    ("AddressRegistration", "actor_object"): None,
    ("AddressRegistration", "current"): None,
    ("AddressRegistration", "end"): None,
    ("AddressRegistration", "model"): None,
    ("AddressRegistration", "note"): None,
    ("AddressRegistration", "registration_id"): None,
    ("AddressRegistration", "start"): None,
    ("AddressRegistration", "uuid"): None,
    ("AddressRegistration", "validities"): None,
    ("AddressResponse", "current"): None,
    ("AddressResponse", "objects"): None,
    ("AddressResponse", "registrations"): None,
    ("AddressResponse", "uuid"): None,
    ("AddressResponse", "validities"): None,
    ("AddressResponsePaged", "objects"): None,
    ("AddressResponsePaged", "page_info"): None,
    ("AddressResponseRegistration", "actor"): None,
    ("AddressResponseRegistration", "actor_object"): None,
    ("AddressResponseRegistration", "current"): None,
    ("AddressResponseRegistration", "end"): None,
    ("AddressResponseRegistration", "model"): None,
    ("AddressResponseRegistration", "note"): None,
    ("AddressResponseRegistration", "registration_id"): None,
    ("AddressResponseRegistration", "start"): None,
    ("AddressResponseRegistration", "uuid"): None,
    ("AddressResponseRegistration", "validities"): None,
    ("Association", "association_type"): ("read_class", "class", "read"),
    ("Association", "association_type_response"): ("read_class", "class", "read"),
    ("Association", "association_type_uuid"): None,
    ("Association", "dynamic_class"): ("read_class", "class", "read"),
    ("Association", "dynamic_class_response"): ("read_class", "class", "read"),
    ("Association", "dynamic_class_uuid"): None,
    ("Association", "employee"): ("read_employee", "employee", "read"),
    ("Association", "employee_uuid"): None,
    ("Association", "it_user"): ("read_ituser", "ituser", "read"),
    ("Association", "it_user_response"): ("read_ituser", "ituser", "read"),
    ("Association", "it_user_uuid"): None,
    ("Association", "job_function"): ("read_class", "class", "read"),
    ("Association", "job_function_response"): ("read_class", "class", "read"),
    ("Association", "job_function_uuid"): None,
    ("Association", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Association", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Association", "org_unit_uuid"): None,
    ("Association", "person"): ("read_employee", "employee", "read"),
    ("Association", "person_response"): ("read_employee", "employee", "read"),
    ("Association", "primary"): ("read_class", "class", "read"),
    ("Association", "primary_response"): ("read_class", "class", "read"),
    ("Association", "primary_uuid"): None,
    ("Association", "substitute"): ("read_employee", "employee", "read"),
    ("Association", "substitute_response"): ("read_employee", "employee", "read"),
    ("Association", "substitute_uuid"): None,
    ("Association", "trade_union"): ("read_class", "class", "read"),
    ("Association", "trade_union_response"): ("read_class", "class", "read"),
    ("Association", "trade_union_uuid"): None,
    ("Association", "type"): None,
    ("Association", "user_key"): None,
    ("Association", "uuid"): None,
    ("Association", "validity"): None,
    ("AssociationRegistration", "actor"): None,
    ("AssociationRegistration", "actor_object"): None,
    ("AssociationRegistration", "current"): None,
    ("AssociationRegistration", "end"): None,
    ("AssociationRegistration", "model"): None,
    ("AssociationRegistration", "note"): None,
    ("AssociationRegistration", "registration_id"): None,
    ("AssociationRegistration", "start"): None,
    ("AssociationRegistration", "uuid"): None,
    ("AssociationRegistration", "validities"): None,
    ("AssociationResponse", "current"): None,
    ("AssociationResponse", "objects"): None,
    ("AssociationResponse", "registrations"): None,
    ("AssociationResponse", "uuid"): None,
    ("AssociationResponse", "validities"): None,
    ("AssociationResponsePaged", "objects"): None,
    ("AssociationResponsePaged", "page_info"): None,
    ("AssociationResponseRegistration", "actor"): None,
    ("AssociationResponseRegistration", "actor_object"): None,
    ("AssociationResponseRegistration", "current"): None,
    ("AssociationResponseRegistration", "end"): None,
    ("AssociationResponseRegistration", "model"): None,
    ("AssociationResponseRegistration", "note"): None,
    ("AssociationResponseRegistration", "registration_id"): None,
    ("AssociationResponseRegistration", "start"): None,
    ("AssociationResponseRegistration", "uuid"): None,
    ("AssociationResponseRegistration", "validities"): None,
    ("Class", "children"): ("read_class", "class", "read"),
    ("Class", "children_response"): ("read_class", "class", "read"),
    ("Class", "description"): None,
    ("Class", "example"): None,
    ("Class", "facet"): ("read_facet", "facet", "read"),
    ("Class", "facet_response"): ("read_facet", "facet", "read"),
    ("Class", "facet_uuid"): None,
    ("Class", "full_name"): None,
    ("Class", "it_system"): ("read_itsystem", "itsystem", "read"),
    ("Class", "it_system_response"): ("read_itsystem", "itsystem", "read"),
    ("Class", "it_system_uuid"): None,
    ("Class", "name"): None,
    ("Class", "org_uuid"): None,
    ("Class", "owner"): None,
    ("Class", "parent"): ("read_class", "class", "read"),
    ("Class", "parent_response"): ("read_class", "class", "read"),
    ("Class", "parent_uuid"): None,
    ("Class", "published"): None,
    ("Class", "scope"): None,
    ("Class", "top_level_facet"): ("read_facet", "facet", "read"),
    ("Class", "type"): None,
    ("Class", "user_key"): None,
    ("Class", "uuid"): None,
    ("Class", "validity"): None,
    ("ClassRegistration", "actor"): None,
    ("ClassRegistration", "actor_object"): None,
    ("ClassRegistration", "current"): None,
    ("ClassRegistration", "end"): None,
    ("ClassRegistration", "model"): None,
    ("ClassRegistration", "note"): None,
    ("ClassRegistration", "registration_id"): None,
    ("ClassRegistration", "start"): None,
    ("ClassRegistration", "uuid"): None,
    ("ClassRegistration", "validities"): None,
    ("ClassResponse", "current"): None,
    ("ClassResponse", "objects"): None,
    ("ClassResponse", "registrations"): None,
    ("ClassResponse", "uuid"): None,
    ("ClassResponse", "validities"): None,
    ("ClassResponsePaged", "objects"): None,
    ("ClassResponsePaged", "page_info"): None,
    ("ClassResponseRegistration", "actor"): None,
    ("ClassResponseRegistration", "actor_object"): None,
    ("ClassResponseRegistration", "current"): None,
    ("ClassResponseRegistration", "end"): None,
    ("ClassResponseRegistration", "model"): None,
    ("ClassResponseRegistration", "note"): None,
    ("ClassResponseRegistration", "registration_id"): None,
    ("ClassResponseRegistration", "start"): None,
    ("ClassResponseRegistration", "uuid"): None,
    ("ClassResponseRegistration", "validities"): None,
    ("DARAddress", "description"): None,
    ("DARAddress", "door"): None,
    ("DARAddress", "floor"): None,
    ("DARAddress", "house_number"): None,
    ("DARAddress", "href"): None,
    ("DARAddress", "latitude"): None,
    ("DARAddress", "longitude"): None,
    ("DARAddress", "municipality_code"): None,
    ("DARAddress", "name"): None,
    ("DARAddress", "road_code"): None,
    ("DARAddress", "road_name"): None,
    ("DARAddress", "streetmap_href"): None,
    ("DARAddress", "supplementary_city"): None,
    ("DARAddress", "value"): None,
    ("DARAddress", "zip_code"): None,
    ("DARAddress", "zip_code_name"): None,
    ("DefaultAddress", "value"): None,
    ("Employee", "addresses"): ("read_address", "address", "read"),
    ("Employee", "addresses_response"): ("read_address", "address", "read"),
    ("Employee", "associations"): ("read_association", "association", "read"),
    ("Employee", "associations_response"): ("read_association", "association", "read"),
    ("Employee", "cpr_no"): None,
    ("Employee", "cpr_number"): None,
    ("Employee", "engagements"): ("read_engagement", "engagement", "read"),
    ("Employee", "engagements_response"): ("read_engagement", "engagement", "read"),
    ("Employee", "given_name"): None,
    ("Employee", "givenname"): None,
    ("Employee", "itusers"): ("read_ituser", "ituser", "read"),
    ("Employee", "itusers_response"): ("read_ituser", "ituser", "read"),
    ("Employee", "leaves"): ("read_leave", "leave", "read"),
    ("Employee", "leaves_response"): ("read_leave", "leave", "read"),
    ("Employee", "manager_roles"): ("read_manager", "manager", "read"),
    ("Employee", "manager_roles_response"): ("read_manager", "manager", "read"),
    ("Employee", "name"): None,
    ("Employee", "nickname"): None,
    ("Employee", "nickname_given_name"): None,
    ("Employee", "nickname_givenname"): None,
    ("Employee", "nickname_surname"): None,
    ("Employee", "seniority"): None,
    ("Employee", "surname"): None,
    ("Employee", "type"): None,
    ("Employee", "user_key"): None,
    ("Employee", "uuid"): None,
    ("Employee", "validity"): None,
    ("EmployeeResponse", "current"): None,
    ("EmployeeResponse", "objects"): None,
    ("EmployeeResponse", "registrations"): None,
    ("EmployeeResponse", "uuid"): None,
    ("EmployeeResponse", "validities"): None,
    ("EmployeeResponsePaged", "objects"): None,
    ("EmployeeResponsePaged", "page_info"): None,
    ("EmployeeResponseRegistration", "actor"): None,
    ("EmployeeResponseRegistration", "actor_object"): None,
    ("EmployeeResponseRegistration", "current"): None,
    ("EmployeeResponseRegistration", "end"): None,
    ("EmployeeResponseRegistration", "model"): None,
    ("EmployeeResponseRegistration", "note"): None,
    ("EmployeeResponseRegistration", "registration_id"): None,
    ("EmployeeResponseRegistration", "start"): None,
    ("EmployeeResponseRegistration", "uuid"): None,
    ("EmployeeResponseRegistration", "validities"): None,
    ("Engagement", "addresses_response"): ("read_address", "address", "read"),
    ("Engagement", "employee"): ("read_employee", "employee", "read"),
    ("Engagement", "employee_uuid"): None,
    ("Engagement", "engagement_type"): ("read_class", "class", "read"),
    ("Engagement", "engagement_type_response"): ("read_class", "class", "read"),
    ("Engagement", "engagement_type_uuid"): None,
    ("Engagement", "extension_1"): None,
    ("Engagement", "extension_10"): None,
    ("Engagement", "extension_2"): None,
    ("Engagement", "extension_3"): None,
    ("Engagement", "extension_4"): None,
    ("Engagement", "extension_5"): None,
    ("Engagement", "extension_6"): None,
    ("Engagement", "extension_7"): None,
    ("Engagement", "extension_8"): None,
    ("Engagement", "extension_9"): None,
    ("Engagement", "fraction"): None,
    ("Engagement", "is_primary"): None,
    ("Engagement", "itusers"): ("read_ituser", "ituser", "read"),
    ("Engagement", "itusers_response"): ("read_ituser", "ituser", "read"),
    ("Engagement", "job_function"): ("read_class", "class", "read"),
    ("Engagement", "job_function_response"): ("read_class", "class", "read"),
    ("Engagement", "job_function_uuid"): None,
    ("Engagement", "leave"): ("read_leave", "leave", "read"),
    ("Engagement", "leave_response"): ("read_leave", "leave", "read"),
    ("Engagement", "leave_uuid"): None,
    ("Engagement", "managers"): ("read_manager", "manager", "read"),
    ("Engagement", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Engagement", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Engagement", "org_unit_uuid"): None,
    ("Engagement", "person"): ("read_employee", "employee", "read"),
    ("Engagement", "person_response"): ("read_employee", "employee", "read"),
    ("Engagement", "primary"): ("read_class", "class", "read"),
    ("Engagement", "primary_response"): ("read_class", "class", "read"),
    ("Engagement", "primary_uuid"): None,
    ("Engagement", "type"): None,
    ("Engagement", "user_key"): None,
    ("Engagement", "uuid"): None,
    ("Engagement", "validity"): None,
    ("EngagementRegistration", "actor"): None,
    ("EngagementRegistration", "actor_object"): None,
    ("EngagementRegistration", "current"): None,
    ("EngagementRegistration", "end"): None,
    ("EngagementRegistration", "model"): None,
    ("EngagementRegistration", "note"): None,
    ("EngagementRegistration", "registration_id"): None,
    ("EngagementRegistration", "start"): None,
    ("EngagementRegistration", "uuid"): None,
    ("EngagementRegistration", "validities"): None,
    ("EngagementResponse", "current"): None,
    ("EngagementResponse", "objects"): None,
    ("EngagementResponse", "registrations"): None,
    ("EngagementResponse", "uuid"): None,
    ("EngagementResponse", "validities"): None,
    ("EngagementResponsePaged", "objects"): None,
    ("EngagementResponsePaged", "page_info"): None,
    ("EngagementResponseRegistration", "actor"): None,
    ("EngagementResponseRegistration", "actor_object"): None,
    ("EngagementResponseRegistration", "current"): None,
    ("EngagementResponseRegistration", "end"): None,
    ("EngagementResponseRegistration", "model"): None,
    ("EngagementResponseRegistration", "note"): None,
    ("EngagementResponseRegistration", "registration_id"): None,
    ("EngagementResponseRegistration", "start"): None,
    ("EngagementResponseRegistration", "uuid"): None,
    ("EngagementResponseRegistration", "validities"): None,
    ("Event", "priority"): None,
    ("Event", "subject"): None,
    ("Event", "token"): None,
    ("Facet", "children"): ("read_facet", "facet", "read"),
    ("Facet", "children_response"): ("read_facet", "facet", "read"),
    ("Facet", "classes"): ("read_class", "class", "read"),
    ("Facet", "classes_responses"): ("read_class", "class", "read"),
    ("Facet", "description"): None,
    ("Facet", "org_uuid"): None,
    ("Facet", "parent"): ("read_facet", "facet", "read"),
    ("Facet", "parent_response"): ("read_facet", "facet", "read"),
    ("Facet", "parent_uuid"): None,
    ("Facet", "published"): None,
    ("Facet", "type"): None,
    ("Facet", "user_key"): None,
    ("Facet", "uuid"): None,
    ("Facet", "validity"): None,
    ("FacetRegistration", "actor"): None,
    ("FacetRegistration", "actor_object"): None,
    ("FacetRegistration", "current"): None,
    ("FacetRegistration", "end"): None,
    ("FacetRegistration", "model"): None,
    ("FacetRegistration", "note"): None,
    ("FacetRegistration", "registration_id"): None,
    ("FacetRegistration", "start"): None,
    ("FacetRegistration", "uuid"): None,
    ("FacetRegistration", "validities"): None,
    ("FacetResponse", "current"): None,
    ("FacetResponse", "objects"): None,
    ("FacetResponse", "registrations"): None,
    ("FacetResponse", "uuid"): None,
    ("FacetResponse", "validities"): None,
    ("FacetResponsePaged", "objects"): None,
    ("FacetResponsePaged", "page_info"): None,
    ("FacetResponseRegistration", "actor"): None,
    ("FacetResponseRegistration", "actor_object"): None,
    ("FacetResponseRegistration", "current"): None,
    ("FacetResponseRegistration", "end"): None,
    ("FacetResponseRegistration", "model"): None,
    ("FacetResponseRegistration", "note"): None,
    ("FacetResponseRegistration", "registration_id"): None,
    ("FacetResponseRegistration", "start"): None,
    ("FacetResponseRegistration", "uuid"): None,
    ("FacetResponseRegistration", "validities"): None,
    ("File", "base64_contents"): None,
    ("File", "file_name"): None,
    ("File", "file_store"): None,
    ("File", "text_contents"): None,
    ("FilePaged", "objects"): None,
    ("FilePaged", "page_info"): None,
    ("FullEvent", "listener"): ("read_event_listener", "event_listener", "read"),
    ("FullEvent", "priority"): None,
    ("FullEvent", "silenced"): None,
    ("FullEvent", "subject"): None,
    ("FullEventPaged", "objects"): None,
    ("FullEventPaged", "page_info"): None,
    ("Health", "identifier"): None,
    ("Health", "status"): None,
    ("HealthPaged", "objects"): None,
    ("HealthPaged", "page_info"): None,
    ("IRegistrationPaged", "objects"): None,
    ("IRegistrationPaged", "page_info"): None,
    ("ITSystem", "name"): None,
    ("ITSystem", "roles"): ("read_class", "class", "read"),
    ("ITSystem", "roles_response"): ("read_class", "class", "read"),
    ("ITSystem", "system_type"): None,
    ("ITSystem", "type"): None,
    ("ITSystem", "user_key"): None,
    ("ITSystem", "uuid"): None,
    ("ITSystem", "validity"): None,
    ("ITSystemRegistration", "actor"): None,
    ("ITSystemRegistration", "actor_object"): None,
    ("ITSystemRegistration", "current"): None,
    ("ITSystemRegistration", "end"): None,
    ("ITSystemRegistration", "model"): None,
    ("ITSystemRegistration", "note"): None,
    ("ITSystemRegistration", "registration_id"): None,
    ("ITSystemRegistration", "start"): None,
    ("ITSystemRegistration", "uuid"): None,
    ("ITSystemRegistration", "validities"): None,
    ("ITSystemResponse", "current"): None,
    ("ITSystemResponse", "objects"): None,
    ("ITSystemResponse", "registrations"): None,
    ("ITSystemResponse", "uuid"): None,
    ("ITSystemResponse", "validities"): None,
    ("ITSystemResponsePaged", "objects"): None,
    ("ITSystemResponsePaged", "page_info"): None,
    ("ITSystemResponseRegistration", "actor"): None,
    ("ITSystemResponseRegistration", "actor_object"): None,
    ("ITSystemResponseRegistration", "current"): None,
    ("ITSystemResponseRegistration", "end"): None,
    ("ITSystemResponseRegistration", "model"): None,
    ("ITSystemResponseRegistration", "note"): None,
    ("ITSystemResponseRegistration", "registration_id"): None,
    ("ITSystemResponseRegistration", "start"): None,
    ("ITSystemResponseRegistration", "uuid"): None,
    ("ITSystemResponseRegistration", "validities"): None,
    ("ITUser", "addresses"): ("read_address", "address", "read"),
    ("ITUser", "addresses_response"): ("read_address", "address", "read"),
    ("ITUser", "binding_type"): None,
    ("ITUser", "employee"): ("read_employee", "employee", "read"),
    ("ITUser", "employee_uuid"): None,
    ("ITUser", "engagement"): ("read_engagement", "engagement", "read"),
    ("ITUser", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("ITUser", "engagement_uuid"): None,
    ("ITUser", "engagement_uuids"): None,
    ("ITUser", "engagements"): ("read_engagement", "engagement", "read"),
    ("ITUser", "engagements_responses"): ("read_engagement", "engagement", "read"),
    ("ITUser", "external_id"): None,
    ("ITUser", "itsystem"): ("read_itsystem", "itsystem", "read"),
    ("ITUser", "itsystem_response"): ("read_itsystem", "itsystem", "read"),
    ("ITUser", "itsystem_uuid"): None,
    ("ITUser", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("ITUser", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("ITUser", "org_unit_uuid"): None,
    ("ITUser", "person"): ("read_employee", "employee", "read"),
    ("ITUser", "person_response"): ("read_employee", "employee", "read"),
    ("ITUser", "primary"): ("read_class", "class", "read"),
    ("ITUser", "primary_response"): ("read_class", "class", "read"),
    ("ITUser", "primary_uuid"): None,
    ("ITUser", "rolebindings"): ("read_rolebinding", "rolebinding", "read"),
    ("ITUser", "rolebindings_response"): ("read_rolebinding", "rolebinding", "read"),
    ("ITUser", "type"): None,
    ("ITUser", "user_key"): None,
    ("ITUser", "uuid"): None,
    ("ITUser", "validity"): None,
    ("ITUserRegistration", "actor"): None,
    ("ITUserRegistration", "actor_object"): None,
    ("ITUserRegistration", "current"): None,
    ("ITUserRegistration", "end"): None,
    ("ITUserRegistration", "model"): None,
    ("ITUserRegistration", "note"): None,
    ("ITUserRegistration", "registration_id"): None,
    ("ITUserRegistration", "start"): None,
    ("ITUserRegistration", "uuid"): None,
    ("ITUserRegistration", "validities"): None,
    ("ITUserResponse", "current"): None,
    ("ITUserResponse", "objects"): None,
    ("ITUserResponse", "registrations"): None,
    ("ITUserResponse", "uuid"): None,
    ("ITUserResponse", "validities"): None,
    ("ITUserResponsePaged", "objects"): None,
    ("ITUserResponsePaged", "page_info"): None,
    ("ITUserResponseRegistration", "actor"): None,
    ("ITUserResponseRegistration", "actor_object"): None,
    ("ITUserResponseRegistration", "current"): None,
    ("ITUserResponseRegistration", "end"): None,
    ("ITUserResponseRegistration", "model"): None,
    ("ITUserResponseRegistration", "note"): None,
    ("ITUserResponseRegistration", "registration_id"): None,
    ("ITUserResponseRegistration", "start"): None,
    ("ITUserResponseRegistration", "uuid"): None,
    ("ITUserResponseRegistration", "validities"): None,
    ("KLE", "kle_aspect_uuids"): None,
    ("KLE", "kle_aspects"): ("read_class", "class", "read"),
    ("KLE", "kle_aspects_response"): ("read_class", "class", "read"),
    ("KLE", "kle_number"): ("read_class", "class", "read"),
    ("KLE", "kle_number_response"): ("read_class", "class", "read"),
    ("KLE", "kle_number_uuid"): None,
    ("KLE", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("KLE", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("KLE", "org_unit_uuid"): None,
    ("KLE", "type"): None,
    ("KLE", "user_key"): None,
    ("KLE", "uuid"): None,
    ("KLE", "validity"): None,
    ("KLERegistration", "actor"): None,
    ("KLERegistration", "actor_object"): None,
    ("KLERegistration", "current"): None,
    ("KLERegistration", "end"): None,
    ("KLERegistration", "model"): None,
    ("KLERegistration", "note"): None,
    ("KLERegistration", "registration_id"): None,
    ("KLERegistration", "start"): None,
    ("KLERegistration", "uuid"): None,
    ("KLERegistration", "validities"): None,
    ("KLEResponse", "current"): None,
    ("KLEResponse", "objects"): None,
    ("KLEResponse", "registrations"): None,
    ("KLEResponse", "uuid"): None,
    ("KLEResponse", "validities"): None,
    ("KLEResponsePaged", "objects"): None,
    ("KLEResponsePaged", "page_info"): None,
    ("KLEResponseRegistration", "actor"): None,
    ("KLEResponseRegistration", "actor_object"): None,
    ("KLEResponseRegistration", "current"): None,
    ("KLEResponseRegistration", "end"): None,
    ("KLEResponseRegistration", "model"): None,
    ("KLEResponseRegistration", "note"): None,
    ("KLEResponseRegistration", "registration_id"): None,
    ("KLEResponseRegistration", "start"): None,
    ("KLEResponseRegistration", "uuid"): None,
    ("KLEResponseRegistration", "validities"): None,
    ("Leave", "employee"): ("read_employee", "employee", "read"),
    ("Leave", "employee_uuid"): None,
    ("Leave", "engagement"): ("read_engagement", "engagement", "read"),
    ("Leave", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("Leave", "engagement_uuid"): None,
    ("Leave", "leave_type"): ("read_class", "class", "read"),
    ("Leave", "leave_type_response"): ("read_class", "class", "read"),
    ("Leave", "leave_type_uuid"): None,
    ("Leave", "person"): ("read_employee", "employee", "read"),
    ("Leave", "person_response"): ("read_employee", "employee", "read"),
    ("Leave", "type"): None,
    ("Leave", "user_key"): None,
    ("Leave", "uuid"): None,
    ("Leave", "validity"): None,
    ("LeaveRegistration", "actor"): None,
    ("LeaveRegistration", "actor_object"): None,
    ("LeaveRegistration", "current"): None,
    ("LeaveRegistration", "end"): None,
    ("LeaveRegistration", "model"): None,
    ("LeaveRegistration", "note"): None,
    ("LeaveRegistration", "registration_id"): None,
    ("LeaveRegistration", "start"): None,
    ("LeaveRegistration", "uuid"): None,
    ("LeaveRegistration", "validities"): None,
    ("LeaveResponse", "current"): None,
    ("LeaveResponse", "objects"): None,
    ("LeaveResponse", "registrations"): None,
    ("LeaveResponse", "uuid"): None,
    ("LeaveResponse", "validities"): None,
    ("LeaveResponsePaged", "objects"): None,
    ("LeaveResponsePaged", "page_info"): None,
    ("LeaveResponseRegistration", "actor"): None,
    ("LeaveResponseRegistration", "actor_object"): None,
    ("LeaveResponseRegistration", "current"): None,
    ("LeaveResponseRegistration", "end"): None,
    ("LeaveResponseRegistration", "model"): None,
    ("LeaveResponseRegistration", "note"): None,
    ("LeaveResponseRegistration", "registration_id"): None,
    ("LeaveResponseRegistration", "start"): None,
    ("LeaveResponseRegistration", "uuid"): None,
    ("LeaveResponseRegistration", "validities"): None,
    ("Listener", "events"): ("read_event", "event", "read"),
    ("Listener", "namespace"): ("read_event_namespace", "event_namespace", "read"),
    ("Listener", "owner"): None,
    ("Listener", "routing_key"): None,
    ("Listener", "user_key"): None,
    ("Listener", "uuid"): None,
    ("ListenerPaged", "objects"): None,
    ("ListenerPaged", "page_info"): None,
    ("Manager", "employee"): ("read_employee", "employee", "read"),
    ("Manager", "employee_uuid"): None,
    ("Manager", "engagement_response"): ("read_engagement", "engagement", "read"),
    ("Manager", "manager_level"): ("read_class", "class", "read"),
    ("Manager", "manager_level_response"): ("read_class", "class", "read"),
    ("Manager", "manager_level_uuid"): None,
    ("Manager", "manager_type"): ("read_class", "class", "read"),
    ("Manager", "manager_type_response"): ("read_class", "class", "read"),
    ("Manager", "manager_type_uuid"): None,
    ("Manager", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Manager", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Manager", "org_unit_uuid"): None,
    ("Manager", "person"): ("read_employee", "employee", "read"),
    ("Manager", "person_response"): ("read_employee", "employee", "read"),
    ("Manager", "responsibilities"): ("read_class", "class", "read"),
    ("Manager", "responsibilities_response"): ("read_class", "class", "read"),
    ("Manager", "responsibility_uuids"): None,
    ("Manager", "type"): None,
    ("Manager", "user_key"): None,
    ("Manager", "uuid"): None,
    ("Manager", "validity"): None,
    ("ManagerRegistration", "actor"): None,
    ("ManagerRegistration", "actor_object"): None,
    ("ManagerRegistration", "current"): None,
    ("ManagerRegistration", "end"): None,
    ("ManagerRegistration", "model"): None,
    ("ManagerRegistration", "note"): None,
    ("ManagerRegistration", "registration_id"): None,
    ("ManagerRegistration", "start"): None,
    ("ManagerRegistration", "uuid"): None,
    ("ManagerRegistration", "validities"): None,
    ("ManagerResponse", "current"): None,
    ("ManagerResponse", "objects"): None,
    ("ManagerResponse", "registrations"): None,
    ("ManagerResponse", "uuid"): None,
    ("ManagerResponse", "validities"): None,
    ("ManagerResponsePaged", "objects"): None,
    ("ManagerResponsePaged", "page_info"): None,
    ("ManagerResponseRegistration", "actor"): None,
    ("ManagerResponseRegistration", "actor_object"): None,
    ("ManagerResponseRegistration", "current"): None,
    ("ManagerResponseRegistration", "end"): None,
    ("ManagerResponseRegistration", "model"): None,
    ("ManagerResponseRegistration", "note"): None,
    ("ManagerResponseRegistration", "registration_id"): None,
    ("ManagerResponseRegistration", "start"): None,
    ("ManagerResponseRegistration", "uuid"): None,
    ("ManagerResponseRegistration", "validities"): None,
    ("MultifieldAddress", "name"): None,
    ("MultifieldAddress", "value"): None,
    ("MultifieldAddress", "value2"): None,
    ("Mutation", "address_create"): ("create_address", "address", "create"),
    ("Mutation", "address_delete"): ("delete_address", "address", "delete"),
    ("Mutation", "address_refresh"): ("refresh_address", "address", "refresh"),
    ("Mutation", "address_terminate"): ("terminate_address", "address", "terminate"),
    ("Mutation", "address_update"): ("update_address", "address", "update"),
    ("Mutation", "addresses_create"): ("create_address", "address", "create"),
    ("Mutation", "association_create"): ("create_association", "association", "create"),
    ("Mutation", "association_refresh"): (
        "refresh_association",
        "association",
        "refresh",
    ),
    ("Mutation", "association_terminate"): (
        "terminate_association",
        "association",
        "terminate",
    ),
    ("Mutation", "association_update"): ("update_association", "association", "update"),
    ("Mutation", "class_create"): ("create_class", "class", "create"),
    ("Mutation", "class_delete"): ("delete_class", "class", "delete"),
    ("Mutation", "class_refresh"): ("refresh_class", "class", "refresh"),
    ("Mutation", "class_terminate"): ("terminate_class", "class", "terminate"),
    ("Mutation", "class_update"): ("update_class", "class", "update"),
    ("Mutation", "employee_create"): ("create_employee", "employee", "create"),
    ("Mutation", "employee_delete"): ("delete_employee", "employee", "delete"),
    ("Mutation", "employee_refresh"): ("refresh_employee", "employee", "refresh"),
    ("Mutation", "employee_terminate"): ("terminate_employee", "employee", "terminate"),
    ("Mutation", "employee_update"): ("update_employee", "employee", "update"),
    ("Mutation", "engagement_create"): ("create_engagement", "engagement", "create"),
    ("Mutation", "engagement_delete"): ("delete_engagement", "engagement", "delete"),
    ("Mutation", "engagement_refresh"): ("refresh_engagement", "engagement", "refresh"),
    ("Mutation", "engagement_terminate"): (
        "terminate_engagement",
        "engagement",
        "terminate",
    ),
    ("Mutation", "engagement_update"): ("update_engagement", "engagement", "update"),
    ("Mutation", "engagements_create"): ("create_engagement", "engagement", "create"),
    ("Mutation", "engagements_update"): ("update_engagement", "engagement", "update"),
    ("Mutation", "event_acknowledge"): ("acknowledge_event", None, None),
    ("Mutation", "event_listener_declare"): (
        "create_event_listener",
        "event_listener",
        "create",
    ),
    ("Mutation", "event_listener_delete"): (
        "delete_event_listener",
        "event_listener",
        "delete",
    ),
    ("Mutation", "event_namespace_declare"): (
        "create_event_namespace",
        "event_namespace",
        "create",
    ),
    ("Mutation", "event_namespace_delete"): (
        "delete_event_namespace",
        "event_namespace",
        "delete",
    ),
    ("Mutation", "event_rerun"): ("rerun_event", None, None),
    ("Mutation", "event_send"): ("send_event", None, None),
    ("Mutation", "event_silence"): ("silence_event", None, None),
    ("Mutation", "event_unsilence"): ("unsilence_event", None, None),
    ("Mutation", "facet_create"): ("create_facet", "facet", "create"),
    ("Mutation", "facet_delete"): ("delete_facet", "facet", "delete"),
    ("Mutation", "facet_refresh"): ("refresh_facet", "facet", "refresh"),
    ("Mutation", "facet_terminate"): ("terminate_facet", "facet", "terminate"),
    ("Mutation", "facet_update"): ("update_facet", "facet", "update"),
    ("Mutation", "itassociation_create"): (
        "create_association",
        "association",
        "create",
    ),
    ("Mutation", "itassociation_terminate"): (
        "terminate_association",
        "association",
        "terminate",
    ),
    ("Mutation", "itassociation_update"): (
        "update_association",
        "association",
        "update",
    ),
    ("Mutation", "itsystem_create"): ("create_itsystem", "itsystem", "create"),
    ("Mutation", "itsystem_delete"): ("delete_itsystem", "itsystem", "delete"),
    ("Mutation", "itsystem_refresh"): ("refresh_itsystem", "itsystem", "refresh"),
    ("Mutation", "itsystem_terminate"): ("terminate_itsystem", "itsystem", "terminate"),
    ("Mutation", "itsystem_update"): ("update_itsystem", "itsystem", "update"),
    ("Mutation", "ituser_create"): ("create_ituser", "ituser", "create"),
    ("Mutation", "ituser_delete"): ("delete_ituser", "ituser", "delete"),
    ("Mutation", "ituser_refresh"): ("refresh_ituser", "ituser", "refresh"),
    ("Mutation", "ituser_terminate"): ("terminate_ituser", "ituser", "terminate"),
    ("Mutation", "ituser_update"): ("update_ituser", "ituser", "update"),
    ("Mutation", "itusers_create"): ("create_ituser", "ituser", "create"),
    ("Mutation", "kle_create"): ("create_kle", "kle", "create"),
    ("Mutation", "kle_refresh"): ("refresh_kle", "kle", "refresh"),
    ("Mutation", "kle_terminate"): ("terminate_kle", "kle", "terminate"),
    ("Mutation", "kle_update"): ("update_kle", "kle", "update"),
    ("Mutation", "leave_create"): ("create_leave", "leave", "create"),
    ("Mutation", "leave_refresh"): ("refresh_leave", "leave", "refresh"),
    ("Mutation", "leave_terminate"): ("terminate_leave", "leave", "terminate"),
    ("Mutation", "leave_update"): ("update_leave", "leave", "update"),
    ("Mutation", "manager_create"): ("create_manager", "manager", "create"),
    ("Mutation", "manager_delete"): ("delete_manager", "manager", "delete"),
    ("Mutation", "manager_refresh"): ("refresh_manager", "manager", "refresh"),
    ("Mutation", "manager_terminate"): ("terminate_manager", "manager", "terminate"),
    ("Mutation", "manager_update"): ("update_manager", "manager", "update"),
    ("Mutation", "managers_create"): ("create_manager", "manager", "create"),
    ("Mutation", "org_create"): ("create_org", "org", "create"),
    ("Mutation", "org_unit_create"): ("create_org_unit", "org_unit", "create"),
    ("Mutation", "org_unit_delete"): ("delete_org_unit", "org_unit", "delete"),
    ("Mutation", "org_unit_refresh"): ("refresh_org_unit", "org_unit", "refresh"),
    ("Mutation", "org_unit_terminate"): ("terminate_org_unit", "org_unit", "terminate"),
    ("Mutation", "org_unit_update"): ("update_org_unit", "org_unit", "update"),
    ("Mutation", "owner_create"): ("create_owner", "owner", "create"),
    ("Mutation", "owner_refresh"): ("refresh_owner", "owner", "refresh"),
    ("Mutation", "owner_terminate"): ("terminate_owner", "owner", "terminate"),
    ("Mutation", "owner_update"): ("update_owner", "owner", "update"),
    ("Mutation", "related_unit_refresh"): (
        "refresh_related_unit",
        "related_unit",
        "refresh",
    ),
    ("Mutation", "related_units_update"): (
        "update_related_unit",
        "related_unit",
        "update",
    ),
    ("Mutation", "rolebinding_create"): ("create_rolebinding", "rolebinding", "create"),
    ("Mutation", "rolebinding_delete"): ("delete_rolebinding", "rolebinding", "delete"),
    ("Mutation", "rolebinding_refresh"): (
        "refresh_rolebinding",
        "rolebinding",
        "refresh",
    ),
    ("Mutation", "rolebinding_terminate"): (
        "terminate_rolebinding",
        "rolebinding",
        "terminate",
    ),
    ("Mutation", "rolebinding_update"): ("update_rolebinding", "rolebinding", "update"),
    ("Mutation", "rolebindings_create"): (
        "create_rolebinding",
        "rolebinding",
        "create",
    ),
    ("Mutation", "upload_file"): ("upload_files", None, None),
    ("Myself", "actor"): None,
    ("Myself", "email"): None,
    ("Myself", "roles"): None,
    ("Myself", "username"): None,
    # NB: Namespace.listeners checks read_event_namespace (not read_event_listener);
    # this preserves the original per-field permission_classes behaviour.
    ("Namespace", "listeners"): ("read_event_namespace", "event_namespace", "read"),
    ("Namespace", "name"): None,
    ("Namespace", "owner"): None,
    ("Namespace", "public"): None,
    ("NamespacePaged", "objects"): None,
    ("NamespacePaged", "page_info"): None,
    ("OpenValidity", "from"): None,
    ("OpenValidity", "to"): None,
    ("Organisation", "municipality_code"): None,
    ("Organisation", "name"): None,
    ("Organisation", "type"): None,
    ("Organisation", "user_key"): None,
    ("Organisation", "uuid"): None,
    ("OrganisationUnit", "addresses"): ("read_address", "address", "read"),
    ("OrganisationUnit", "addresses_response"): ("read_address", "address", "read"),
    ("OrganisationUnit", "ancestors"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "associations"): ("read_association", "association", "read"),
    ("OrganisationUnit", "associations_response"): (
        "read_association",
        "association",
        "read",
    ),
    ("OrganisationUnit", "child_count"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "children"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "children_response"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "engagements"): ("read_engagement", "engagement", "read"),
    ("OrganisationUnit", "engagements_response"): (
        "read_engagement",
        "engagement",
        "read",
    ),
    ("OrganisationUnit", "has_children"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "itusers"): ("read_ituser", "ituser", "read"),
    ("OrganisationUnit", "itusers_response"): ("read_ituser", "ituser", "read"),
    ("OrganisationUnit", "kles"): ("read_kle", "kle", "read"),
    ("OrganisationUnit", "kles_response"): ("read_kle", "kle", "read"),
    ("OrganisationUnit", "leaves"): ("read_leave", "leave", "read"),
    ("OrganisationUnit", "leaves_response"): ("read_leave", "leave", "read"),
    ("OrganisationUnit", "managers"): ("read_manager", "manager", "read"),
    ("OrganisationUnit", "managers_response"): ("read_manager", "manager", "read"),
    ("OrganisationUnit", "name"): None,
    ("OrganisationUnit", "org_unit_hierarchy"): None,
    ("OrganisationUnit", "org_unit_hierarchy_model"): ("read_class", "class", "read"),
    ("OrganisationUnit", "org_unit_level"): ("read_class", "class", "read"),
    ("OrganisationUnit", "org_unit_level_uuid"): None,
    ("OrganisationUnit", "owners"): ("read_owner", "owner", "read"),
    ("OrganisationUnit", "parent"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "parent_response"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "parent_uuid"): None,
    ("OrganisationUnit", "related_units"): (
        "read_related_unit",
        "related_unit",
        "read",
    ),
    ("OrganisationUnit", "related_units_response"): (
        "read_related_unit",
        "related_unit",
        "read",
    ),
    ("OrganisationUnit", "root"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "root_response"): ("read_org_unit", "org_unit", "read"),
    ("OrganisationUnit", "time_planning"): ("read_class", "class", "read"),
    ("OrganisationUnit", "time_planning_response"): ("read_class", "class", "read"),
    ("OrganisationUnit", "time_planning_uuid"): None,
    ("OrganisationUnit", "type"): None,
    ("OrganisationUnit", "unit_hierarchy_response"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_level_response"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_type"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_type_response"): ("read_class", "class", "read"),
    ("OrganisationUnit", "unit_type_uuid"): None,
    ("OrganisationUnit", "user_key"): None,
    ("OrganisationUnit", "uuid"): None,
    ("OrganisationUnit", "validity"): None,
    ("OrganisationUnitRegistration", "actor"): None,
    ("OrganisationUnitRegistration", "actor_object"): None,
    ("OrganisationUnitRegistration", "current"): None,
    ("OrganisationUnitRegistration", "end"): None,
    ("OrganisationUnitRegistration", "model"): None,
    ("OrganisationUnitRegistration", "note"): None,
    ("OrganisationUnitRegistration", "registration_id"): None,
    ("OrganisationUnitRegistration", "start"): None,
    ("OrganisationUnitRegistration", "uuid"): None,
    ("OrganisationUnitRegistration", "validities"): None,
    ("OrganisationUnitResponse", "current"): None,
    ("OrganisationUnitResponse", "objects"): None,
    ("OrganisationUnitResponse", "registrations"): None,
    ("OrganisationUnitResponse", "uuid"): None,
    ("OrganisationUnitResponse", "validities"): None,
    ("OrganisationUnitResponsePaged", "objects"): None,
    ("OrganisationUnitResponsePaged", "page_info"): None,
    ("OrganisationUnitResponseRegistration", "actor"): None,
    ("OrganisationUnitResponseRegistration", "actor_object"): None,
    ("OrganisationUnitResponseRegistration", "current"): None,
    ("OrganisationUnitResponseRegistration", "end"): None,
    ("OrganisationUnitResponseRegistration", "model"): None,
    ("OrganisationUnitResponseRegistration", "note"): None,
    ("OrganisationUnitResponseRegistration", "registration_id"): None,
    ("OrganisationUnitResponseRegistration", "start"): None,
    ("OrganisationUnitResponseRegistration", "uuid"): None,
    ("OrganisationUnitResponseRegistration", "validities"): None,
    ("Owner", "employee_uuid"): None,
    ("Owner", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("Owner", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("Owner", "org_unit_uuid"): None,
    ("Owner", "owner"): ("read_owner", "owner", "read"),
    ("Owner", "owner_inference_priority"): None,
    ("Owner", "owner_response"): ("read_owner", "owner", "read"),
    ("Owner", "owner_uuid"): None,
    ("Owner", "person"): ("read_employee", "employee", "read"),
    ("Owner", "person_response"): ("read_employee", "employee", "read"),
    ("Owner", "type"): None,
    ("Owner", "user_key"): None,
    ("Owner", "uuid"): None,
    ("Owner", "validity"): None,
    ("OwnerRegistration", "actor"): None,
    ("OwnerRegistration", "actor_object"): None,
    ("OwnerRegistration", "current"): None,
    ("OwnerRegistration", "end"): None,
    ("OwnerRegistration", "model"): None,
    ("OwnerRegistration", "note"): None,
    ("OwnerRegistration", "registration_id"): None,
    ("OwnerRegistration", "start"): None,
    ("OwnerRegistration", "uuid"): None,
    ("OwnerRegistration", "validities"): None,
    ("OwnerResponse", "current"): None,
    ("OwnerResponse", "objects"): None,
    ("OwnerResponse", "registrations"): None,
    ("OwnerResponse", "uuid"): None,
    ("OwnerResponse", "validities"): None,
    ("OwnerResponsePaged", "objects"): None,
    ("OwnerResponsePaged", "page_info"): None,
    ("OwnerResponseRegistration", "actor"): None,
    ("OwnerResponseRegistration", "actor_object"): None,
    ("OwnerResponseRegistration", "current"): None,
    ("OwnerResponseRegistration", "end"): None,
    ("OwnerResponseRegistration", "model"): None,
    ("OwnerResponseRegistration", "note"): None,
    ("OwnerResponseRegistration", "registration_id"): None,
    ("OwnerResponseRegistration", "start"): None,
    ("OwnerResponseRegistration", "uuid"): None,
    ("OwnerResponseRegistration", "validities"): None,
    ("PageInfo", "next_cursor"): None,
    ("PersonRegistration", "actor"): None,
    ("PersonRegistration", "actor_object"): None,
    ("PersonRegistration", "current"): None,
    ("PersonRegistration", "end"): None,
    ("PersonRegistration", "model"): None,
    ("PersonRegistration", "note"): None,
    ("PersonRegistration", "registration_id"): None,
    ("PersonRegistration", "start"): None,
    ("PersonRegistration", "uuid"): None,
    ("PersonRegistration", "validities"): None,
    ("Query", "access_log"): ("read_accesslog", "accesslog", "read"),
    ("Query", "addresses"): ("read_address", "address", "read"),
    ("Query", "associations"): ("read_association", "association", "read"),
    ("Query", "classes"): ("read_class", "class", "read"),
    ("Query", "employees"): ("read_employee", "employee", "read"),
    ("Query", "engagements"): ("read_engagement", "engagement", "read"),
    ("Query", "event_fetch"): ("fetch_event", None, None),
    ("Query", "event_listeners"): ("read_event_listener", "event_listener", "read"),
    ("Query", "event_namespaces"): ("read_event_namespace", "event_namespace", "read"),
    ("Query", "events"): ("read_event", "event", "read"),
    ("Query", "facets"): ("read_facet", "facet", "read"),
    ("Query", "files"): ("read_file", "file", "read"),
    ("Query", "healths"): None,
    ("Query", "itsystems"): ("read_itsystem", "itsystem", "read"),
    ("Query", "itusers"): ("read_ituser", "ituser", "read"),
    ("Query", "kles"): ("read_kle", "kle", "read"),
    ("Query", "leaves"): ("read_leave", "leave", "read"),
    ("Query", "managers"): ("read_manager", "manager", "read"),
    ("Query", "me"): None,
    ("Query", "org"): ("read_org", "org", "read"),
    ("Query", "org_units"): ("read_org_unit", "org_unit", "read"),
    ("Query", "owners"): ("read_owner", "owner", "read"),
    ("Query", "persons"): ("read_employee", "employee", "read"),
    ("Query", "registrations"): ("read_registration", "registration", "read"),
    ("Query", "related_units"): ("read_related_unit", "related_unit", "read"),
    ("Query", "rolebindings"): ("read_rolebinding", "rolebinding", "read"),
    ("Query", "version"): None,
    ("Registration", "actor"): None,
    ("Registration", "actor_object"): None,
    ("Registration", "end"): None,
    ("Registration", "model"): None,
    ("Registration", "note"): None,
    ("Registration", "registration_id"): None,
    ("Registration", "start"): None,
    ("Registration", "uuid"): None,
    ("RegistrationPaged", "objects"): None,
    ("RegistrationPaged", "page_info"): None,
    ("RelatedUnit", "org_unit_uuids"): None,
    ("RelatedUnit", "org_units"): ("read_org_unit", "org_unit", "read"),
    ("RelatedUnit", "org_units_response"): ("read_org_unit", "org_unit", "read"),
    ("RelatedUnit", "type"): None,
    ("RelatedUnit", "user_key"): None,
    ("RelatedUnit", "uuid"): None,
    ("RelatedUnit", "validity"): None,
    ("RelatedUnitRegistration", "actor"): None,
    ("RelatedUnitRegistration", "actor_object"): None,
    ("RelatedUnitRegistration", "current"): None,
    ("RelatedUnitRegistration", "end"): None,
    ("RelatedUnitRegistration", "model"): None,
    ("RelatedUnitRegistration", "note"): None,
    ("RelatedUnitRegistration", "registration_id"): None,
    ("RelatedUnitRegistration", "start"): None,
    ("RelatedUnitRegistration", "uuid"): None,
    ("RelatedUnitRegistration", "validities"): None,
    ("RelatedUnitResponse", "current"): None,
    ("RelatedUnitResponse", "objects"): None,
    ("RelatedUnitResponse", "registrations"): None,
    ("RelatedUnitResponse", "uuid"): None,
    ("RelatedUnitResponse", "validities"): None,
    ("RelatedUnitResponsePaged", "objects"): None,
    ("RelatedUnitResponsePaged", "page_info"): None,
    ("RelatedUnitResponseRegistration", "actor"): None,
    ("RelatedUnitResponseRegistration", "actor_object"): None,
    ("RelatedUnitResponseRegistration", "current"): None,
    ("RelatedUnitResponseRegistration", "end"): None,
    ("RelatedUnitResponseRegistration", "model"): None,
    ("RelatedUnitResponseRegistration", "note"): None,
    ("RelatedUnitResponseRegistration", "registration_id"): None,
    ("RelatedUnitResponseRegistration", "start"): None,
    ("RelatedUnitResponseRegistration", "uuid"): None,
    ("RelatedUnitResponseRegistration", "validities"): None,
    ("RoleBinding", "ituser"): ("read_ituser", "ituser", "read"),
    ("RoleBinding", "ituser_response"): ("read_ituser", "ituser", "read"),
    ("RoleBinding", "org_unit"): ("read_org_unit", "org_unit", "read"),
    ("RoleBinding", "org_unit_response"): ("read_org_unit", "org_unit", "read"),
    ("RoleBinding", "role"): ("read_class", "class", "read"),
    ("RoleBinding", "role_response"): ("read_class", "class", "read"),
    ("RoleBinding", "user_key"): None,
    ("RoleBinding", "uuid"): None,
    ("RoleBinding", "validity"): None,
    ("RoleBindingRegistration", "actor"): None,
    ("RoleBindingRegistration", "actor_object"): None,
    ("RoleBindingRegistration", "current"): None,
    ("RoleBindingRegistration", "end"): None,
    ("RoleBindingRegistration", "model"): None,
    ("RoleBindingRegistration", "note"): None,
    ("RoleBindingRegistration", "registration_id"): None,
    ("RoleBindingRegistration", "start"): None,
    ("RoleBindingRegistration", "uuid"): None,
    ("RoleBindingRegistration", "validities"): None,
    ("RoleBindingResponse", "current"): None,
    ("RoleBindingResponse", "objects"): None,
    ("RoleBindingResponse", "registrations"): None,
    ("RoleBindingResponse", "uuid"): None,
    ("RoleBindingResponse", "validities"): None,
    ("RoleBindingResponsePaged", "objects"): None,
    ("RoleBindingResponsePaged", "page_info"): None,
    ("RoleBindingResponseRegistration", "actor"): None,
    ("RoleBindingResponseRegistration", "actor_object"): None,
    ("RoleBindingResponseRegistration", "current"): None,
    ("RoleBindingResponseRegistration", "end"): None,
    ("RoleBindingResponseRegistration", "model"): None,
    ("RoleBindingResponseRegistration", "note"): None,
    ("RoleBindingResponseRegistration", "registration_id"): None,
    ("RoleBindingResponseRegistration", "start"): None,
    ("RoleBindingResponseRegistration", "uuid"): None,
    ("RoleBindingResponseRegistration", "validities"): None,
    ("SpecialActor", "display_name"): None,
    ("SpecialActor", "event_listeners"): (
        "read_event_listener",
        "event_listener",
        "read",
    ),
    ("SpecialActor", "event_namespaces"): (
        "read_event_namespace",
        "event_namespace",
        "read",
    ),
    ("SpecialActor", "key"): None,
    ("SpecialActor", "uuid"): None,
    ("UUIDPaged", "objects"): None,
    ("UUIDPaged", "page_info"): None,
    ("UnknownActor", "display_name"): None,
    ("UnknownActor", "error"): None,
    ("UnknownActor", "event_listeners"): (
        "read_event_listener",
        "event_listener",
        "read",
    ),
    ("UnknownActor", "event_namespaces"): (
        "read_event_namespace",
        "event_namespace",
        "read",
    ),
    ("UnknownActor", "uuid"): None,
    ("Validity", "from"): None,
    ("Validity", "to"): None,
    ("Version", "lora_version"): None,
    ("Version", "mo_hash"): None,
    ("Version", "mo_version"): None,
}
