from enum import Enum


class AccessLogModel(str, Enum):
    ACCESS_LOG = "ACCESS_LOG"
    PERSON = "PERSON"
    FACET = "FACET"
    IT_SYSTEM = "IT_SYSTEM"
    CLASS = "CLASS"
    ORGANISATION = "ORGANISATION"
    ORGANISATION_UNIT = "ORGANISATION_UNIT"
    ORGANISATION_FUNCTION = "ORGANISATION_FUNCTION"


class FileStore(str, Enum):
    EXPORTS = "EXPORTS"
    INSIGHTS = "INSIGHTS"


class HardcodedActor(str, Enum):
    NO_AUTH = "NO_AUTH"
    LEGACY_AUTH = "LEGACY_AUTH"
    BEFORE_ACTOR = "BEFORE_ACTOR"
    LORA_USER = "LORA_USER"
    UNABLE_TO_PARSE_TOKEN = "UNABLE_TO_PARSE_TOKEN"
    MISSING_UUID_ON_TOKEN = "MISSING_UUID_ON_TOKEN"
    NO_AUTH_MIDDLEWARE = "NO_AUTH_MIDDLEWARE"


class OwnerInferencePriority(str, Enum):
    ENGAGEMENT = "ENGAGEMENT"
    ASSOCIATION = "ASSOCIATION"
