# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
version: "3.9"
services:
  frontend:
    depends_on:
      mo:
        condition: service_started
  mo:
    depends_on:
      mox:
        condition: service_started
      msg_broker:
        condition: service_started
      keycloak:
        condition: service_started
      otel-collector:
        condition: service_started
  mox:
    depends_on:
      mox-db-init:
        condition: service_completed_successfully
      mox-db:
        condition: service_started
      otel-collector:
        condition: service_started
  mox-db-init:
    depends_on:
      mox-db:
        condition: service_started
  keycloak:
    depends_on:
      keycloak-gen:
        condition: service_completed_successfully
      keycloak-db:
        condition: service_started
  otel-collector:
    depends_on:
      tempo:
        condition: service_started
  grafana:
    depends_on:
      tempo:
        condition: service_started
