# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

# A copy of this file is also present in the LoRa repository under
# `dev-environment/settings-for-mo-test.toml`. See that file for an explanation
# as to why. Please update both files simultaneously.
[database]
host = "mox-db"
user = "mox"
password = "mox"
db_name = "mox"


[db_extensions]
path = "oio_rest/oio_rest/db_extensions/mo-01.json"


[testing_api]
enable = true
