receivers:
  jaeger:
    protocols:
      thrift_compact:

processors:
  batch:

exporters:
  otlp:
    endpoint: tempo:55680
    insecure: true

service:
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch]
      exporters: [otlp]
