site_name: OS2mo | MedarbejderOrganisation
site_url: ""
use_directory_urls: False
site_description: OS2mo dokumentation
repo_name: os2mo
# TODO: Use the GitHub repo when it's ready
repo_url: https://github.com/OS2mo/os2mo
docs_dir: src/

nav:
  - OS2MO:
      - Velkommen: index.md
      - API dokumentation, herunder GraphQL:
          - api-dokumentation/triggers.md
          - api-dokumentation/events.md
          - api-dokumentation/amqp-legacy.md
          - graphql/intro.md
          - graphql/migration.md
          - graphql/reads.md
      - Arkitektur og design:
          - arkitektur-design/system.md
          - arkitektur-design/facets.md
          - arkitektur-design/overview.md
      - Drift og support:
          - drift-support/cookbook.md
          - drift-support/mocloud.md
          - drift-support/audit.md
      - Funktionalitet:
          - Email-notifikationer: guides/Emailnotifikationer.md
          - KLE i MO: guides/KLEiMO.md
          - Lederhåndtering i MO: guides/Lederhaandtering i MO.md
          - MED-organisation i OS2mo: guides/MED-organisationen.md
          - Stillingsbetegnelser (følsomme): guides/Stillingsbetegnelser.md
      - MO manual: drift-support/manual.md
      - Release History: changelog.md
      - Sikkerhed:
          - ADFS SAML setup for OS2mo: guides/adfs-setup.md
          - ADFS RBAC setup for OS2mo: guides/adfs-rbac-setup.md
          - Autentificering: drift-support/auth.md
          - Roller: drift-support/keycloak.md
      - Technician and developer guides:
          - Getting started (with Docker): guides/environment/docker.md
  - Lokal rammearkitektur (LoRa og databasen):
      - Developer Documentation:
          - lora/dev/wildcards.md
      - User Documentation:
          - Objects:
              - lora/user/objects.md
          - lora/user/log-haendelse.md
  - Integrationer:
      - Integrationer:
          - data-import-export/integrations/aarhus-los.md
          - data-import-export/integrations/ad.md
          - data-import-export/integrations/ldap_ad_amqp_integration.md
          - data-import-export/integrations/opusloen.md
          - data-import-export/integrations/sdloen.md
          - data-import-export/integrations/Organisationsopmærkning.md
          - data-import-export/integrations/Omada.md
      - Exporter:
          - data-import-export/exporters/plan2learn.md
          - data-import-export/exporters/sql_export.md
          - data-import-export/exporters/emus.md
          - data-import-export/exporters/os2phonebook.md
          - data-import-export/exporters/os2rollekatalog.md
          - data-import-export/exporters/os2sync.md
          - data-import-export/exporters/org-chart.md
      - OS2MO Data Import:
          - data-import-export/os2mo_data_import/import-tool.md
      - data-import-export/reports.md
      - data-import-export/tools.md
theme:
  name: "material"
  palette:
    - scheme:
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
  features:
    - navigation.top
    - navigation.tabs
  favicon: static/favicon.ico

# Adds Magenta's colour scheme
extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      toc_depth: 3
      permalink: "#"
