site_name: OS2mo | MedarbejderOrganisation
site_url: ""
use_directory_urls: False
site_description: OS2mo dokumentation
repo_name: os2mo
# TODO: Use the GitHub repo when it's ready
repo_url: https://github.com/OS2mo/os2mo
docs_dir: src/

nav:
  - Velkommen:
      - OS2mo: index.md
      - Release History: news.md
  - Arkitektur og design:
      - arkitektur-design/overview.md
      - arkitektur-design/facets.md
      - arkitektur-design/system.md
  - User and developer guides:
      - Getting started:
          - guides/environment/docker.md
          - guides/environment/install-source.md
      - Tests: guides/tests.md
      - Conventions: guides/conventions.md
      - ADFS:
        - guides/adfs-setup.md
        - guides/adfs-rbac-setup.md
  - Drift og support:
      - drift-support/auth.md
      - drift-support/cookbook.md
      - drift-support/manual.md
      - drift-support/settings.md
      - drift-support/mocloud.md
      - drift-support/keycloak.md
  - API Dokumentation:
      - api-dokumentation/amqp.md
      - api-dokumentation/triggers.md
      - api-dokumentation/user-configuration.md
  - GraphQL:
      - graphql/intro.md
      - graphql/reads.md
  - LoRa MOX:
    - lora/index.md
    - User Documentation: 
      - lora/user/overview.md
      - lora/user/praesentation.md
      - lora/user/installation.md
      - lora/user/database.md
      - Objects:
        - lora/user/objects.md
        - Integrationdata: lora/user/objects/integrationdata.md
      - REST API: 
        - lora/user/api.md
        - lora/user/api/self-documentation.md
        - lora/user/api/tutorial.md
        - Operations:
          - Read: lora/user/api/read.md 
          - List: lora/user/api/list.md
          - Search: lora/user/api/search.md
          - Create: lora/user/api/create.md
          - Update: 
            - lora/user/api/update.md
            - lora/user/api/update/merging.md
            - lora/user/api/update/deleting.md
          - Passivate: lora/user/api/passivate.md
          - Delete: lora/user/api/delete.md
          - Import: lora/user/api/import.md
          - File operations:
            - lora/user/api/advanced/file-operations.md
            - lora/user/api/advanced/deleting-document.md
      - lora/user/log-haendelse.md
      - lora/user/agents.md
      - lora/user/auth.md
      - lora/user/deployment.md
      - lora/user/settings.md
      - lora/user/operating-mox.md
    - Developer Documentation:
      - lora/dev/database.md
      - lora/dev/migrations.md
      - lora/dev/wildcards.md
      - lora/dev/test.md
      - lora/dev/testing-rest.md
      - lora/dev/building-docs.md
      - lora/dev/beskedfordeler.md
      - lora/dev/news.md
  - Data import og export:
    - data-import-export/intro.md
    - Integrationer:
      - data-import-export/integrations/sdloen.md
      - data-import-export/integrations/opusloen.md
      - data-import-export/integrations/ad.md
      - data-import-export/integrations/os2sync.md
      - data-import-export/integrations/aarhus-los.md
    - Exporter:
      - data-import-export/exporters/exporters.md
      - data-import-export/exporters/plan2learn.md
      - data-import-export/exporters/sql_export.md
      - data-import-export/exporters/emus.md
      - data-import-export/exporters/os2phonebook.md
      - data-import-export/exporters/os2rollekatalog.md
    - OS2MO Data Import:
      - data-import-export/os2mo_data_import/import-tool.md
      - data-import-export/os2mo_data_import/integration-abstraction.md
    - data-import-export/reports.md
    - data-import-export/tools.md
    - data-import-export/changelog.md
theme:
  name: "material"
  palette:
    - scheme:
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
  features:
    - navigation.top
    - navigation.tabs
  favicon: static/favicon.ico

# Adds Magenta's colour scheme
extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      toc_depth: 3
      permalink: "#"
