site_name: OS2mo | MedarbejderOrganisation
site_url: ""
use_directory_urls: False
site_description: OS2mo dokumentation
repo_name: os2mo
# TODO: Use the GitHub repo when it's ready
repo_url: https://github.com/OS2mo/os2mo
docs_dir: src/

nav:
  - Velkommen:
      - OS2mo: index.md
      - Release History: news.md
  - Arkitektur og design:
      - arkitektur-design/overview.md
      - arkitektur-design/facets.md
      - arkitektur-design/system.md
  - Udvikler- og brugerguide:
      - Getting started:
          - guides/environment/docker.md
          - guides/environment/install-source.md
      - Tests: guides/tests.md
      - Conventions: guides/conventions.md
  - Drift og support:
      - drift-support/auth.md
      - drift-support/cookbook.md
      - drift-support/manual.md
      - drift-support/settings.md
  - API Dokumentation:
      - api-dokumentation/amqp.md
      - api-dokumentation/triggers.md
      - api-dokumentation/user-configuration.md
  - GraphQL: graphql/graphql.md

theme:
  name: "material"
  palette:
    - scheme:
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
  features:
    - navigation.top
    - navigation.tabs
  favicon: static/favicon.ico

# Adds Magenta's colour scheme
extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      toc_depth: 3
      permalink: "#"
