site_name: OS2mo | MedarbejderOrganisation
site_url: ""
use_directory_urls: False
site_description: OS2mo dokumentation
repo_name: os2mo
# TODO: Use the GitHub repo when it's ready
repo_url: https://github.com/OS2mo/os2mo
docs_dir: src/

nav:
  - MO:
    - Velkommen: mo/index.md
    - Arkitektur og design:
      - mo/arkitektur-design/overview.md
      - mo/arkitektur-design/facets.md
      - mo/arkitektur-design/system.md
    - User and developer guides:
      - Getting started:
        - mo/guides/environment/docker.md
        - mo/guides/environment/install-source.md
        - Tests: mo/guides/tests.md
        - Conventions: mo/guides/conventions.md
        - ADFS:
          - mo/guides/adfs-setup.md
          - mo/guides/adfs-rbac-setup.md
    - Drift og support:
      - mo/drift-support/auth.md
      - mo/drift-support/cookbook.md
      - mo/drift-support/manual.md
      - mo/drift-support/settings.md
    - API Dokumentation:
      - mo/api-dokumentation/amqp.md
      - mo/api-dokumentation/triggers.md
      - mo/api-dokumentation/user-configuration.md
    - GraphQL:
      - mo/graphql/intro.md
      - mo/graphql/reads.md
    - Release History: mo/news.md

  - LoRa:
    - Welcome: lora/index.md
    - User Documentation:
      - lora/user/agents.md
      - API:
        - Advanced:
          - lora/user/api/advanced/deleting-document.md
          - lora/user/api/advanced/file-operations.md
        - lora/user/api/create.md
        - lora/user/api/delete.md
        - lora/user/api/import.md
        - lora/user/api/list.md
        - lora/user/api/passivate.md
        - lora/user/api/read.md
        - lora/user/api/search.md
        - lora/user/api/self-documentation.md
        - lora/user/api/tutorial.md
        - Update:
          - lora/user/api/update/deleting.md
          - lora/user/api/update/merging.md
        - lora/user/api/update.md
      - lora/user/api.md
      - lora/user/auth.md
      - Bruger UML: lora/user/bruger-uml.png
      - lora/user/database.md
      - lora/user/deployment.md
      - lora/user/installation.md
      - lora/user/log-haendelse.md
      - Objects:
        - lora/user/objects/integrationdata.md
      - lora/user/objects.md
      - lora/user/operating-mox.md
      - lora/user/overview.md
      - lora/user/praesentation.md
      - lora/user/settings.md
    - Developer Documentation:
      - lora/dev/beskedfordeler.md
      - lora/dev/building-docs.md
      - lora/dev/database.md
      - lora/dev/migrations.md
      - lora/dev/news.md
      - lora/dev/test.md
      - lora/dev/testing-rest.md
      - lora/dev/wildcards.md

theme:
  name: "material"
  palette:
    - scheme:
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
  features:
    - navigation.top
    - navigation.tabs
  favicon: static/favicon.ico

# Adds Magenta's colour scheme
extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      toc_depth: 3
      permalink: "#"
