# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Command-line interface."""

import os

import typer
from more_itertools import one

from mo_ldap_import_export.config import AuthBackendEnum
from mo_ldap_import_export.config import Settings


def generate_ldapsearch_command() -> list[str]:
    """Generate an ldapsearch command from the ingration configuration."""
    settings = Settings()
    command = ["ldapsearch"]
    # Output in LDIF format without comments and version
    command.append("-LLL")
    # Configure program for SIMPLE auth
    assert (
        settings.ldap_auth_method == AuthBackendEnum.SIMPLE
    ), f"Can only generate script for {AuthBackendEnum.SIMPLE}"
    command.append("-x")
    # Configure connection string
    assert (
        len(settings.ldap_controllers) == 1
    ), "Cannot generate script for multiple LDAP controllers"
    ldap_controller = one(settings.ldap_controllers)
    ldap_url = "ldaps://" if ldap_controller.use_ssl else "ldap://"
    ldap_url += ldap_controller.host
    if ldap_controller.port:
        ldap_url += ":" + str(ldap_controller.port)
    command.append("-H")
    command.append(f'"{ldap_url}"')
    # Configure timeout
    command.append("-o")
    command.append(f"nettimeout={ldap_controller.timeout}")
    # Configure username
    command.append("-D")
    command.append(f'"{settings.ldap_user}"')
    # Configure password
    command.append("-w")
    command.append(f'"{settings.ldap_password.get_secret_value()}"')
    # Configure search base
    command.append("-b")
    command.append(f'"{settings.ldap_search_base}"')
    return command


def commandlist_to_string(command: list[str]) -> str:
    return " ".join(command)


ldapsearch = typer.Typer()


@ldapsearch.command()
def generate() -> None:
    """Generate and print the ldapsearch command."""
    print(commandlist_to_string(generate_ldapsearch_command()))


@ldapsearch.command()
def run(
    extra: list[str] | None = typer.Argument(
        None, help="Extra arguments to be added to the end of the command."
    ),
) -> None:
    """Generate and run the ldapsearch command."""
    # Ensure that extra is always a list
    extra = extra or []
    # This intentionally uses `os.system` instead of the recommended `subprocess.run`
    # as we understand the risks involved and do in fact want shell interpretation of
    # the 'extra' arguments, etc. We want this command to behave as closely as possible
    # to using the generate command followed by running the command yourself.
    #
    # The main goal of this command is providing the convenience of not having to copy
    # and paste the command generated by the generate command, as copy and paste can be
    # broken in some environments, especially in Citrix.
    os.system(commandlist_to_string(generate_ldapsearch_command() + extra))


cli = typer.Typer()
cli.add_typer(
    ldapsearch, name="ldapsearch", help="Commands related to the ldapsearch program."
)


if __name__ == "__main__":
    cli()
