# SPDX-FileCopyrightText: 2022 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

include:
  - local: .gitlab/ci/rules.gitlab-ci.yml


.lint-base:
  extends: .lint:rules:lint-all-files
  stage: lint
  needs: []
  image: python:3.9

Pre-commit:
  extends: .lint-base
  before_script:
    - pip install pre-commit pydocstyle
    - pre-commit install
    # Fetch terraform
    - TERRAFORM_VERSION="1.1.6"
    - TERRAFORM_DOWNLOAD_URL=https://releases.hashicorp.com/terraform
    - TERRAFORM_URL=${TERRAFORM_DOWNLOAD_URL}/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    - curl -o terraform_linux_amd64.zip -sL ${TERRAFORM_URL}
    - unzip terraform_linux_amd64.zip -d /usr/bin/
    - chmod +x /usr/bin/terraform
  script:
    - pre-commit run --all-files
    - pydocstyle backend/mora/graphapi/ --convention=google --add-ignore=D1

Lint Dockerfiles:
  # TODO: Do this as part of pre-commit instead
  extends: .lint-base
  image: hadolint/hadolint:latest-debian
  before_script:
    - apt-get -y update
    - apt-get -y install --no-install-recommends git
  script:
    - git ls-files --exclude='*Dockerfile*' --ignored | xargs --max-lines=1 hadolint

REUSE compliance:
  # TODO: Do this as part of pre-commit instead
  extends: .lint-base
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint

Lint shell scripts:
  # TODO: Do this as part of pre-commit instead
  extends: .lint-base
  image: koalaman/shellcheck-alpine:latest
  before_script:
    - apk update
    - apk add git
  script:
    - git ls-files --exclude='*.sh' --ignored -c | xargs shellcheck
