# SPDX-FileCopyrightText: 2022 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

include:
  - local: .gitlab/ci/rules.gitlab-ci.yml

variables:
  REVIEW_URL: "https://review-os2mo-mr$CI_MERGE_REQUEST_IID.moraci.magentahosted.dk"

# Review
#########
Deploy Review:
  stage: review
  extends:
    - .review:rules:start-review-app-pipeline
  needs:
    - Build OS2MO
  image: debian:bullseye
  variables:
    GIT_STRATEGY: none  # We do not need the source code
  before_script:
    - apt-get update && apt-get install -y curl jq
  script:
    - curl --silent --request POST --user $CONFIG_UPDATER_REVIEW_APP_USERNAME:$CONFIG_UPDATER_REVIEW_APP_PASSWORD "https://config-updater.magentahosted.dk/os2mo/review-apps/os2mo/deploy?mr_id=$CI_MERGE_REQUEST_IID&commit_sha=$CI_COMMIT_SHA"
    - until $(curl "$REVIEW_URL/version/" | jq ".mo_hash == \"$CI_COMMIT_SHA\""); do sleep 5; done
  environment:
    name: review/$CI_MERGE_REQUEST_IID
    # Cannot use $REVIEW_URL for the url because GitLab
    url: "https://review-os2mo-mr$CI_MERGE_REQUEST_IID.moraci.magentahosted.dk"
    on_stop: Stop Review
    auto_stop_in: 1 week
  tags:
    - deploy


# QA
#####
.qa-base:
  stage: qa
  extends:
    - .qa:rules:run-qa

Create Performance Test Keycloak Token:
  extends:
    - .qa-base
  needs:
    - Deploy Review
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  variables:
    TF_ADDRESS: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/terraform/state/tempotest-mr$CI_MERGE_REQUEST_IID"
    TF_VAR_keycloak_admin_password: $REVIEW_KEYCLOAK_ADMIN_PASSWORD
    TF_VAR_keycloak_url: $REVIEW_URL
    TF_VAR_keycloak_tempotest_client_secret: $REVIEW_TEMPOTEST_CLIENT_SECRET
  before_script:
    - cd tempotest/
    - gitlab-terraform init
    - gitlab-terraform validate
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
    - gitlab-terraform apply

Performance Tests:
  extends:
    - .qa-base
  needs:
    - Create Performance Test Keycloak Token
  image:
    name: $TEMPOTEST_IMAGE_SHA
    entrypoint: [""]
  tags:
    - high-mem  # we don't want other jobs impacting the test results
  script: "/k6 run /script.js --summary-export=load-performance.json"
  variables:
    MO_URL: "$REVIEW_URL"
    AUTH_SERVER: "$REVIEW_URL/auth"
    CLIENT_ID: "tempotest"
    CLIENT_SECRET: "$REVIEW_TEMPOTEST_CLIENT_SECRET"
    UPLOAD_TO_GRAFANA_SOMETHING: "false"
  artifacts:
    when: always
    reports:
      load_performance: load-performance.json


# Post-QA
##########
.post-qa-base:
  stage: post-qa

Stop Review:
  extends:
    - .post-qa-base
    - .post-qa:rules:stop-review-app
  needs: []
  image: curlimages/curl:7.81.0
  variables:
    GIT_STRATEGY: none  # We do not need the source code
  script:
    - curl --silent --request POST --user $CONFIG_UPDATER_REVIEW_APP_USERNAME:$CONFIG_UPDATER_REVIEW_APP_PASSWORD https://config-updater.magentahosted.dk/os2mo/review-apps/os2mo/undeploy?mr_id=$CI_MERGE_REQUEST_IID
  environment:
    name: review/$CI_MERGE_REQUEST_IID
    action: stop
  tags:
    - deploy

Delete Review Terraform State:
  extends:
    - .post-qa-base
    - .post-qa:rules:stop-review-app
  needs:
    - Stop Review
  image: curlimages/curl:7.81.0
  script:
    - curl --silent --request POST --user $CONFIG_UPDATER_REVIEW_APP_USERNAME:$CONFIG_UPDATER_REVIEW_APP_PASSWORD https://config-updater.magentahosted.dk/os2mo/review-apps/os2mo/delete-tf-state?mr_id=$CI_MERGE_REQUEST_IID
