# SPDX-FileCopyrightText: 2022 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

# Conditions
#############

# Global Conditions
.if-default-branch-refs: &if-default-branch-refs
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-tag: &if-tag
  if: '$CI_COMMIT_TAG'

.if-tag-semver: &if-tag-semver
  if: '$CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/'

.if-merge-request: &if-merge-request
  if: '$CI_MERGE_REQUEST_IID'

.if-schedule: &if-schedule
  if: '$CI_PIPELINE_SOURCE == "schedule"'

# Sync Conditions
.if-merge-request-labels-dont-interrupt: &if-merge-request-labels-dont-interrupt
  if: "$CI_MERGE_REQUEST_LABELS =~ /Pipeline::Don't Interrupt/"

# Review / QA Conditions
.if-merge-request-labels-run-review-app: &if-merge-request-labels-run-review-app
  if: '$CI_MERGE_REQUEST_LABELS =~ /Pipeline::Run Review App/'

.if-merge-request-labels-run-qa: &if-merge-request-labels-run-qa
  if: '$CI_MERGE_REQUEST_LABELS =~ /Pipeline::Run QA/'


# Rules
########

# Workflow Rules
.workflow:rules:
  rules:
    - <<: *if-tag
    - <<: *if-default-branch-refs
    - <<: *if-merge-request

# Sync Rules
.sync:rules:dont-interrupt-me:
  rules:
    - <<: *if-default-branch-refs
    - <<: *if-schedule
    - <<: *if-merge-request-labels-dont-interrupt
    - when: manual
      allow_failure: true

# Lint Rules
.lint:rules:lint-all-files:
  # TODO: Individual lint rules for each file type using 'changes' patterns
  rules:
    - <<: *if-merge-request

# Build Rules
.build:rules:build-release-image:
  rules:
    - <<: *if-schedule
      when: never
    - when: on_success

.build:rules:build-test-image:
  rules:
    - <<: *if-merge-request

# Test / Coverage Rules
.test:rules:run-tests:
  rules:
    - <<: *if-merge-request

# Review Rules
.review:rules:start-review-app-pipeline:
  rules:
    - <<: *if-default-branch-refs
    - <<: *if-merge-request-labels-run-review-app
    - <<: *if-merge-request-labels-run-qa
    - <<: *if-merge-request
      when: manual
      allow_failure: true

# QA Rules
.qa:rules:run-qa:
  rules:
    - <<: *if-default-branch-refs
    - <<: *if-merge-request-labels-run-qa
    - <<: *if-merge-request
      when: manual
      allow_failure: true

# Post-QA Rules
.post-qa:rules:stop-review-app:
  rules:
    - <<: *if-default-branch-refs
    - <<: *if-merge-request
      when: manual
      allow_failure: true

# Docs Rules
.docs:rules:build-docs:
  rules:
    - !reference [".docs:rules:deploy-branch-docs", rules]
    - !reference [".docs:rules:deploy-master-docs", rules]

.docs:rules:deploy-branch-docs:
  rules:
    - <<: *if-merge-request

.docs:rules:deploy-master-docs:
  rules:
    - <<: *if-schedule
      when: never
    - <<: *if-tag-semver
      when: never
    - <<: *if-default-branch-refs
