# SPDX-FileCopyrightText: 2022 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

include:
  - local: .gitlab/ci/rules.gitlab-ci.yml

dont-interrupt-me:
  extends: .sync:rules:dont-interrupt-me
  stage: sync
  image: alpine:latest
  interruptible: false
  variables:
    GIT_STRATEGY: none
  script:
    - echo "This jobs makes sure this pipeline won't be interrupted!"
    - echo "It works because you cannot cancel subsequent jobs after a job with interruptible=false starts."
    - echo "See https://docs.gitlab.com/ee/ci/yaml/#interruptible for more information."
